#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Build seo_bulk_waveNN_cities_data.py from CSV seeds + dedupe against site slugs."""
from __future__ import annotations

import argparse
import csv
import re
from pathlib import Path

STATE_META: dict[str, tuple[str, str]] = {
    "AL": ("alabama-mahjong.html", "alabama-mahjong-hub.html"),
    "AK": ("alaska-mahjong.html", "alaska-mahjong-hub.html"),
    "AZ": ("arizona-mahjong.html", "arizona-mahjong-hub.html"),
    "AR": ("arkansas-mahjong.html", "arkansas-mahjong-hub.html"),
    "CA": ("california-mahjong.html", "california-mahjong-hub.html"),
    "CO": ("colorado-mahjong.html", "colorado-mahjong-hub.html"),
    "CT": ("connecticut-mahjong.html", "connecticut-mahjong-hub.html"),
    "DE": ("delaware-mahjong.html", "delaware-mahjong-hub.html"),
    "FL": ("florida-mahjong.html", "florida-mahjong-hub.html"),
    "GA": ("georgia-mahjong.html", "georgia-mahjong-hub.html"),
    "HI": ("hawaii-mahjong.html", "hawaii-mahjong-hub.html"),
    "ID": ("idaho-mahjong.html", "idaho-mahjong-hub.html"),
    "IL": ("illinois-mahjong.html", "illinois-mahjong-hub.html"),
    "IN": ("indiana-mahjong.html", "indiana-mahjong-hub.html"),
    "IA": ("iowa-mahjong.html", "iowa-mahjong-hub.html"),
    "KS": ("kansas-mahjong.html", "kansas-mahjong-hub.html"),
    "KY": ("kentucky-mahjong.html", "kentucky-mahjong-hub.html"),
    "LA": ("louisiana-mahjong.html", "louisiana-mahjong-hub.html"),
    "ME": ("maine-mahjong.html", "maine-mahjong-hub.html"),
    "MD": ("maryland-mahjong.html", "maryland-mahjong-hub.html"),
    "MA": ("massachusetts-mahjong.html", "massachusetts-mahjong-hub.html"),
    "MI": ("michigan-mahjong.html", "michigan-mahjong-hub.html"),
    "MN": ("minnesota-mahjong.html", "minnesota-mahjong-hub.html"),
    "MS": ("mississippi-mahjong.html", "mississippi-mahjong-hub.html"),
    "MO": ("missouri-mahjong.html", "missouri-mahjong-hub.html"),
    "MT": ("montana-mahjong.html", "montana-mahjong-hub.html"),
    "NE": ("nebraska-mahjong.html", "nebraska-mahjong-hub.html"),
    "NV": ("nevada-mahjong.html", "nevada-mahjong-hub.html"),
    "NH": ("new-hampshire-mahjong.html", "new-hampshire-mahjong-hub.html"),
    "NJ": ("new-jersey-mahjong.html", "new-jersey-mahjong-hub.html"),
    "NM": ("new-mexico-mahjong.html", "new-mexico-mahjong-hub.html"),
    "NY": ("new-york-mahjong.html", "new-york-mahjong-hub.html"),
    "NC": ("north-carolina-mahjong.html", "north-carolina-mahjong-hub.html"),
    "ND": ("north-dakota-mahjong.html", "north-dakota-mahjong-hub.html"),
    "OH": ("ohio-mahjong.html", "ohio-mahjong-hub.html"),
    "OK": ("oklahoma-mahjong.html", "oklahoma-mahjong-hub.html"),
    "OR": ("oregon-mahjong.html", "oregon-mahjong-hub.html"),
    "PA": ("pennsylvania-mahjong.html", "pennsylvania-mahjong-hub.html"),
    "RI": ("rhode-island-mahjong.html", "rhode-island-mahjong-hub.html"),
    "SC": ("south-carolina-mahjong.html", "south-carolina-mahjong-hub.html"),
    "SD": ("south-dakota-mahjong.html", "south-dakota-mahjong-hub.html"),
    "TN": ("tennessee-mahjong.html", "tennessee-mahjong-hub.html"),
    "TX": ("texas-mahjong.html", "texas-mahjong-hub.html"),
    "UT": ("utah-mahjong.html", "utah-mahjong-hub.html"),
    "VT": ("vermont-mahjong.html", "vermont-mahjong-hub.html"),
    "VA": ("virginia-mahjong.html", "virginia-mahjong-hub.html"),
    "WA": ("washington-state-mahjong.html", "washington-mahjong-hub.html"),
    "WV": ("west-virginia-mahjong.html", "west-virginia-mahjong-hub.html"),
    "WI": ("wisconsin-mahjong.html", "wisconsin-mahjong-hub.html"),
    "WY": ("wyoming-mahjong.html", "wyoming-mahjong-hub.html"),
}

STATE_NAME_TO_ABBR = {
    "Alabama": "AL",
    "Alaska": "AK",
    "Arizona": "AZ",
    "Arkansas": "AR",
    "California": "CA",
    "Colorado": "CO",
    "Connecticut": "CT",
    "Delaware": "DE",
    "Florida": "FL",
    "Georgia": "GA",
    "Hawaii": "HI",
    "Idaho": "ID",
    "Illinois": "IL",
    "Indiana": "IN",
    "Iowa": "IA",
    "Kansas": "KS",
    "Kentucky": "KY",
    "Louisiana": "LA",
    "Maine": "ME",
    "Maryland": "MD",
    "Massachusetts": "MA",
    "Michigan": "MI",
    "Minnesota": "MN",
    "Mississippi": "MS",
    "Missouri": "MO",
    "Montana": "MT",
    "Nebraska": "NE",
    "Nevada": "NV",
    "New Hampshire": "NH",
    "New Jersey": "NJ",
    "New Mexico": "NM",
    "New York": "NY",
    "North Carolina": "NC",
    "North Dakota": "ND",
    "Ohio": "OH",
    "Oklahoma": "OK",
    "Oregon": "OR",
    "Pennsylvania": "PA",
    "Rhode Island": "RI",
    "South Carolina": "SC",
    "South Dakota": "SD",
    "Tennessee": "TN",
    "Texas": "TX",
    "Utah": "UT",
    "Vermont": "VT",
    "Virginia": "VA",
    "Washington": "WA",
    "West Virginia": "WV",
    "Wisconsin": "WI",
    "Wyoming": "WY",
}

# Extra towns/suburbs beyond plotly top-1k (state_abbr -> city names)
EXTRA_CITIES: dict[str, list[str]] = {
    "GA": [
        "Dunwoody",
        "Sandy Springs",
        "Johns Creek",
        "Milton",
        "Peachtree Corners",
        "Sugar Hill",
        "Winder",
        "Monroe",
        "Conyers",
        "Stockbridge",
        "McDonough",
        "Griffin",
        "LaGrange",
        "Thomasville",
        "Statesboro",
        "Waycross",
        "Milledgeville",
        "Cartersville",
        "Calhoun",
        "Toccoa",
    ],
    "TN": [
        "Spring Hill",
        "Thompson's Station",
        "Nolensville",
        "Brentwood",
        "Springfield",
        "Tullahoma",
        "Smyrna",
        "La Vergne",
        "Lebanon",
        "Mount Juliet",
        "Hendersonville",
        "Portland",
        "Dickson",
        "McMinnville",
        "Shelbyville",
    ],
    "NC": [
        "Apex",
        "Holly Springs",
        "Wake Forest",
        "Garner",
        "Clayton",
        "Morrisville",
        "Fuquay-Varina",
        "Lumberton",
        "Sanford",
        "Albemarle",
        "Kernersville",
        "Thomasville",
        "Lexington",
        "Mooresville",
        "Huntersville",
        "Cornelius",
        "Davidson",
        "Stallings",
        "Weddington",
        "Matthews",
    ],
    "SC": [
        "Fort Mill",
        "Tega Cay",
        "Rock Hill",
        "Sumter",
        "Florence",
        "Myrtle Beach",
        "North Augusta",
        "Aiken",
        "Beaufort",
        "Bluffton",
        "Port Royal",
        "Georgetown",
        "Lancaster",
        "Camden",
        "Orangeburg",
    ],
    "FL": [
        "Wellington",
        "Royal Palm Beach",
        "Lake Worth",
        "Greenacres",
        "Palm Springs",
        "North Miami",
        "Coral Gables",
        "Hialeah",
        "Doral",
        "Cutler Bay",
        "Homestead",
        "Winter Garden",
        "Ocoee",
        "Altamonte Springs",
        "Kissimmee",
        "St Cloud",
    ],
    "TX": [
        "Sugar Land",
        "Missouri City",
        "Pearland",
        "League City",
        "Bay City",
        "Port Arthur",
        "Nacogdoches",
        "Lufkin",
        "Paris",
        "Greenville",
        "Wichita Falls",
        "San Angelo",
        "Del Rio",
        "Eagle Pass",
        "Uvalde",
        "Kerrville",
        "Seguin",
        "Kyle",
        "Buda",
        "Pflugerville",
    ],
    "CA": [
        "Irvine",
        "Newport Beach",
        "Laguna Beach",
        "Dana Point",
        "San Clemente",
        "Mission Viejo",
        "Lake Forest",
        "Huntington Beach",
        "Fullerton",
        "Anaheim",
        "Garden Grove",
        "Costa Mesa",
        "Tustin",
        "Yorba Linda",
        "Brea",
        "La Habra",
        "Whittier",
        "Torrance",
        "Manhattan Beach",
        "Redondo Beach",
    ],
    "NY": [
        "Scarsdale",
        "Rye",
        "Mamaroneck",
        "Larchmont",
        "Harrison",
        "Mount Kisco",
        "Peekskill",
        "Beacon",
        "Middletown",
        "Kingston",
        "Saratoga Springs",
        "Glens Falls",
        "Plattsburgh",
        "Olean",
        "Jamestown",
    ],
    "PA": [
        "Media",
        "Wayne",
        "Ardmore",
        "Bryn Mawr",
        "Conshohocken",
        "Lansdale",
        "Doylestown",
        "New Hope",
        "Lititz",
        "Hanover",
        "Carlisle",
        "Chambersburg",
        "Indiana",
        "Butler",
        "Greensburg",
    ],
    "OH": [
        "Dublin",
        "Westerville",
        "Gahanna",
        "Reynoldsburg",
        "Grove City",
        "Hilliard",
        "Upper Arlington",
        "Worthington",
        "Mason",
        "Fairfield",
        "Hamilton",
        "Middletown",
        "Springfield",
        "Lima",
        "Findlay",
    ],
    "MI": [
        "Troy",
        "Novi",
        "Farmington Hills",
        "Southfield",
        "Royal Oak",
        "Birmingham",
        "Rochester Hills",
        "Shelby Township",
        "Macomb",
        "Clinton Township",
        "Bay City",
        "Saginaw",
        "Midland",
        "Muskegon",
        "Holland",
    ],
    "IL": [
        "Naperville",
        "Aurora",
        "Joliet",
        "Elgin",
        "Waukegan",
        "Cicero",
        "Bloomington",
        "Champaign",
        "Decatur",
        "Peoria",
        "Rockford",
        "Springfield",
        "Quincy",
        "Carbondale",
        "Normal",
    ],
    "CO": [
        "Castle Rock",
        "Parker",
        "Lone Tree",
        "Highlands Ranch",
        "Centennial",
        "Aurora",
        "Thornton",
        "Northglenn",
        "Brighton",
        "Greeley",
        "Fort Morgan",
        "Sterling",
        "Trinidad",
        "Montrose",
        "Durango",
    ],
    "AZ": [
        "Scottsdale",
        "Paradise Valley",
        "Tempe",
        "Mesa",
        "Glendale",
        "Peoria",
        "Surprise",
        "Goodyear",
        "Avondale",
        "Flagstaff",
        "Sedona",
        "Kingman",
        "Yuma",
        "Nogales",
        "Sierra Vista",
    ],
    "WA": [
        "Redmond",
        "Kirkland",
        "Issaquah",
        "Sammamish",
        "Renton",
        "Kent",
        "Federal Way",
        "Auburn",
        "Puyallup",
        "Lacey",
        "Olympia",
        "Bremerton",
        "Wenatchee",
        "Yakima",
        "Walla Walla",
    ],
    "OR": [
        "Lake Oswego",
        "Tigard",
        "Beaverton",
        "Hillsboro",
        "Gresham",
        "Oregon City",
        "Grants Pass",
        "Medford",
        "Klamath Falls",
        "Bend",
        "Redmond",
        "Corvallis",
        "Albany",
        "McMinnville",
        "Newberg",
    ],
    "VA": [
        "Reston",
        "Herndon",
        "Vienna",
        "McLean",
        "Great Falls",
        "Falls Church",
        "McLean",
        "Manassas",
        "Woodbridge",
        "Fredericksburg",
        "Williamsburg",
        "Yorktown",
        "Poquoson",
        "Smithfield",
        "Suffolk",
    ],
    "MD": [
        "Bethesda",
        "Chevy Chase",
        "Rockville",
        "Gaithersburg",
        "Germantown",
        "Frederick",
        "Hagerstown",
        "Annapolis",
        "Easton",
        "Salisbury",
        "Ocean City",
        "Cambridge",
        "La Plata",
        "Bowie",
        "College Park",
    ],
    "NJ": [
        "Princeton",
        "Lawrenceville",
        "Freehold",
        "Red Bank",
        "Long Branch",
        "Asbury Park",
        "Ocean City",
        "Vineland",
        "Millville",
        "Bridgeton",
        "Cape May",
        "Wildwood",
        "Atlantic City",
        "Margate City",
        "Somers Point",
    ],
    "MA": [
        "Newton",
        "Brookline",
        "Wellesley",
        "Needham",
        "Lexington",
        "Concord",
        "Sudbury",
        "Framingham",
        "Natick",
        "Waltham",
        "Arlington",
        "Belmont",
        "Marblehead",
        "Swampscott",
        "Newburyport",
    ],
    "CT": [
        "Greenwich",
        "Stamford",
        "Darien",
        "Westport",
        "Fairfield",
        "Trumbull",
        "Milford",
        "Guilford",
        "Madison",
        "Old Saybrook",
        "Mystic",
        "Stonington",
        "Litchfield",
        "Torrington",
        "Simsbury",
    ],
    "MN": [
        "Edina",
        "Minnetonka",
        "Plymouth",
        "Maple Grove",
        "Blaine",
        "Lakeville",
        "Apple Valley",
        "Eagan",
        "Woodbury",
        "Stillwater",
        "Mankato",
        "Rochester",
        "Duluth",
        "Bemidji",
        "Brainerd",
    ],
    "WI": [
        "Brookfield",
        "Wauwatosa",
        "Mequon",
        "Oconomowoc",
        "Lake Geneva",
        "Sheboygan",
        "Fond du Lac",
        "Appleton",
        "Oshkosh",
        "Wausau",
        "Rhinelander",
        "Stevens Point",
        "La Crosse",
        "Eau Claire",
        "Superior",
    ],
    "MO": [
        "Chesterfield",
        "Ballwin",
        "Wildwood",
        "O'Fallon",
        "St Charles",
        "St Peters",
        "Wentzville",
        "Lake St Louis",
        "Cape Girardeau",
        "Poplar Bluff",
        "Sikeston",
        "Rolla",
        "Warrensburg",
        "Sedalia",
        "Jefferson City",
    ],
    "LA": [
        "Metairie",
        "Kenner",
        "Slidell",
        "Mandeville",
        "Covington",
        "Hammond",
        "Thibodaux",
        "Houma",
        "Morgan City",
        "Opelousas",
        "Ruston",
        "Monroe",
        "Alexandria",
        "Lake Charles",
        "Sulphur",
    ],
    "KY": [
        "Bowling Green",
        "Richmond",
        "Georgetown",
        "Florence",
        "Covington",
        "Newport",
        "Ashland",
        "Morehead",
        "Somerset",
        "London",
        "Campbellsville",
        "Murray",
        "Paducah",
        "Henderson",
        "Madisonville",
    ],
    "IN": [
        "Carmel",
        "Fishers",
        "Noblesville",
        "Greenwood",
        "Bloomington",
        "Columbus",
        "Jeffersonville",
        "New Albany",
        "Muncie",
        "Anderson",
        "Kokomo",
        "Lafayette",
        "West Lafayette",
        "Terre Haute",
        "Evansville",
    ],
    "IA": [
        "West Des Moines",
        "Ankeny",
        "Urbandale",
        "Johnston",
        "Coralville",
        "Iowa City",
        "Waterloo",
        "Cedar Falls",
        "Dubuque",
        "Sioux City",
        "Council Bluffs",
        "Mason City",
        "Fort Dodge",
        "Burlington",
        "Muscatine",
    ],
    "KS": [
        "Overland Park",
        "Olathe",
        "Lenexa",
        "Shawnee",
        "Manhattan",
        "Lawrence",
        "Hutchinson",
        "Salina",
        "Dodge City",
        "Garden City",
        "Emporia",
        "Pittsburg",
        "Hays",
        "Great Bend",
        "McPherson",
    ],
    "NE": [
        "Grand Island",
        "Kearney",
        "Norfolk",
        "Columbus",
        "Fremont",
        "Bellevue",
        "Papillion",
        "La Vista",
        "Scottsbluff",
        "North Platte",
        "Hastings",
        "Beatrice",
        "McCook",
        "Alliance",
        "Sidney",
    ],
    "OK": [
        "Broken Arrow",
        "Edmond",
        "Norman",
        "Moore",
        "Stillwater",
        "Enid",
        "Lawton",
        "Muskogee",
        "Ada",
        "Durant",
        "Ardmore",
        "Ponca City",
        "Bartlesville",
        "Guthrie",
        "Claremore",
    ],
    "AR": [
        "Fayetteville",
        "Springdale",
        "Rogers",
        "Bentonville",
        "Conway",
        "Jonesboro",
        "Paragould",
        "Hot Springs",
        "Texarkana",
        "El Dorado",
        "Magnolia",
        "Camden",
        "Arkadelphia",
        "Batesville",
        "Mountain Home",
    ],
    "MS": [
        "Gulfport",
        "Biloxi",
        "Hattiesburg",
        "Meridian",
        "Tupelo",
        "Greenville",
        "Oxford",
        "Starkville",
        "Columbus",
        "Vicksburg",
        "Natchez",
        "Laurel",
        "McComb",
        "Brookhaven",
        "Picayune",
    ],
    "AL": [
        "Madison",
        "Decatur",
        "Florence",
        "Huntsville",
        "Dothan",
        "Auburn",
        "Opelika",
        "Tuscaloosa",
        "Gadsden",
        "Anniston",
        "Cullman",
        "Enterprise",
        "Selma",
        "Prattville",
        "Fairhope",
    ],
    "UT": [
        "St George",
        "Cedar City",
        "Logan",
        "Ogden",
        "Layton",
        "Bountiful",
        "Draper",
        "Sandy",
        "Murray",
        "Orem",
        "Provo",
        "Lehi",
        "American Fork",
        "Park City",
        "Heber City",
    ],
    "NM": [
        "Las Cruces",
        "Roswell",
        "Carlsbad",
        "Hobbs",
        "Farmington",
        "Gallup",
        "Taos",
        "Santa Fe",
        "Los Alamos",
        "Ruidoso",
        "Alamogordo",
        "Silver City",
        "Deming",
        "Clovis",
        "Portales",
    ],
    "NV": [
        "Henderson",
        "North Las Vegas",
        "Summerlin",
        "Boulder City",
        "Mesquite",
        "Laughlin",
        "Pahrump",
        "Elko",
        "Fallon",
        "Winnemucca",
        "Incline Village",
        "Stateline",
        "Minden",
        "Fernley",
        "Carson City",
    ],
    "ID": [
        "Meridian",
        "Nampa",
        "Caldwell",
        "Twin Falls",
        "Idaho Falls",
        "Pocatello",
        "Coeur d'Alene",
        "Post Falls",
        "Moscow",
        "Lewiston",
        "Sun Valley",
        "Ketchum",
        "Hailey",
        "Sandpoint",
        "Rexburg",
    ],
    "MT": [
        "Bozeman",
        "Missoula",
        "Kalispell",
        "Whitefish",
        "Helena",
        "Great Falls",
        "Billings",
        "Butte",
        "Havre",
        "Miles City",
        "Livingston",
        "Red Lodge",
        "Big Sky",
        "Hamilton",
        "Dillon",
    ],
    "WY": [
        "Jackson",
        "Cody",
        "Sheridan",
        "Gillette",
        "Casper",
        "Laramie",
        "Cheyenne",
        "Rock Springs",
        "Green River",
        "Riverton",
        "Lander",
        "Powell",
        "Worland",
        "Rawlins",
        "Evanston",
    ],
    "ND": [
        "Fargo",
        "Bismarck",
        "Minot",
        "Grand Forks",
        "Williston",
        "Dickinson",
        "Mandan",
        "Jamestown",
        "Wahpeton",
        "Devils Lake",
        "Valley City",
        "Watford City",
        "Rugby",
        "Grafton",
        "Beulah",
    ],
    "SD": [
        "Sioux Falls",
        "Rapid City",
        "Aberdeen",
        "Brookings",
        "Watertown",
        "Mitchell",
        "Yankton",
        "Pierre",
        "Huron",
        "Vermillion",
        "Spearfish",
        "Sturgis",
        "Deadwood",
        "Lead",
        "Hot Springs",
    ],
    "HI": [
        "Kailua",
        "Kaneohe",
        "Pearl City",
        "Mililani",
        "Ewa Beach",
        "Kapolei",
        "Waipahu",
        "Hilo",
        "Kona",
        "Waimea",
        "Lahaina",
        "Kihei",
        "Wailuku",
        "Lihue",
        "Princeville",
    ],
    "AK": [
        "Anchorage",
        "Fairbanks",
        "Juneau",
        "Wasilla",
        "Sitka",
        "Ketchikan",
        "Kenai",
        "Kodiak",
        "Homer",
        "Soldotna",
        "Palmer",
        "Valdez",
        "Nome",
        "Bethel",
        "Cordova",
    ],
    "ME": [
        "Portland",
        "Bangor",
        "Augusta",
        "Bar Harbor",
        "Kennebunk",
        "Freeport",
        "Rockland",
        "Camden",
        "Belfast",
        "Bath",
        "Brunswick",
        "Waterville",
        "Ellsworth",
        "Presque Isle",
        "Caribou",
    ],
    "VT": [
        "Burlington",
        "Montpelier",
        "Stowe",
        "Killington",
        "Woodstock",
        "Manchester",
        "Bennington",
        "Brattleboro",
        "Rutland",
        "Middlebury",
        "St Albans",
        "Essex Junction",
        "Williston",
        "South Burlington",
        "Waterbury",
    ],
    "NH": [
        "Manchester",
        "Nashua",
        "Concord",
        "Portsmouth",
        "Exeter",
        "Hanover",
        "Lebanon",
        "Keene",
        "Laconia",
        "Wolfeboro",
        "Meredith",
        "North Conway",
        "Jackson",
        "Lincoln",
        "Dover",
    ],
    "RI": [
        "Providence",
        "Newport",
        "Warwick",
        "Cranston",
        "Pawtucket",
        "East Greenwich",
        "Westerly",
        "Narragansett",
        "Bristol",
        "Barrington",
        "South Kingstown",
        "North Kingstown",
        "Jamestown",
        "Block Island",
        "Woonsocket",
    ],
    "DE": [
        "Wilmington",
        "Dover",
        "Newark",
        "Rehoboth Beach",
        "Lewes",
        "Bethany Beach",
        "Fenwick Island",
        "Milton",
        "Georgetown",
        "Seaford",
        "Milford",
        "Smyrna",
        "Middletown",
        "New Castle",
        "Hockessin",
    ],
    "WV": [
        "Charleston",
        "Huntington",
        "Morgantown",
        "Wheeling",
        "Parkersburg",
        "Lewisburg",
        "Beckley",
        "Martinsburg",
        "Shepherdstown",
        "Harpers Ferry",
        "Charles Town",
        "Summersville",
        "Elkins",
        "Buckhannon",
        "Ripley",
    ],
}

# Southeast-only mega wave: GA, TN, NC, SC, AL, FL + travel states KY, MS, LA, VA, AR
SOUTHEAST_STATES = frozenset({"GA", "TN", "NC", "SC", "AL", "FL", "KY", "MS", "LA", "VA", "AR"})

SOUTHEAST_EXTRA: dict[str, list[str]] = {
    "GA": [
        "Canton", "Woodstock", "Cumming", "Dahlonega", "Blue Ridge", "Helen", "Clayton",
        "Hiawassee", "Blairsville", "Jasper", "Dallas", "Douglasville", "Newnan", "Fayetteville",
        "Peachtree City", "Tyrone", "Sharpsburg", "LaGrange", "Americus", "Cordele", "Valdosta",
        "Brunswick", "Jekyll Island", "St Marys", "Vidalia", "Dublin", "Swainsboro", "Elberton",
        "Hartwell", "Washington", "Thomson", "Madison", "Eatonton", "Monticello", "Social Circle",
        "Covington", "Monroe", "Loganville", "Snellville", "Lilburn", "Stone Mountain", "Tucker",
        "Decatur", "Brookhaven", "Chamblee", "Doraville", "Roswell", "Marietta", "Kennesaw",
        "Acworth", "Cartersville", "Rome", "Calhoun", "Dalton", "Chatsworth", "Cleveland",
    ],
    "TN": [
        "Sewanee", "Winchester", "Tullahoma", "Shelbyville", "Lewisburg", "Pulaski", "Lawrenceburg",
        "Columbia", "McMinnville", "Sparta", "Crossville", "Cookeville", "Livingston", "Jamestown",
        "Oneida", "Rockwood", "Kingston", "Lenoir City", "Oak Ridge", "Clinton", "Harriman",
        "Sweetwater", "Athens", "Etowah", "Dayton", "Dunlap", "Signal Mountain", "Red Bank",
        "East Ridge", "Soddy Daisy", "Collegedale", "Ooltewah", "Apison", "Hixson", "Middle Valley",
        "Powell", "Farragut", "Alcoa", "Sevierville", "Pigeon Forge", "Townsend", "Wears Valley",
        "Tellico Plains", "Vonore", "Madisonville", "Newport", "Rogersville", "Greeneville",
    ],
    "NC": [
        "Southern Pines", "Pinehurst", "Aberdeen", "Sanford", "Lillington", "Smithfield",
        "Selma", "Goldsboro", "Kinston", "New Bern", "Havelock", "Morehead City", "Beaufort",
        "Atlantic Beach", "Emerald Isle", "Swansboro", "Jacksonville", "Lumberton", "Whiteville",
        "Southport", "Oak Island", "Sunset Beach", "Calabash", "Shallotte", "Elizabethtown",
        "Laurinburg", "Rockingham", "Hamlet", "Asheboro", "Lexington", "Thomasville", "High Point",
        "Jamestown", "Summerfield", "Oak Ridge", "King", "Mount Airy", "Elkin", "North Wilkesboro",
        "Lenoir", "Morganton", "Marion", "Black Mountain", "Weaverville", "Mars Hill", "Brevard",
        "Sylva", "Franklin", "Highlands", "Cashiers", "Cherokee", "Murphy", "Andrews",
    ],
    "SC": [
        "Clemson", "Seneca", "Easley", "Pickens", "Liberty", "Williamston", "Anderson",
        "Belton", "Honea Path", "Abbeville", "Greenwood", "Laurens", "Clinton", "Newberry",
        "Winnsboro", "Blythewood", "Irmo", "Lexington", "West Columbia", "Cayce", "Batesburg-Leesville",
        "Orangeburg", "Bamberg", "Walterboro", "Ridgeland", "Hardeeville", "Beaufort", "Port Royal",
        "Folly Beach", "Isle of Palms", "Sullivan's Island", "Goose Creek", "Moncks Corner",
        "Georgetown", "Murrells Inlet", "Surfside Beach", "Conway", "Little River", "North Myrtle Beach",
        "Loris", "Bennettsville", "Dillon", "Marion", "Lake City", "Manning", "Bishopville",
    ],
    "AL": [
        "Trussville", "Homewood", "Mountain Brook", "Vestavia Hills", "Pelham", "Alabaster",
        "Calera", "Helena", "Chelsea", "Sylacauga", "Alexander City", "Eufaula", "Ozark",
        "Andalusia", "Atmore", "Bay Minette", "Foley", "Spanish Fort", "Daphne", "Saraland",
        "Tillmans Corner", "Theodore", "Satsuma", "Citronelle", "Monroeville", "Thomasville",
        "Demopolis", "Livingston", "Camden", "Greenville", "Troy", "Ozark", "Headland",
        "Geneva", "Hartselle", "Athens AL", "Moulton", "Russellville", "Jasper AL", "Oneonta",
        "Guntersville", "Scottsboro", "Fort Payne", "Albertville", "Boaz", "Pell City", "Leeds",
    ],
    "FL": [
        "Ponte Vedra Beach", "Atlantic Beach", "Neptune Beach", "Fernandina Beach", "Amelia Island",
        "St Augustine Beach", "Palm Coast", "Flagler Beach", "New Smyrna Beach", "Edgewater",
        "Titusville", "Melbourne Beach", "Indialantic", "Sebastian", "Stuart", "Jensen Beach",
        "Hobe Sound", "Tequesta", "Lantana", "Manalapan", "Highland Beach", "Deerfield Beach",
        "Lauderdale-by-the-Sea", "Sea Ranch Lakes", "Pembroke Pines", "Miramar", "Cooper City",
        "Davie", "Plantation", "Sunrise", "Coral Springs", "Parkland", "Margate", "Tamarac",
        "North Port", "Venice", "Englewood", "Punta Gorda", "Port Charlotte", "Placida",
        "Boca Grande", "Captiva", "Sanibel", "Estero", "Bonita Springs", "Marco Island",
        "Immokalee", "LaBelle", "Clewiston", "Belle Glade", "Lake Placid", "Avon Park",
    ],
    "KY": [
        "Danville", "Bardstown", "Shelbyville", "La Grange", "Prospect", "Anchorage",
        "St Matthews", "Jeffersontown", "Mount Washington", "Shepherdsville", "Elizabethtown",
        "Radcliff", "Campbellsville", "Somerset", "London", "Corbin", "Williamsburg", "Barbourville",
        "Middlesboro", "Pikeville", "Prestonsburg", "Paintsville", "Ashland", "Morehead",
        "Maysville", "Winchester", "Richmond", "Berea", "Nicholasville", "Wilmore", "Harrodsburg",
        "Frankfort", "Paris", "Georgetown KY", "Cynthiana", "Maysville", "Murray", "Mayfield",
        "Paducah", "Hopkinsville", "Madisonville", "Owensboro", "Henderson", "Bowling Green",
    ],
    "MS": [
        "Ocean Springs", "Gautier", "Pascagoula", "Long Beach", "Pass Christian", "Bay St Louis",
        "Waveland", "Diamondhead", "D'Iberville", "Gulfport", "Starkville", "West Point",
        "Columbus MS", "Starkville", "Philadelphia", "Meridian", "Laurel", "Hattiesburg",
        "Petal", "Purvis", "Poplarville", "Wiggins", "Lucedale", "Moss Point", "Corinth",
        "Booneville", "New Albany", "Oxford", "Batesville", "Clarksdale", "Greenville MS",
        "Cleveland MS", "Indianola", "Yazoo City", "Ridgeland", "Madison MS", "Brandon",
        "Pearl", "Clinton MS", "Flowood", "Ridgeland", "Canton MS", "Brookhaven", "McComb",
    ],
    "LA": [
        "Mandeville", "Covington", "Slidell", "Hammond", "Ponchatoula", "Houma", "Thibodaux",
        "Morgan City", "Franklin", "Abbeville LA", "Jennings", "Sulphur", "Westlake", "DeRidder",
        "Leesville", "Natchitoches", "Ruston", "Monroe", "West Monroe", "Bastrop", "Minden",
        "Bossier City", "Shreveport", "Natchitoches", "Alexandria", "Pineville", "Marksville",
        "Opelousas", "Crowley", "Lafayette", "Youngsville", "Broussard", "Scott", "Breaux Bridge",
        "St Martinville", "New Iberia", "Donaldsonville", "Plaquemine", "Gonzales", "Denham Springs",
        "Walker", "Zachary", "Central", "Baker", "Port Allen", "Brusly", "St Francisville",
    ],
    "VA": [
        "Williamsburg", "Yorktown", "Poquoson", "Hampton", "Newport News", "Portsmouth",
        "Suffolk", "Chesapeake", "Virginia Beach", "Norfolk", "Smithfield", "Isle of Wight",
        "Franklin VA", "Emporia", "South Boston", "Danville", "Martinsville", "Bassett",
        "Rocky Mount", "Bedford", "Lynchburg", "Forest", "Amherst", "Farmville", "Blackstone",
        "Petersburg", "Colonial Heights", "Hopewell", "Prince George", "Chester", "Midlothian",
        "Glen Allen", "Short Pump", "Mechanicsville", "Ashland", "Colonial Beach", "Kilmarnock",
        "Irvington", "Onancock", "Chincoteague", "Exmore", "Cape Charles", "Lexington VA",
        "Staunton", "Waynesboro", "Harrisonburg", "Front Royal", "Luray", "Shenandoah",
    ],
    "AR": [
        "Bentonville", "Rogers", "Bella Vista", "Siloam Springs", "Searcy", "Batesville",
        "Heber Springs", "Greers Ferry", "Hot Springs Village", "Mena", "De Queen", "Hope",
        "Camden", "El Dorado", "Magnolia", "Stuttgart", "Forrest City", "West Memphis",
        "Blytheville", "Paragould", "Jonesboro", "Batesville", "Mountain Home", "Harrison",
        "Eureka Springs", "Russellville", "Clarksville", "Conway", "Maumelle", "Sherwood",
        "Jacksonville AR", "Cabot", "Bryant", "Searcy", "Russellville", "Arkadelphia", "Malvern",
    ],
}


def slugify(text: str) -> str:
    text = text.lower().replace(".", "").replace("'", "")
    text = re.sub(r"[^a-z0-9]+", "-", text).strip("-")
    return text


def collect_existing(root: Path) -> set[str]:
    existing: set[str] = set()
    for p in root.glob("*.html"):
        existing.add(p.name)
    for fp in root.glob("*.py"):
        if fp.name.startswith("seo_bulk") or fp.name == "generate-seo-pages.py":
            t = fp.read_text(encoding="utf-8", errors="ignore")
            for pat in (
                r'city\("([^"]+)"',
                r'page\("([^"]+)"',
                r'mahjong_kw\("([^"]+)"',
            ):
                existing.update(re.findall(pat, t))
    return existing


def make_slug(city: str, st: str, existing: set[str], used: set[str]) -> str:
    base = slugify(city)
    stl = st.lower()
    for cand in (f"{base}-{stl}-mahjong.html", f"{base}-{stl}-{stl}-mahjong.html"):
        if cand not in existing and cand not in used:
            return cand
    n = 2
    while True:
        cand = f"{base}-{stl}-{n}-mahjong.html"
        if cand not in existing and cand not in used:
            return cand
        n += 1


def iter_seed_cities(csv_path: Path | None, *, southeast_only: bool = False) -> list[tuple[str, str]]:
    seeds: list[tuple[str, str]] = []
    seen: set[tuple[str, str]] = set()

    def add(city: str, st: str) -> None:
        key = (city, st)
        if key in seen:
            return
        if southeast_only and st not in SOUTHEAST_STATES:
            return
        seen.add(key)
        seeds.append(key)

    if southeast_only:
        for st in sorted(SOUTHEAST_STATES):
            for city in SOUTHEAST_EXTRA.get(st, []):
                add(city, st)
            for city in EXTRA_CITIES.get(st, []):
                add(city, st)
    else:
        for st, cities in EXTRA_CITIES.items():
            for city in cities:
                add(city, st)

    if csv_path and csv_path.is_file():
        with csv_path.open(newline="", encoding="utf-8") as f:
            reader = csv.DictReader(f)
            for row in reader:
                city = (row.get("City") or "").strip()
                state = (row.get("State") or "").strip()
                if not city or not state:
                    continue
                abbr = STATE_NAME_TO_ABBR.get(state)
                if abbr:
                    add(city, abbr)
    return seeds


def build_tuples(seeds: list[tuple[str, str]], existing: set[str], limit: int) -> list[tuple]:
    used: set[str] = set()
    out: list[tuple] = []
    for city, st in seeds:
        if st not in STATE_META:
            continue
        slug = make_slug(city, st, existing, used)
        if slug in existing or slug in used:
            continue
        state_page, hub_page = STATE_META[st]
        label = city if city.upper().endswith(f" {st}") else f"{city} {st}"
        out.append((slug, label, st, state_page, hub_page))
        used.add(slug)
        if len(out) >= limit:
            break
    return out


def write_data_file(path: Path, var_name: str, tuples: list[tuple]) -> None:
    lines = [
        f"# auto-generated city tuples — {var_name}",
        f"{var_name} = [",
    ]
    for tup in tuples:
        lines.append(f"    {tup!r},")
    lines.append("]")
    lines.append("")
    path.write_text("\n".join(lines), encoding="utf-8")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--wave", type=int, default=29)
    parser.add_argument("--limit", type=int, default=410)
    parser.add_argument("--csv", type=Path, default=Path("/tmp/us_cities.csv"))
    parser.add_argument(
        "--southeast",
        action="store_true",
        help="Only GA/TN/NC/SC/AL/FL/KY/MS/LA/VA/AR; prioritize SOUTHEAST_EXTRA towns",
    )
    args = parser.parse_args()

    root = Path(__file__).parent
    existing = collect_existing(root)
    seeds = iter_seed_cities(args.csv if args.csv.exists() else None, southeast_only=args.southeast)
    tuples = build_tuples(seeds, existing, args.limit)
    var = f"WAVE{args.wave}_CITIES"
    out = root / f"seo_bulk_wave{args.wave}_cities_data.py"
    write_data_file(out, var, tuples)
    print(f"Wrote {len(tuples)} cities to {out.name}")


if __name__ == "__main__":
    main()
