# auto-generated city tuples — WAVE44_CITIES
WAVE44_CITIES = [
    ('dunwoody-ga-2-mahjong.html', 'Dunwoody GA', 'GA', 'georgia-mahjong.html', 'georgia-mahjong-hub.html'),
    ('sandy-springs-ga-2-mahjong.html', 'Sandy Springs GA', 'GA', 'georgia-mahjong.html', 'georgia-mahjong-hub.html'),
    ('johns-creek-ga-8-mahjong.html', 'Johns Creek GA', 'GA', 'georgia-mahjong.html', 'georgia-mahjong-hub.html'),
    ('milton-ga-2-mahjong.html', 'Milton GA', 'GA', 'georgia-mahjong.html', 'georgia-mahjong-hub.html'),
    ('peachtree-corners-ga-2-mahjong.html', 'Peachtree Corners GA', 'GA', 'georgia-mahjong.html', 'georgia-mahjong-hub.html'),
    ('sugar-hill-ga-2-mahjong.html', 'Sugar Hill GA', 'GA', 'georgia-mahjong.html', 'georgia-mahjong-hub.html'),
    ('winder-ga-2-mahjong.html', 'Winder GA', 'GA', 'georgia-mahjong.html', 'georgia-mahjong-hub.html'),
    ('monroe-ga-2-mahjong.html', 'Monroe GA', 'GA', 'georgia-mahjong.html', 'georgia-mahjong-hub.html'),
    ('conyers-ga-2-mahjong.html', 'Conyers GA', 'GA', 'georgia-mahjong.html', 'georgia-mahjong-hub.html'),
    ('stockbridge-ga-2-mahjong.html', 'Stockbridge GA', 'GA', 'georgia-mahjong.html', 'georgia-mahjong-hub.html'),
    ('mcdonough-ga-2-mahjong.html', 'McDonough GA', 'GA', 'georgia-mahjong.html', 'georgia-mahjong-hub.html'),
    ('griffin-ga-2-mahjong.html', 'Griffin GA', 'GA', 'georgia-mahjong.html', 'georgia-mahjong-hub.html'),
    ('lagrange-ga-3-mahjong.html', 'LaGrange GA', 'GA', 'georgia-mahjong.html', 'georgia-mahjong-hub.html'),
    ('thomasville-ga-2-mahjong.html', 'Thomasville GA', 'GA', 'georgia-mahjong.html', 'georgia-mahjong-hub.html'),
    ('statesboro-ga-3-mahjong.html', 'Statesboro GA', 'GA', 'georgia-mahjong.html', 'georgia-mahjong-hub.html'),
    ('waycross-ga-2-mahjong.html', 'Waycross GA', 'GA', 'georgia-mahjong.html', 'georgia-mahjong-hub.html'),
    ('milledgeville-ga-2-mahjong.html', 'Milledgeville GA', 'GA', 'georgia-mahjong.html', 'georgia-mahjong-hub.html'),
    ('cartersville-ga-2-mahjong.html', 'Cartersville GA', 'GA', 'georgia-mahjong.html', 'georgia-mahjong-hub.html'),
    ('calhoun-ga-2-mahjong.html', 'Calhoun GA', 'GA', 'georgia-mahjong.html', 'georgia-mahjong-hub.html'),
    ('toccoa-ga-2-mahjong.html', 'Toccoa GA', 'GA', 'georgia-mahjong.html', 'georgia-mahjong-hub.html'),
    ('spring-hill-tn-2-mahjong.html', 'Spring Hill TN', 'TN', 'tennessee-mahjong.html', 'tennessee-mahjong-hub.html'),
    ('thompsons-station-tn-tn-mahjong.html', "Thompson's Station TN", 'TN', 'tennessee-mahjong.html', 'tennessee-mahjong-hub.html'),
    ('nolensville-tn-tn-mahjong.html', 'Nolensville TN', 'TN', 'tennessee-mahjong.html', 'tennessee-mahjong-hub.html'),
    ('brentwood-tn-2-mahjong.html', 'Brentwood TN', 'TN', 'tennessee-mahjong.html', 'tennessee-mahjong-hub.html'),
    ('springfield-tn-tn-mahjong.html', 'Springfield TN', 'TN', 'tennessee-mahjong.html', 'tennessee-mahjong-hub.html'),
    ('tullahoma-tn-2-mahjong.html', 'Tullahoma TN', 'TN', 'tennessee-mahjong.html', 'tennessee-mahjong-hub.html'),
    ('smyrna-tn-2-mahjong.html', 'Smyrna TN', 'TN', 'tennessee-mahjong.html', 'tennessee-mahjong-hub.html'),
    ('la-vergne-tn-2-mahjong.html', 'La Vergne TN', 'TN', 'tennessee-mahjong.html', 'tennessee-mahjong-hub.html'),
    ('lebanon-tn-tn-mahjong.html', 'Lebanon TN', 'TN', 'tennessee-mahjong.html', 'tennessee-mahjong-hub.html'),
    ('mount-juliet-tn-tn-mahjong.html', 'Mount Juliet TN', 'TN', 'tennessee-mahjong.html', 'tennessee-mahjong-hub.html'),
    ('hendersonville-tn-tn-mahjong.html', 'Hendersonville TN', 'TN', 'tennessee-mahjong.html', 'tennessee-mahjong-hub.html'),
    ('portland-tn-tn-mahjong.html', 'Portland TN', 'TN', 'tennessee-mahjong.html', 'tennessee-mahjong-hub.html'),
    ('dickson-tn-2-mahjong.html', 'Dickson TN', 'TN', 'tennessee-mahjong.html', 'tennessee-mahjong-hub.html'),
    ('mcminnville-tn-2-mahjong.html', 'McMinnville TN', 'TN', 'tennessee-mahjong.html', 'tennessee-mahjong-hub.html'),
    ('shelbyville-tn-2-mahjong.html', 'Shelbyville TN', 'TN', 'tennessee-mahjong.html', 'tennessee-mahjong-hub.html'),
    ('apex-nc-7-mahjong.html', 'Apex NC', 'NC', 'north-carolina-mahjong.html', 'north-carolina-mahjong-hub.html'),
    ('holly-springs-nc-2-mahjong.html', 'Holly Springs NC', 'NC', 'north-carolina-mahjong.html', 'north-carolina-mahjong-hub.html'),
    ('wake-forest-nc-2-mahjong.html', 'Wake Forest NC', 'NC', 'north-carolina-mahjong.html', 'north-carolina-mahjong-hub.html'),
    ('garner-nc-2-mahjong.html', 'Garner NC', 'NC', 'north-carolina-mahjong.html', 'north-carolina-mahjong-hub.html'),
    ('clayton-nc-2-mahjong.html', 'Clayton NC', 'NC', 'north-carolina-mahjong.html', 'north-carolina-mahjong-hub.html'),
    ('morrisville-nc-2-mahjong.html', 'Morrisville NC', 'NC', 'north-carolina-mahjong.html', 'north-carolina-mahjong-hub.html'),
    ('fuquay-varina-nc-2-mahjong.html', 'Fuquay-Varina NC', 'NC', 'north-carolina-mahjong.html', 'north-carolina-mahjong-hub.html'),
    ('lumberton-nc-3-mahjong.html', 'Lumberton NC', 'NC', 'north-carolina-mahjong.html', 'north-carolina-mahjong-hub.html'),
    ('sanford-nc-2-mahjong.html', 'Sanford NC', 'NC', 'north-carolina-mahjong.html', 'north-carolina-mahjong-hub.html'),
    ('albemarle-nc-2-mahjong.html', 'Albemarle NC', 'NC', 'north-carolina-mahjong.html', 'north-carolina-mahjong-hub.html'),
    ('kernersville-nc-2-mahjong.html', 'Kernersville NC', 'NC', 'north-carolina-mahjong.html', 'north-carolina-mahjong-hub.html'),
    ('thomasville-nc-2-mahjong.html', 'Thomasville NC', 'NC', 'north-carolina-mahjong.html', 'north-carolina-mahjong-hub.html'),
    ('lexington-nc-2-mahjong.html', 'Lexington NC', 'NC', 'north-carolina-mahjong.html', 'north-carolina-mahjong-hub.html'),
    ('mooresville-nc-3-mahjong.html', 'Mooresville NC', 'NC', 'north-carolina-mahjong.html', 'north-carolina-mahjong-hub.html'),
    ('huntersville-nc-9-mahjong.html', 'Huntersville NC', 'NC', 'north-carolina-mahjong.html', 'north-carolina-mahjong-hub.html'),
    ('cornelius-nc-3-mahjong.html', 'Cornelius NC', 'NC', 'north-carolina-mahjong.html', 'north-carolina-mahjong-hub.html'),
    ('davidson-nc-2-mahjong.html', 'Davidson NC', 'NC', 'north-carolina-mahjong.html', 'north-carolina-mahjong-hub.html'),
    ('stallings-nc-2-mahjong.html', 'Stallings NC', 'NC', 'north-carolina-mahjong.html', 'north-carolina-mahjong-hub.html'),
    ('weddington-nc-2-mahjong.html', 'Weddington NC', 'NC', 'north-carolina-mahjong.html', 'north-carolina-mahjong-hub.html'),
    ('matthews-nc-3-mahjong.html', 'Matthews NC', 'NC', 'north-carolina-mahjong.html', 'north-carolina-mahjong-hub.html'),
    ('fort-mill-sc-3-mahjong.html', 'Fort Mill SC', 'SC', 'south-carolina-mahjong.html', 'south-carolina-mahjong-hub.html'),
    ('tega-cay-sc-sc-mahjong.html', 'Tega Cay SC', 'SC', 'south-carolina-mahjong.html', 'south-carolina-mahjong-hub.html'),
    ('rock-hill-sc-2-mahjong.html', 'Rock Hill SC', 'SC', 'south-carolina-mahjong.html', 'south-carolina-mahjong-hub.html'),
    ('sumter-sc-2-mahjong.html', 'Sumter SC', 'SC', 'south-carolina-mahjong.html', 'south-carolina-mahjong-hub.html'),
    ('florence-sc-3-mahjong.html', 'Florence SC', 'SC', 'south-carolina-mahjong.html', 'south-carolina-mahjong-hub.html'),
    ('myrtle-beach-sc-2-mahjong.html', 'Myrtle Beach SC', 'SC', 'south-carolina-mahjong.html', 'south-carolina-mahjong-hub.html'),
    ('north-augusta-sc-sc-mahjong.html', 'North Augusta SC', 'SC', 'south-carolina-mahjong.html', 'south-carolina-mahjong-hub.html'),
    ('aiken-sc-2-mahjong.html', 'Aiken SC', 'SC', 'south-carolina-mahjong.html', 'south-carolina-mahjong-hub.html'),
    ('beaufort-sc-3-mahjong.html', 'Beaufort SC', 'SC', 'south-carolina-mahjong.html', 'south-carolina-mahjong-hub.html'),
    ('bluffton-sc-2-mahjong.html', 'Bluffton SC', 'SC', 'south-carolina-mahjong.html', 'south-carolina-mahjong-hub.html'),
    ('port-royal-sc-2-mahjong.html', 'Port Royal SC', 'SC', 'south-carolina-mahjong.html', 'south-carolina-mahjong-hub.html'),
    ('georgetown-sc-3-mahjong.html', 'Georgetown SC', 'SC', 'south-carolina-mahjong.html', 'south-carolina-mahjong-hub.html'),
    ('lancaster-sc-sc-mahjong.html', 'Lancaster SC', 'SC', 'south-carolina-mahjong.html', 'south-carolina-mahjong-hub.html'),
    ('camden-sc-sc-mahjong.html', 'Camden SC', 'SC', 'south-carolina-mahjong.html', 'south-carolina-mahjong-hub.html'),
    ('orangeburg-sc-3-mahjong.html', 'Orangeburg SC', 'SC', 'south-carolina-mahjong.html', 'south-carolina-mahjong-hub.html'),
    ('wellington-fl-6-mahjong.html', 'Wellington FL', 'FL', 'florida-mahjong.html', 'florida-mahjong-hub.html'),
    ('royal-palm-beach-fl-2-mahjong.html', 'Royal Palm Beach FL', 'FL', 'florida-mahjong.html', 'florida-mahjong-hub.html'),
    ('lake-worth-fl-2-mahjong.html', 'Lake Worth FL', 'FL', 'florida-mahjong.html', 'florida-mahjong-hub.html'),
    ('greenacres-fl-2-mahjong.html', 'Greenacres FL', 'FL', 'florida-mahjong.html', 'florida-mahjong-hub.html'),
    ('palm-springs-fl-2-mahjong.html', 'Palm Springs FL', 'FL', 'florida-mahjong.html', 'florida-mahjong-hub.html'),
    ('north-miami-fl-8-mahjong.html', 'North Miami FL', 'FL', 'florida-mahjong.html', 'florida-mahjong-hub.html'),
    ('coral-gables-fl-8-mahjong.html', 'Coral Gables FL', 'FL', 'florida-mahjong.html', 'florida-mahjong-hub.html'),
    ('hialeah-fl-2-mahjong.html', 'Hialeah FL', 'FL', 'florida-mahjong.html', 'florida-mahjong-hub.html'),
    ('doral-fl-8-mahjong.html', 'Doral FL', 'FL', 'florida-mahjong.html', 'florida-mahjong-hub.html'),
    ('cutler-bay-fl-2-mahjong.html', 'Cutler Bay FL', 'FL', 'florida-mahjong.html', 'florida-mahjong-hub.html'),
    ('homestead-fl-2-mahjong.html', 'Homestead FL', 'FL', 'florida-mahjong.html', 'florida-mahjong-hub.html'),
    ('winter-garden-fl-2-mahjong.html', 'Winter Garden FL', 'FL', 'florida-mahjong.html', 'florida-mahjong-hub.html'),
    ('ocoee-fl-2-mahjong.html', 'Ocoee FL', 'FL', 'florida-mahjong.html', 'florida-mahjong-hub.html'),
    ('altamonte-springs-fl-2-mahjong.html', 'Altamonte Springs FL', 'FL', 'florida-mahjong.html', 'florida-mahjong-hub.html'),
    ('kissimmee-fl-9-mahjong.html', 'Kissimmee FL', 'FL', 'florida-mahjong.html', 'florida-mahjong-hub.html'),
    ('st-cloud-fl-2-mahjong.html', 'St Cloud FL', 'FL', 'florida-mahjong.html', 'florida-mahjong-hub.html'),
    ('sugar-land-tx-8-mahjong.html', 'Sugar Land TX', 'TX', 'texas-mahjong.html', 'texas-mahjong-hub.html'),
    ('missouri-city-tx-7-mahjong.html', 'Missouri City TX', 'TX', 'texas-mahjong.html', 'texas-mahjong-hub.html'),
    ('pearland-tx-8-mahjong.html', 'Pearland TX', 'TX', 'texas-mahjong.html', 'texas-mahjong-hub.html'),
    ('league-city-tx-2-mahjong.html', 'League City TX', 'TX', 'texas-mahjong.html', 'texas-mahjong-hub.html'),
    ('bay-city-tx-tx-mahjong.html', 'Bay City TX', 'TX', 'texas-mahjong.html', 'texas-mahjong-hub.html'),
    ('port-arthur-tx-5-mahjong.html', 'Port Arthur TX', 'TX', 'texas-mahjong.html', 'texas-mahjong-hub.html'),
    ('nacogdoches-tx-2-mahjong.html', 'Nacogdoches TX', 'TX', 'texas-mahjong.html', 'texas-mahjong-hub.html'),
    ('lufkin-tx-2-mahjong.html', 'Lufkin TX', 'TX', 'texas-mahjong.html', 'texas-mahjong-hub.html'),
    ('paris-tx-2-mahjong.html', 'Paris TX', 'TX', 'texas-mahjong.html', 'texas-mahjong-hub.html'),
    ('greenville-tx-2-mahjong.html', 'Greenville TX', 'TX', 'texas-mahjong.html', 'texas-mahjong-hub.html'),
    ('wichita-falls-tx-7-mahjong.html', 'Wichita Falls TX', 'TX', 'texas-mahjong.html', 'texas-mahjong-hub.html'),
    ('san-angelo-tx-7-mahjong.html', 'San Angelo TX', 'TX', 'texas-mahjong.html', 'texas-mahjong-hub.html'),
    ('del-rio-tx-tx-mahjong.html', 'Del Rio TX', 'TX', 'texas-mahjong.html', 'texas-mahjong-hub.html'),
    ('eagle-pass-tx-tx-mahjong.html', 'Eagle Pass TX', 'TX', 'texas-mahjong.html', 'texas-mahjong-hub.html'),
    ('uvalde-tx-tx-mahjong.html', 'Uvalde TX', 'TX', 'texas-mahjong.html', 'texas-mahjong-hub.html'),
    ('kerrville-tx-tx-mahjong.html', 'Kerrville TX', 'TX', 'texas-mahjong.html', 'texas-mahjong-hub.html'),
    ('seguin-tx-tx-mahjong.html', 'Seguin TX', 'TX', 'texas-mahjong.html', 'texas-mahjong-hub.html'),
    ('kyle-tx-tx-mahjong.html', 'Kyle TX', 'TX', 'texas-mahjong.html', 'texas-mahjong-hub.html'),
    ('buda-tx-tx-mahjong.html', 'Buda TX', 'TX', 'texas-mahjong.html', 'texas-mahjong-hub.html'),
    ('pflugerville-tx-tx-mahjong.html', 'Pflugerville TX', 'TX', 'texas-mahjong.html', 'texas-mahjong-hub.html'),
    ('irvine-ca-2-mahjong.html', 'Irvine CA', 'CA', 'california-mahjong.html', 'california-mahjong-hub.html'),
    ('newport-beach-ca-5-mahjong.html', 'Newport Beach CA', 'CA', 'california-mahjong.html', 'california-mahjong-hub.html'),
    ('laguna-beach-ca-ca-mahjong.html', 'Laguna Beach CA', 'CA', 'california-mahjong.html', 'california-mahjong-hub.html'),
    ('dana-point-ca-ca-mahjong.html', 'Dana Point CA', 'CA', 'california-mahjong.html', 'california-mahjong-hub.html'),
    ('san-clemente-ca-7-mahjong.html', 'San Clemente CA', 'CA', 'california-mahjong.html', 'california-mahjong-hub.html'),
    ('mission-viejo-ca-ca-mahjong.html', 'Mission Viejo CA', 'CA', 'california-mahjong.html', 'california-mahjong-hub.html'),
    ('lake-forest-ca-ca-mahjong.html', 'Lake Forest CA', 'CA', 'california-mahjong.html', 'california-mahjong-hub.html'),
    ('huntington-beach-ca-ca-mahjong.html', 'Huntington Beach CA', 'CA', 'california-mahjong.html', 'california-mahjong-hub.html'),
    ('fullerton-ca-ca-mahjong.html', 'Fullerton CA', 'CA', 'california-mahjong.html', 'california-mahjong-hub.html'),
    ('anaheim-ca-ca-mahjong.html', 'Anaheim CA', 'CA', 'california-mahjong.html', 'california-mahjong-hub.html'),
    ('garden-grove-ca-ca-mahjong.html', 'Garden Grove CA', 'CA', 'california-mahjong.html', 'california-mahjong-hub.html'),
    ('costa-mesa-ca-5-mahjong.html', 'Costa Mesa CA', 'CA', 'california-mahjong.html', 'california-mahjong-hub.html'),
    ('tustin-ca-7-mahjong.html', 'Tustin CA', 'CA', 'california-mahjong.html', 'california-mahjong-hub.html'),
    ('yorba-linda-ca-7-mahjong.html', 'Yorba Linda CA', 'CA', 'california-mahjong.html', 'california-mahjong-hub.html'),
    ('brea-ca-7-mahjong.html', 'Brea CA', 'CA', 'california-mahjong.html', 'california-mahjong-hub.html'),
    ('la-habra-ca-7-mahjong.html', 'La Habra CA', 'CA', 'california-mahjong.html', 'california-mahjong-hub.html'),
    ('whittier-ca-ca-mahjong.html', 'Whittier CA', 'CA', 'california-mahjong.html', 'california-mahjong-hub.html'),
    ('torrance-ca-ca-mahjong.html', 'Torrance CA', 'CA', 'california-mahjong.html', 'california-mahjong-hub.html'),
    ('manhattan-beach-ca-ca-mahjong.html', 'Manhattan Beach CA', 'CA', 'california-mahjong.html', 'california-mahjong-hub.html'),
    ('redondo-beach-ca-ca-mahjong.html', 'Redondo Beach CA', 'CA', 'california-mahjong.html', 'california-mahjong-hub.html'),
    ('scarsdale-ny-ny-mahjong.html', 'Scarsdale NY', 'NY', 'new-york-mahjong.html', 'new-york-mahjong-hub.html'),
    ('rye-ny-ny-mahjong.html', 'Rye NY', 'NY', 'new-york-mahjong.html', 'new-york-mahjong-hub.html'),
    ('mamaroneck-ny-ny-mahjong.html', 'Mamaroneck NY', 'NY', 'new-york-mahjong.html', 'new-york-mahjong-hub.html'),
    ('larchmont-ny-ny-mahjong.html', 'Larchmont NY', 'NY', 'new-york-mahjong.html', 'new-york-mahjong-hub.html'),
    ('harrison-ny-ny-mahjong.html', 'Harrison NY', 'NY', 'new-york-mahjong.html', 'new-york-mahjong-hub.html'),
    ('mount-kisco-ny-ny-mahjong.html', 'Mount Kisco NY', 'NY', 'new-york-mahjong.html', 'new-york-mahjong-hub.html'),
    ('peekskill-ny-ny-mahjong.html', 'Peekskill NY', 'NY', 'new-york-mahjong.html', 'new-york-mahjong-hub.html'),
    ('beacon-ny-ny-mahjong.html', 'Beacon NY', 'NY', 'new-york-mahjong.html', 'new-york-mahjong-hub.html'),
    ('middletown-ny-2-mahjong.html', 'Middletown NY', 'NY', 'new-york-mahjong.html', 'new-york-mahjong-hub.html'),
    ('kingston-ny-2-mahjong.html', 'Kingston NY', 'NY', 'new-york-mahjong.html', 'new-york-mahjong-hub.html'),
    ('saratoga-springs-ny-2-mahjong.html', 'Saratoga Springs NY', 'NY', 'new-york-mahjong.html', 'new-york-mahjong-hub.html'),
    ('glens-falls-ny-2-mahjong.html', 'Glens Falls NY', 'NY', 'new-york-mahjong.html', 'new-york-mahjong-hub.html'),
    ('plattsburgh-ny-2-mahjong.html', 'Plattsburgh NY', 'NY', 'new-york-mahjong.html', 'new-york-mahjong-hub.html'),
    ('olean-ny-2-mahjong.html', 'Olean NY', 'NY', 'new-york-mahjong.html', 'new-york-mahjong-hub.html'),
    ('jamestown-ny-2-mahjong.html', 'Jamestown NY', 'NY', 'new-york-mahjong.html', 'new-york-mahjong-hub.html'),
    ('media-pa-2-mahjong.html', 'Media PA', 'PA', 'pennsylvania-mahjong.html', 'pennsylvania-mahjong-hub.html'),
    ('wayne-pa-pa-mahjong.html', 'Wayne PA', 'PA', 'pennsylvania-mahjong.html', 'pennsylvania-mahjong-hub.html'),
    ('ardmore-pa-pa-mahjong.html', 'Ardmore PA', 'PA', 'pennsylvania-mahjong.html', 'pennsylvania-mahjong-hub.html'),
    ('bryn-mawr-pa-pa-mahjong.html', 'Bryn Mawr PA', 'PA', 'pennsylvania-mahjong.html', 'pennsylvania-mahjong-hub.html'),
    ('conshohocken-pa-pa-mahjong.html', 'Conshohocken PA', 'PA', 'pennsylvania-mahjong.html', 'pennsylvania-mahjong-hub.html'),
    ('lansdale-pa-pa-mahjong.html', 'Lansdale PA', 'PA', 'pennsylvania-mahjong.html', 'pennsylvania-mahjong-hub.html'),
    ('doylestown-pa-pa-mahjong.html', 'Doylestown PA', 'PA', 'pennsylvania-mahjong.html', 'pennsylvania-mahjong-hub.html'),
    ('new-hope-pa-pa-mahjong.html', 'New Hope PA', 'PA', 'pennsylvania-mahjong.html', 'pennsylvania-mahjong-hub.html'),
    ('lititz-pa-pa-mahjong.html', 'Lititz PA', 'PA', 'pennsylvania-mahjong.html', 'pennsylvania-mahjong-hub.html'),
    ('hanover-pa-pa-mahjong.html', 'Hanover PA', 'PA', 'pennsylvania-mahjong.html', 'pennsylvania-mahjong-hub.html'),
    ('carlisle-pa-2-mahjong.html', 'Carlisle PA', 'PA', 'pennsylvania-mahjong.html', 'pennsylvania-mahjong-hub.html'),
    ('chambersburg-pa-2-mahjong.html', 'Chambersburg PA', 'PA', 'pennsylvania-mahjong.html', 'pennsylvania-mahjong-hub.html'),
    ('indiana-pa-2-mahjong.html', 'Indiana PA', 'PA', 'pennsylvania-mahjong.html', 'pennsylvania-mahjong-hub.html'),
    ('butler-pa-2-mahjong.html', 'Butler PA', 'PA', 'pennsylvania-mahjong.html', 'pennsylvania-mahjong-hub.html'),
    ('greensburg-pa-2-mahjong.html', 'Greensburg PA', 'PA', 'pennsylvania-mahjong.html', 'pennsylvania-mahjong-hub.html'),
    ('dublin-oh-7-mahjong.html', 'Dublin OH', 'OH', 'ohio-mahjong.html', 'ohio-mahjong-hub.html'),
    ('westerville-oh-oh-mahjong.html', 'Westerville OH', 'OH', 'ohio-mahjong.html', 'ohio-mahjong-hub.html'),
    ('gahanna-oh-oh-mahjong.html', 'Gahanna OH', 'OH', 'ohio-mahjong.html', 'ohio-mahjong-hub.html'),
    ('reynoldsburg-oh-oh-mahjong.html', 'Reynoldsburg OH', 'OH', 'ohio-mahjong.html', 'ohio-mahjong-hub.html'),
    ('grove-city-oh-7-mahjong.html', 'Grove City OH', 'OH', 'ohio-mahjong.html', 'ohio-mahjong-hub.html'),
    ('hilliard-oh-oh-mahjong.html', 'Hilliard OH', 'OH', 'ohio-mahjong.html', 'ohio-mahjong-hub.html'),
    ('upper-arlington-oh-oh-mahjong.html', 'Upper Arlington OH', 'OH', 'ohio-mahjong.html', 'ohio-mahjong-hub.html'),
    ('worthington-oh-oh-mahjong.html', 'Worthington OH', 'OH', 'ohio-mahjong.html', 'ohio-mahjong-hub.html'),
    ('mason-oh-oh-mahjong.html', 'Mason OH', 'OH', 'ohio-mahjong.html', 'ohio-mahjong-hub.html'),
    ('fairfield-oh-7-mahjong.html', 'Fairfield OH', 'OH', 'ohio-mahjong.html', 'ohio-mahjong-hub.html'),
    ('hamilton-oh-oh-mahjong.html', 'Hamilton OH', 'OH', 'ohio-mahjong.html', 'ohio-mahjong-hub.html'),
    ('middletown-oh-oh-mahjong.html', 'Middletown OH', 'OH', 'ohio-mahjong.html', 'ohio-mahjong-hub.html'),
    ('springfield-oh-oh-mahjong.html', 'Springfield OH', 'OH', 'ohio-mahjong.html', 'ohio-mahjong-hub.html'),
    ('lima-oh-8-mahjong.html', 'Lima OH', 'OH', 'ohio-mahjong.html', 'ohio-mahjong-hub.html'),
    ('findlay-oh-8-mahjong.html', 'Findlay OH', 'OH', 'ohio-mahjong.html', 'ohio-mahjong-hub.html'),
    ('troy-mi-6-mahjong.html', 'Troy MI', 'MI', 'michigan-mahjong.html', 'michigan-mahjong-hub.html'),
    ('novi-mi-2-mahjong.html', 'Novi MI', 'MI', 'michigan-mahjong.html', 'michigan-mahjong-hub.html'),
    ('farmington-hills-mi-mi-mahjong.html', 'Farmington Hills MI', 'MI', 'michigan-mahjong.html', 'michigan-mahjong-hub.html'),
    ('southfield-mi-7-mahjong.html', 'Southfield MI', 'MI', 'michigan-mahjong.html', 'michigan-mahjong-hub.html'),
    ('royal-oak-mi-5-mahjong.html', 'Royal Oak MI', 'MI', 'michigan-mahjong.html', 'michigan-mahjong-hub.html'),
    ('birmingham-mi-mi-mahjong.html', 'Birmingham MI', 'MI', 'michigan-mahjong.html', 'michigan-mahjong-hub.html'),
    ('rochester-hills-mi-2-mahjong.html', 'Rochester Hills MI', 'MI', 'michigan-mahjong.html', 'michigan-mahjong-hub.html'),
    ('shelby-township-mi-mi-mahjong.html', 'Shelby Township MI', 'MI', 'michigan-mahjong.html', 'michigan-mahjong-hub.html'),
    ('macomb-mi-mi-mahjong.html', 'Macomb MI', 'MI', 'michigan-mahjong.html', 'michigan-mahjong-hub.html'),
    ('clinton-township-mi-mi-mahjong.html', 'Clinton Township MI', 'MI', 'michigan-mahjong.html', 'michigan-mahjong-hub.html'),
    ('bay-city-mi-2-mahjong.html', 'Bay City MI', 'MI', 'michigan-mahjong.html', 'michigan-mahjong-hub.html'),
    ('saginaw-mi-8-mahjong.html', 'Saginaw MI', 'MI', 'michigan-mahjong.html', 'michigan-mahjong-hub.html'),
    ('midland-mi-2-mahjong.html', 'Midland MI', 'MI', 'michigan-mahjong.html', 'michigan-mahjong-hub.html'),
    ('muskegon-mi-8-mahjong.html', 'Muskegon MI', 'MI', 'michigan-mahjong.html', 'michigan-mahjong-hub.html'),
    ('holland-mi-2-mahjong.html', 'Holland MI', 'MI', 'michigan-mahjong.html', 'michigan-mahjong-hub.html'),
    ('naperville-il-8-mahjong.html', 'Naperville IL', 'IL', 'illinois-mahjong.html', 'illinois-mahjong-hub.html'),
    ('aurora-il-8-mahjong.html', 'Aurora IL', 'IL', 'illinois-mahjong.html', 'illinois-mahjong-hub.html'),
    ('joliet-il-2-mahjong.html', 'Joliet IL', 'IL', 'illinois-mahjong.html', 'illinois-mahjong-hub.html'),
    ('elgin-il-2-mahjong.html', 'Elgin IL', 'IL', 'illinois-mahjong.html', 'illinois-mahjong-hub.html'),
    ('waukegan-il-2-mahjong.html', 'Waukegan IL', 'IL', 'illinois-mahjong.html', 'illinois-mahjong-hub.html'),
    ('cicero-il-2-mahjong.html', 'Cicero IL', 'IL', 'illinois-mahjong.html', 'illinois-mahjong-hub.html'),
    ('bloomington-il-8-mahjong.html', 'Bloomington IL', 'IL', 'illinois-mahjong.html', 'illinois-mahjong-hub.html'),
    ('champaign-il-2-mahjong.html', 'Champaign IL', 'IL', 'illinois-mahjong.html', 'illinois-mahjong-hub.html'),
    ('decatur-il-8-mahjong.html', 'Decatur IL', 'IL', 'illinois-mahjong.html', 'illinois-mahjong-hub.html'),
    ('peoria-il-8-mahjong.html', 'Peoria IL', 'IL', 'illinois-mahjong.html', 'illinois-mahjong-hub.html'),
    ('rockford-il-2-mahjong.html', 'Rockford IL', 'IL', 'illinois-mahjong.html', 'illinois-mahjong-hub.html'),
    ('springfield-il-8-mahjong.html', 'Springfield IL', 'IL', 'illinois-mahjong.html', 'illinois-mahjong-hub.html'),
    ('quincy-il-8-mahjong.html', 'Quincy IL', 'IL', 'illinois-mahjong.html', 'illinois-mahjong-hub.html'),
    ('carbondale-il-2-mahjong.html', 'Carbondale IL', 'IL', 'illinois-mahjong.html', 'illinois-mahjong-hub.html'),
    ('normal-il-8-mahjong.html', 'Normal IL', 'IL', 'illinois-mahjong.html', 'illinois-mahjong-hub.html'),
    ('castle-rock-co-co-mahjong.html', 'Castle Rock CO', 'CO', 'colorado-mahjong.html', 'colorado-mahjong-hub.html'),
    ('parker-co-7-mahjong.html', 'Parker CO', 'CO', 'colorado-mahjong.html', 'colorado-mahjong-hub.html'),
    ('lone-tree-co-co-mahjong.html', 'Lone Tree CO', 'CO', 'colorado-mahjong.html', 'colorado-mahjong-hub.html'),
    ('highlands-ranch-co-co-mahjong.html', 'Highlands Ranch CO', 'CO', 'colorado-mahjong.html', 'colorado-mahjong-hub.html'),
    ('centennial-co-co-mahjong.html', 'Centennial CO', 'CO', 'colorado-mahjong.html', 'colorado-mahjong-hub.html'),
    ('aurora-co-co-mahjong.html', 'Aurora CO', 'CO', 'colorado-mahjong.html', 'colorado-mahjong-hub.html'),
    ('thornton-co-7-mahjong.html', 'Thornton CO', 'CO', 'colorado-mahjong.html', 'colorado-mahjong-hub.html'),
    ('northglenn-co-co-mahjong.html', 'Northglenn CO', 'CO', 'colorado-mahjong.html', 'colorado-mahjong-hub.html'),
    ('brighton-co-co-mahjong.html', 'Brighton CO', 'CO', 'colorado-mahjong.html', 'colorado-mahjong-hub.html'),
    ('greeley-co-2-mahjong.html', 'Greeley CO', 'CO', 'colorado-mahjong.html', 'colorado-mahjong-hub.html'),
    ('fort-morgan-co-co-mahjong.html', 'Fort Morgan CO', 'CO', 'colorado-mahjong.html', 'colorado-mahjong-hub.html'),
    ('sterling-co-co-mahjong.html', 'Sterling CO', 'CO', 'colorado-mahjong.html', 'colorado-mahjong-hub.html'),
    ('trinidad-co-co-mahjong.html', 'Trinidad CO', 'CO', 'colorado-mahjong.html', 'colorado-mahjong-hub.html'),
    ('montrose-co-co-mahjong.html', 'Montrose CO', 'CO', 'colorado-mahjong.html', 'colorado-mahjong-hub.html'),
    ('durango-co-co-mahjong.html', 'Durango CO', 'CO', 'colorado-mahjong.html', 'colorado-mahjong-hub.html'),
    ('scottsdale-az-7-mahjong.html', 'Scottsdale AZ', 'AZ', 'arizona-mahjong.html', 'arizona-mahjong-hub.html'),
    ('paradise-valley-az-az-mahjong.html', 'Paradise Valley AZ', 'AZ', 'arizona-mahjong.html', 'arizona-mahjong-hub.html'),
    ('tempe-az-6-mahjong.html', 'Tempe AZ', 'AZ', 'arizona-mahjong.html', 'arizona-mahjong-hub.html'),
    ('mesa-az-8-mahjong.html', 'Mesa AZ', 'AZ', 'arizona-mahjong.html', 'arizona-mahjong-hub.html'),
    ('glendale-az-az-mahjong.html', 'Glendale AZ', 'AZ', 'arizona-mahjong.html', 'arizona-mahjong-hub.html'),
    ('peoria-az-5-mahjong.html', 'Peoria AZ', 'AZ', 'arizona-mahjong.html', 'arizona-mahjong-hub.html'),
    ('surprise-az-az-mahjong.html', 'Surprise AZ', 'AZ', 'arizona-mahjong.html', 'arizona-mahjong-hub.html'),
    ('goodyear-az-7-mahjong.html', 'Goodyear AZ', 'AZ', 'arizona-mahjong.html', 'arizona-mahjong-hub.html'),
    ('avondale-az-5-mahjong.html', 'Avondale AZ', 'AZ', 'arizona-mahjong.html', 'arizona-mahjong-hub.html'),
    ('flagstaff-az-8-mahjong.html', 'Flagstaff AZ', 'AZ', 'arizona-mahjong.html', 'arizona-mahjong-hub.html'),
    ('sedona-az-2-mahjong.html', 'Sedona AZ', 'AZ', 'arizona-mahjong.html', 'arizona-mahjong-hub.html'),
    ('kingman-az-az-mahjong.html', 'Kingman AZ', 'AZ', 'arizona-mahjong.html', 'arizona-mahjong-hub.html'),
    ('yuma-az-2-mahjong.html', 'Yuma AZ', 'AZ', 'arizona-mahjong.html', 'arizona-mahjong-hub.html'),
    ('nogales-az-az-mahjong.html', 'Nogales AZ', 'AZ', 'arizona-mahjong.html', 'arizona-mahjong-hub.html'),
    ('sierra-vista-az-8-mahjong.html', 'Sierra Vista AZ', 'AZ', 'arizona-mahjong.html', 'arizona-mahjong-hub.html'),
    ('redmond-wa-wa-mahjong.html', 'Redmond WA', 'WA', 'washington-state-mahjong.html', 'washington-mahjong-hub.html'),
    ('kirkland-wa-wa-mahjong.html', 'Kirkland WA', 'WA', 'washington-state-mahjong.html', 'washington-mahjong-hub.html'),
    ('issaquah-wa-wa-mahjong.html', 'Issaquah WA', 'WA', 'washington-state-mahjong.html', 'washington-mahjong-hub.html'),
    ('sammamish-wa-wa-mahjong.html', 'Sammamish WA', 'WA', 'washington-state-mahjong.html', 'washington-mahjong-hub.html'),
    ('renton-wa-wa-mahjong.html', 'Renton WA', 'WA', 'washington-state-mahjong.html', 'washington-mahjong-hub.html'),
    ('kent-wa-7-mahjong.html', 'Kent WA', 'WA', 'washington-state-mahjong.html', 'washington-mahjong-hub.html'),
    ('federal-way-wa-wa-mahjong.html', 'Federal Way WA', 'WA', 'washington-state-mahjong.html', 'washington-mahjong-hub.html'),
    ('auburn-wa-wa-mahjong.html', 'Auburn WA', 'WA', 'washington-state-mahjong.html', 'washington-mahjong-hub.html'),
    ('puyallup-wa-7-mahjong.html', 'Puyallup WA', 'WA', 'washington-state-mahjong.html', 'washington-mahjong-hub.html'),
    ('lacey-wa-6-mahjong.html', 'Lacey WA', 'WA', 'washington-state-mahjong.html', 'washington-mahjong-hub.html'),
    ('olympia-wa-2-mahjong.html', 'Olympia WA', 'WA', 'washington-state-mahjong.html', 'washington-mahjong-hub.html'),
    ('bremerton-wa-8-mahjong.html', 'Bremerton WA', 'WA', 'washington-state-mahjong.html', 'washington-mahjong-hub.html'),
    ('wenatchee-wa-2-mahjong.html', 'Wenatchee WA', 'WA', 'washington-state-mahjong.html', 'washington-mahjong-hub.html'),
    ('yakima-wa-6-mahjong.html', 'Yakima WA', 'WA', 'washington-state-mahjong.html', 'washington-mahjong-hub.html'),
    ('walla-walla-wa-2-mahjong.html', 'Walla Walla WA', 'WA', 'washington-state-mahjong.html', 'washington-mahjong-hub.html'),
    ('lake-oswego-or-2-mahjong.html', 'Lake Oswego OR', 'OR', 'oregon-mahjong.html', 'oregon-mahjong-hub.html'),
    ('tigard-or-8-mahjong.html', 'Tigard OR', 'OR', 'oregon-mahjong.html', 'oregon-mahjong-hub.html'),
    ('beaverton-or-6-mahjong.html', 'Beaverton OR', 'OR', 'oregon-mahjong.html', 'oregon-mahjong-hub.html'),
    ('hillsboro-or-2-mahjong.html', 'Hillsboro OR', 'OR', 'oregon-mahjong.html', 'oregon-mahjong-hub.html'),
    ('gresham-or-or-mahjong.html', 'Gresham OR', 'OR', 'oregon-mahjong.html', 'oregon-mahjong-hub.html'),
    ('oregon-city-or-2-mahjong.html', 'Oregon City OR', 'OR', 'oregon-mahjong.html', 'oregon-mahjong-hub.html'),
    ('grants-pass-or-2-mahjong.html', 'Grants Pass OR', 'OR', 'oregon-mahjong.html', 'oregon-mahjong-hub.html'),
    ('medford-or-2-mahjong.html', 'Medford OR', 'OR', 'oregon-mahjong.html', 'oregon-mahjong-hub.html'),
    ('klamath-falls-or-2-mahjong.html', 'Klamath Falls OR', 'OR', 'oregon-mahjong.html', 'oregon-mahjong-hub.html'),
    ('bend-or-2-mahjong.html', 'Bend OR', 'OR', 'oregon-mahjong.html', 'oregon-mahjong-hub.html'),
    ('redmond-or-or-mahjong.html', 'Redmond OR', 'OR', 'oregon-mahjong.html', 'oregon-mahjong-hub.html'),
    ('corvallis-or-2-mahjong.html', 'Corvallis OR', 'OR', 'oregon-mahjong.html', 'oregon-mahjong-hub.html'),
    ('albany-or-2-mahjong.html', 'Albany OR', 'OR', 'oregon-mahjong.html', 'oregon-mahjong-hub.html'),
    ('mcminnville-or-2-mahjong.html', 'McMinnville OR', 'OR', 'oregon-mahjong.html', 'oregon-mahjong-hub.html'),
    ('newberg-or-or-mahjong.html', 'Newberg OR', 'OR', 'oregon-mahjong.html', 'oregon-mahjong-hub.html'),
    ('reston-va-2-mahjong.html', 'Reston VA', 'VA', 'virginia-mahjong.html', 'virginia-mahjong-hub.html'),
    ('herndon-va-va-mahjong.html', 'Herndon VA', 'VA', 'virginia-mahjong.html', 'virginia-mahjong-hub.html'),
    ('vienna-va-va-mahjong.html', 'Vienna VA', 'VA', 'virginia-mahjong.html', 'virginia-mahjong-hub.html'),
    ('mclean-va-2-mahjong.html', 'McLean VA', 'VA', 'virginia-mahjong.html', 'virginia-mahjong-hub.html'),
    ('great-falls-va-va-mahjong.html', 'Great Falls VA', 'VA', 'virginia-mahjong.html', 'virginia-mahjong-hub.html'),
    ('falls-church-va-va-mahjong.html', 'Falls Church VA', 'VA', 'virginia-mahjong.html', 'virginia-mahjong-hub.html'),
    ('manassas-va-2-mahjong.html', 'Manassas VA', 'VA', 'virginia-mahjong.html', 'virginia-mahjong-hub.html'),
    ('woodbridge-va-2-mahjong.html', 'Woodbridge VA', 'VA', 'virginia-mahjong.html', 'virginia-mahjong-hub.html'),
    ('fredericksburg-va-2-mahjong.html', 'Fredericksburg VA', 'VA', 'virginia-mahjong.html', 'virginia-mahjong-hub.html'),
    ('williamsburg-va-va-mahjong.html', 'Williamsburg VA', 'VA', 'virginia-mahjong.html', 'virginia-mahjong-hub.html'),
    ('yorktown-va-va-mahjong.html', 'Yorktown VA', 'VA', 'virginia-mahjong.html', 'virginia-mahjong-hub.html'),
    ('poquoson-va-va-mahjong.html', 'Poquoson VA', 'VA', 'virginia-mahjong.html', 'virginia-mahjong-hub.html'),
    ('smithfield-va-va-mahjong.html', 'Smithfield VA', 'VA', 'virginia-mahjong.html', 'virginia-mahjong-hub.html'),
    ('suffolk-va-2-mahjong.html', 'Suffolk VA', 'VA', 'virginia-mahjong.html', 'virginia-mahjong-hub.html'),
    ('bethesda-md-2-mahjong.html', 'Bethesda MD', 'MD', 'maryland-mahjong.html', 'maryland-mahjong-hub.html'),
    ('chevy-chase-md-md-mahjong.html', 'Chevy Chase MD', 'MD', 'maryland-mahjong.html', 'maryland-mahjong-hub.html'),
    ('rockville-md-2-mahjong.html', 'Rockville MD', 'MD', 'maryland-mahjong.html', 'maryland-mahjong-hub.html'),
    ('gaithersburg-md-7-mahjong.html', 'Gaithersburg MD', 'MD', 'maryland-mahjong.html', 'maryland-mahjong-hub.html'),
    ('germantown-md-2-mahjong.html', 'Germantown MD', 'MD', 'maryland-mahjong.html', 'maryland-mahjong-hub.html'),
    ('frederick-md-8-mahjong.html', 'Frederick MD', 'MD', 'maryland-mahjong.html', 'maryland-mahjong-hub.html'),
    ('hagerstown-md-8-mahjong.html', 'Hagerstown MD', 'MD', 'maryland-mahjong.html', 'maryland-mahjong-hub.html'),
    ('annapolis-md-7-mahjong.html', 'Annapolis MD', 'MD', 'maryland-mahjong.html', 'maryland-mahjong-hub.html'),
    ('easton-md-2-mahjong.html', 'Easton MD', 'MD', 'maryland-mahjong.html', 'maryland-mahjong-hub.html'),
    ('salisbury-md-2-mahjong.html', 'Salisbury MD', 'MD', 'maryland-mahjong.html', 'maryland-mahjong-hub.html'),
    ('ocean-city-md-2-mahjong.html', 'Ocean City MD', 'MD', 'maryland-mahjong.html', 'maryland-mahjong-hub.html'),
    ('cambridge-md-2-mahjong.html', 'Cambridge MD', 'MD', 'maryland-mahjong.html', 'maryland-mahjong-hub.html'),
    ('la-plata-md-md-mahjong.html', 'La Plata MD', 'MD', 'maryland-mahjong.html', 'maryland-mahjong-hub.html'),
    ('bowie-md-7-mahjong.html', 'Bowie MD', 'MD', 'maryland-mahjong.html', 'maryland-mahjong-hub.html'),
    ('college-park-md-2-mahjong.html', 'College Park MD', 'MD', 'maryland-mahjong.html', 'maryland-mahjong-hub.html'),
    ('princeton-nj-2-mahjong.html', 'Princeton NJ', 'NJ', 'new-jersey-mahjong.html', 'new-jersey-mahjong-hub.html'),
    ('lawrenceville-nj-nj-mahjong.html', 'Lawrenceville NJ', 'NJ', 'new-jersey-mahjong.html', 'new-jersey-mahjong-hub.html'),
    ('freehold-nj-nj-mahjong.html', 'Freehold NJ', 'NJ', 'new-jersey-mahjong.html', 'new-jersey-mahjong-hub.html'),
    ('red-bank-nj-2-mahjong.html', 'Red Bank NJ', 'NJ', 'new-jersey-mahjong.html', 'new-jersey-mahjong-hub.html'),
    ('long-branch-nj-nj-mahjong.html', 'Long Branch NJ', 'NJ', 'new-jersey-mahjong.html', 'new-jersey-mahjong-hub.html'),
    ('asbury-park-nj-nj-mahjong.html', 'Asbury Park NJ', 'NJ', 'new-jersey-mahjong.html', 'new-jersey-mahjong-hub.html'),
    ('ocean-city-nj-nj-mahjong.html', 'Ocean City NJ', 'NJ', 'new-jersey-mahjong.html', 'new-jersey-mahjong-hub.html'),
    ('vineland-nj-nj-mahjong.html', 'Vineland NJ', 'NJ', 'new-jersey-mahjong.html', 'new-jersey-mahjong-hub.html'),
    ('millville-nj-nj-mahjong.html', 'Millville NJ', 'NJ', 'new-jersey-mahjong.html', 'new-jersey-mahjong-hub.html'),
    ('bridgeton-nj-nj-mahjong.html', 'Bridgeton NJ', 'NJ', 'new-jersey-mahjong.html', 'new-jersey-mahjong-hub.html'),
    ('cape-may-nj-nj-mahjong.html', 'Cape May NJ', 'NJ', 'new-jersey-mahjong.html', 'new-jersey-mahjong-hub.html'),
    ('wildwood-nj-nj-mahjong.html', 'Wildwood NJ', 'NJ', 'new-jersey-mahjong.html', 'new-jersey-mahjong-hub.html'),
    ('atlantic-city-nj-8-mahjong.html', 'Atlantic City NJ', 'NJ', 'new-jersey-mahjong.html', 'new-jersey-mahjong-hub.html'),
    ('margate-city-nj-nj-mahjong.html', 'Margate City NJ', 'NJ', 'new-jersey-mahjong.html', 'new-jersey-mahjong-hub.html'),
    ('somers-point-nj-nj-mahjong.html', 'Somers Point NJ', 'NJ', 'new-jersey-mahjong.html', 'new-jersey-mahjong-hub.html'),
    ('newton-ma-8-mahjong.html', 'Newton MA', 'MA', 'massachusetts-mahjong.html', 'massachusetts-mahjong-hub.html'),
    ('brookline-ma-2-mahjong.html', 'Brookline MA', 'MA', 'massachusetts-mahjong.html', 'massachusetts-mahjong-hub.html'),
    ('wellesley-ma-ma-mahjong.html', 'Wellesley MA', 'MA', 'massachusetts-mahjong.html', 'massachusetts-mahjong-hub.html'),
    ('needham-ma-ma-mahjong.html', 'Needham MA', 'MA', 'massachusetts-mahjong.html', 'massachusetts-mahjong-hub.html'),
    ('lexington-ma-2-mahjong.html', 'Lexington MA', 'MA', 'massachusetts-mahjong.html', 'massachusetts-mahjong-hub.html'),
    ('concord-ma-2-mahjong.html', 'Concord MA', 'MA', 'massachusetts-mahjong.html', 'massachusetts-mahjong-hub.html'),
    ('sudbury-ma-ma-mahjong.html', 'Sudbury MA', 'MA', 'massachusetts-mahjong.html', 'massachusetts-mahjong-hub.html'),
    ('framingham-ma-2-mahjong.html', 'Framingham MA', 'MA', 'massachusetts-mahjong.html', 'massachusetts-mahjong-hub.html'),
    ('natick-ma-2-mahjong.html', 'Natick MA', 'MA', 'massachusetts-mahjong.html', 'massachusetts-mahjong-hub.html'),
    ('waltham-ma-2-mahjong.html', 'Waltham MA', 'MA', 'massachusetts-mahjong.html', 'massachusetts-mahjong-hub.html'),
    ('arlington-ma-ma-mahjong.html', 'Arlington MA', 'MA', 'massachusetts-mahjong.html', 'massachusetts-mahjong-hub.html'),
    ('belmont-ma-ma-mahjong.html', 'Belmont MA', 'MA', 'massachusetts-mahjong.html', 'massachusetts-mahjong-hub.html'),
    ('marblehead-ma-ma-mahjong.html', 'Marblehead MA', 'MA', 'massachusetts-mahjong.html', 'massachusetts-mahjong-hub.html'),
    ('swampscott-ma-ma-mahjong.html', 'Swampscott MA', 'MA', 'massachusetts-mahjong.html', 'massachusetts-mahjong-hub.html'),
    ('newburyport-ma-ma-mahjong.html', 'Newburyport MA', 'MA', 'massachusetts-mahjong.html', 'massachusetts-mahjong-hub.html'),
    ('greenwich-ct-2-mahjong.html', 'Greenwich CT', 'CT', 'connecticut-mahjong.html', 'connecticut-mahjong-hub.html'),
    ('stamford-ct-8-mahjong.html', 'Stamford CT', 'CT', 'connecticut-mahjong.html', 'connecticut-mahjong-hub.html'),
    ('darien-ct-ct-mahjong.html', 'Darien CT', 'CT', 'connecticut-mahjong.html', 'connecticut-mahjong-hub.html'),
    ('westport-ct-ct-mahjong.html', 'Westport CT', 'CT', 'connecticut-mahjong.html', 'connecticut-mahjong-hub.html'),
    ('fairfield-ct-2-mahjong.html', 'Fairfield CT', 'CT', 'connecticut-mahjong.html', 'connecticut-mahjong-hub.html'),
    ('trumbull-ct-ct-mahjong.html', 'Trumbull CT', 'CT', 'connecticut-mahjong.html', 'connecticut-mahjong-hub.html'),
    ('milford-ct-ct-mahjong.html', 'Milford CT', 'CT', 'connecticut-mahjong.html', 'connecticut-mahjong-hub.html'),
    ('guilford-ct-ct-mahjong.html', 'Guilford CT', 'CT', 'connecticut-mahjong.html', 'connecticut-mahjong-hub.html'),
    ('madison-ct-ct-mahjong.html', 'Madison CT', 'CT', 'connecticut-mahjong.html', 'connecticut-mahjong-hub.html'),
    ('old-saybrook-ct-ct-mahjong.html', 'Old Saybrook CT', 'CT', 'connecticut-mahjong.html', 'connecticut-mahjong-hub.html'),
    ('mystic-ct-ct-mahjong.html', 'Mystic CT', 'CT', 'connecticut-mahjong.html', 'connecticut-mahjong-hub.html'),
    ('stonington-ct-ct-mahjong.html', 'Stonington CT', 'CT', 'connecticut-mahjong.html', 'connecticut-mahjong-hub.html'),
    ('litchfield-ct-ct-mahjong.html', 'Litchfield CT', 'CT', 'connecticut-mahjong.html', 'connecticut-mahjong-hub.html'),
    ('torrington-ct-ct-mahjong.html', 'Torrington CT', 'CT', 'connecticut-mahjong.html', 'connecticut-mahjong-hub.html'),
    ('simsbury-ct-ct-mahjong.html', 'Simsbury CT', 'CT', 'connecticut-mahjong.html', 'connecticut-mahjong-hub.html'),
    ('edina-mn-8-mahjong.html', 'Edina MN', 'MN', 'minnesota-mahjong.html', 'minnesota-mahjong-hub.html'),
    ('minnetonka-mn-mn-mahjong.html', 'Minnetonka MN', 'MN', 'minnesota-mahjong.html', 'minnesota-mahjong-hub.html'),
    ('plymouth-mn-mn-mahjong.html', 'Plymouth MN', 'MN', 'minnesota-mahjong.html', 'minnesota-mahjong-hub.html'),
    ('maple-grove-mn-mn-mahjong.html', 'Maple Grove MN', 'MN', 'minnesota-mahjong.html', 'minnesota-mahjong-hub.html'),
    ('blaine-mn-7-mahjong.html', 'Blaine MN', 'MN', 'minnesota-mahjong.html', 'minnesota-mahjong-hub.html'),
    ('lakeville-mn-8-mahjong.html', 'Lakeville MN', 'MN', 'minnesota-mahjong.html', 'minnesota-mahjong-hub.html'),
    ('apple-valley-mn-mn-mahjong.html', 'Apple Valley MN', 'MN', 'minnesota-mahjong.html', 'minnesota-mahjong-hub.html'),
    ('eagan-mn-8-mahjong.html', 'Eagan MN', 'MN', 'minnesota-mahjong.html', 'minnesota-mahjong-hub.html'),
    ('woodbury-mn-2-mahjong.html', 'Woodbury MN', 'MN', 'minnesota-mahjong.html', 'minnesota-mahjong-hub.html'),
    ('stillwater-mn-2-mahjong.html', 'Stillwater MN', 'MN', 'minnesota-mahjong.html', 'minnesota-mahjong-hub.html'),
    ('mankato-mn-2-mahjong.html', 'Mankato MN', 'MN', 'minnesota-mahjong.html', 'minnesota-mahjong-hub.html'),
    ('rochester-mn-8-mahjong.html', 'Rochester MN', 'MN', 'minnesota-mahjong.html', 'minnesota-mahjong-hub.html'),
    ('duluth-mn-2-mahjong.html', 'Duluth MN', 'MN', 'minnesota-mahjong.html', 'minnesota-mahjong-hub.html'),
    ('bemidji-mn-2-mahjong.html', 'Bemidji MN', 'MN', 'minnesota-mahjong.html', 'minnesota-mahjong-hub.html'),
    ('brainerd-mn-2-mahjong.html', 'Brainerd MN', 'MN', 'minnesota-mahjong.html', 'minnesota-mahjong-hub.html'),
    ('brookfield-wi-8-mahjong.html', 'Brookfield WI', 'WI', 'wisconsin-mahjong.html', 'wisconsin-mahjong-hub.html'),
    ('wauwatosa-wi-wi-mahjong.html', 'Wauwatosa WI', 'WI', 'wisconsin-mahjong.html', 'wisconsin-mahjong-hub.html'),
    ('mequon-wi-2-mahjong.html', 'Mequon WI', 'WI', 'wisconsin-mahjong.html', 'wisconsin-mahjong-hub.html'),
    ('oconomowoc-wi-wi-mahjong.html', 'Oconomowoc WI', 'WI', 'wisconsin-mahjong.html', 'wisconsin-mahjong-hub.html'),
    ('lake-geneva-wi-wi-mahjong.html', 'Lake Geneva WI', 'WI', 'wisconsin-mahjong.html', 'wisconsin-mahjong-hub.html'),
    ('sheboygan-wi-2-mahjong.html', 'Sheboygan WI', 'WI', 'wisconsin-mahjong.html', 'wisconsin-mahjong-hub.html'),
    ('fond-du-lac-wi-8-mahjong.html', 'Fond du Lac WI', 'WI', 'wisconsin-mahjong.html', 'wisconsin-mahjong-hub.html'),
    ('appleton-wi-2-mahjong.html', 'Appleton WI', 'WI', 'wisconsin-mahjong.html', 'wisconsin-mahjong-hub.html'),
    ('oshkosh-wi-2-mahjong.html', 'Oshkosh WI', 'WI', 'wisconsin-mahjong.html', 'wisconsin-mahjong-hub.html'),
    ('wausau-wi-8-mahjong.html', 'Wausau WI', 'WI', 'wisconsin-mahjong.html', 'wisconsin-mahjong-hub.html'),
    ('rhinelander-wi-2-mahjong.html', 'Rhinelander WI', 'WI', 'wisconsin-mahjong.html', 'wisconsin-mahjong-hub.html'),
    ('stevens-point-wi-2-mahjong.html', 'Stevens Point WI', 'WI', 'wisconsin-mahjong.html', 'wisconsin-mahjong-hub.html'),
    ('la-crosse-wi-8-mahjong.html', 'La Crosse WI', 'WI', 'wisconsin-mahjong.html', 'wisconsin-mahjong-hub.html'),
    ('eau-claire-wi-8-mahjong.html', 'Eau Claire WI', 'WI', 'wisconsin-mahjong.html', 'wisconsin-mahjong-hub.html'),
    ('superior-wi-wi-mahjong.html', 'Superior WI', 'WI', 'wisconsin-mahjong.html', 'wisconsin-mahjong-hub.html'),
    ('chesterfield-mo-2-mahjong.html', 'Chesterfield MO', 'MO', 'missouri-mahjong.html', 'missouri-mahjong-hub.html'),
    ('ballwin-mo-mo-mahjong.html', 'Ballwin MO', 'MO', 'missouri-mahjong.html', 'missouri-mahjong-hub.html'),
    ('wildwood-mo-mo-mahjong.html', 'Wildwood MO', 'MO', 'missouri-mahjong.html', 'missouri-mahjong-hub.html'),
    ('ofallon-mo-mo-mahjong.html', "O'Fallon MO", 'MO', 'missouri-mahjong.html', 'missouri-mahjong-hub.html'),
    ('st-charles-mo-7-mahjong.html', 'St Charles MO', 'MO', 'missouri-mahjong.html', 'missouri-mahjong-hub.html'),
    ('st-peters-mo-mo-mahjong.html', 'St Peters MO', 'MO', 'missouri-mahjong.html', 'missouri-mahjong-hub.html'),
    ('wentzville-mo-mo-mahjong.html', 'Wentzville MO', 'MO', 'missouri-mahjong.html', 'missouri-mahjong-hub.html'),
    ('lake-st-louis-mo-mo-mahjong.html', 'Lake St Louis MO', 'MO', 'missouri-mahjong.html', 'missouri-mahjong-hub.html'),
    ('cape-girardeau-mo-8-mahjong.html', 'Cape Girardeau MO', 'MO', 'missouri-mahjong.html', 'missouri-mahjong-hub.html'),
    ('poplar-bluff-mo-2-mahjong.html', 'Poplar Bluff MO', 'MO', 'missouri-mahjong.html', 'missouri-mahjong-hub.html'),
    ('sikeston-mo-2-mahjong.html', 'Sikeston MO', 'MO', 'missouri-mahjong.html', 'missouri-mahjong-hub.html'),
    ('rolla-mo-2-mahjong.html', 'Rolla MO', 'MO', 'missouri-mahjong.html', 'missouri-mahjong-hub.html'),
    ('warrensburg-mo-2-mahjong.html', 'Warrensburg MO', 'MO', 'missouri-mahjong.html', 'missouri-mahjong-hub.html'),
    ('sedalia-mo-2-mahjong.html', 'Sedalia MO', 'MO', 'missouri-mahjong.html', 'missouri-mahjong-hub.html'),
    ('jefferson-city-mo-8-mahjong.html', 'Jefferson City MO', 'MO', 'missouri-mahjong.html', 'missouri-mahjong-hub.html'),
    ('metairie-la-3-mahjong.html', 'Metairie LA', 'LA', 'louisiana-mahjong.html', 'louisiana-mahjong-hub.html'),
    ('kenner-la-7-mahjong.html', 'Kenner LA', 'LA', 'louisiana-mahjong.html', 'louisiana-mahjong-hub.html'),
    ('slidell-la-3-mahjong.html', 'Slidell LA', 'LA', 'louisiana-mahjong.html', 'louisiana-mahjong-hub.html'),
    ('mandeville-la-2-mahjong.html', 'Mandeville LA', 'LA', 'louisiana-mahjong.html', 'louisiana-mahjong-hub.html'),
    ('covington-la-2-mahjong.html', 'Covington LA', 'LA', 'louisiana-mahjong.html', 'louisiana-mahjong-hub.html'),
    ('hammond-la-3-mahjong.html', 'Hammond LA', 'LA', 'louisiana-mahjong.html', 'louisiana-mahjong-hub.html'),
    ('thibodaux-la-3-mahjong.html', 'Thibodaux LA', 'LA', 'louisiana-mahjong.html', 'louisiana-mahjong-hub.html'),
    ('houma-la-3-mahjong.html', 'Houma LA', 'LA', 'louisiana-mahjong.html', 'louisiana-mahjong-hub.html'),
    ('morgan-city-la-2-mahjong.html', 'Morgan City LA', 'LA', 'louisiana-mahjong.html', 'louisiana-mahjong-hub.html'),
    ('opelousas-la-3-mahjong.html', 'Opelousas LA', 'LA', 'louisiana-mahjong.html', 'louisiana-mahjong-hub.html'),
    ('ruston-la-3-mahjong.html', 'Ruston LA', 'LA', 'louisiana-mahjong.html', 'louisiana-mahjong-hub.html'),
    ('monroe-la-3-mahjong.html', 'Monroe LA', 'LA', 'louisiana-mahjong.html', 'louisiana-mahjong-hub.html'),
    ('alexandria-la-9-mahjong.html', 'Alexandria LA', 'LA', 'louisiana-mahjong.html', 'louisiana-mahjong-hub.html'),
    ('lake-charles-la-3-mahjong.html', 'Lake Charles LA', 'LA', 'louisiana-mahjong.html', 'louisiana-mahjong-hub.html'),
    ('sulphur-la-3-mahjong.html', 'Sulphur LA', 'LA', 'louisiana-mahjong.html', 'louisiana-mahjong-hub.html'),
    ('bowling-green-ky-3-mahjong.html', 'Bowling Green KY', 'KY', 'kentucky-mahjong.html', 'kentucky-mahjong-hub.html'),
    ('richmond-ky-3-mahjong.html', 'Richmond KY', 'KY', 'kentucky-mahjong.html', 'kentucky-mahjong-hub.html'),
    ('georgetown-ky-4-mahjong.html', 'Georgetown KY', 'KY', 'kentucky-mahjong.html', 'kentucky-mahjong-hub.html'),
    ('florence-ky-3-mahjong.html', 'Florence KY', 'KY', 'kentucky-mahjong.html', 'kentucky-mahjong-hub.html'),
    ('covington-ky-3-mahjong.html', 'Covington KY', 'KY', 'kentucky-mahjong.html', 'kentucky-mahjong-hub.html'),
    ('newport-ky-2-mahjong.html', 'Newport KY', 'KY', 'kentucky-mahjong.html', 'kentucky-mahjong-hub.html'),
    ('ashland-ky-3-mahjong.html', 'Ashland KY', 'KY', 'kentucky-mahjong.html', 'kentucky-mahjong-hub.html'),
    ('morehead-ky-2-mahjong.html', 'Morehead KY', 'KY', 'kentucky-mahjong.html', 'kentucky-mahjong-hub.html'),
    ('somerset-ky-3-mahjong.html', 'Somerset KY', 'KY', 'kentucky-mahjong.html', 'kentucky-mahjong-hub.html'),
    ('london-ky-2-mahjong.html', 'London KY', 'KY', 'kentucky-mahjong.html', 'kentucky-mahjong-hub.html'),
    ('campbellsville-ky-2-mahjong.html', 'Campbellsville KY', 'KY', 'kentucky-mahjong.html', 'kentucky-mahjong-hub.html'),
    ('murray-ky-3-mahjong.html', 'Murray KY', 'KY', 'kentucky-mahjong.html', 'kentucky-mahjong-hub.html'),
    ('paducah-ky-3-mahjong.html', 'Paducah KY', 'KY', 'kentucky-mahjong.html', 'kentucky-mahjong-hub.html'),
    ('henderson-ky-3-mahjong.html', 'Henderson KY', 'KY', 'kentucky-mahjong.html', 'kentucky-mahjong-hub.html'),
    ('madisonville-ky-3-mahjong.html', 'Madisonville KY', 'KY', 'kentucky-mahjong.html', 'kentucky-mahjong-hub.html'),
    ('carmel-in-2-mahjong.html', 'Carmel IN', 'IN', 'indiana-mahjong.html', 'indiana-mahjong-hub.html'),
    ('fishers-in-7-mahjong.html', 'Fishers IN', 'IN', 'indiana-mahjong.html', 'indiana-mahjong-hub.html'),
    ('noblesville-in-8-mahjong.html', 'Noblesville IN', 'IN', 'indiana-mahjong.html', 'indiana-mahjong-hub.html'),
    ('greenwood-in-8-mahjong.html', 'Greenwood IN', 'IN', 'indiana-mahjong.html', 'indiana-mahjong-hub.html'),
    ('bloomington-in-8-mahjong.html', 'Bloomington IN', 'IN', 'indiana-mahjong.html', 'indiana-mahjong-hub.html'),
    ('columbus-in-2-mahjong.html', 'Columbus IN', 'IN', 'indiana-mahjong.html', 'indiana-mahjong-hub.html'),
    ('jeffersonville-in-6-mahjong.html', 'Jeffersonville IN', 'IN', 'indiana-mahjong.html', 'indiana-mahjong-hub.html'),
    ('new-albany-in-2-mahjong.html', 'New Albany IN', 'IN', 'indiana-mahjong.html', 'indiana-mahjong-hub.html'),
    ('muncie-in-6-mahjong.html', 'Muncie IN', 'IN', 'indiana-mahjong.html', 'indiana-mahjong-hub.html'),
    ('anderson-in-2-mahjong.html', 'Anderson IN', 'IN', 'indiana-mahjong.html', 'indiana-mahjong-hub.html'),
    ('kokomo-in-8-mahjong.html', 'Kokomo IN', 'IN', 'indiana-mahjong.html', 'indiana-mahjong-hub.html'),
    ('lafayette-in-8-mahjong.html', 'Lafayette IN', 'IN', 'indiana-mahjong.html', 'indiana-mahjong-hub.html'),
    ('west-lafayette-in-2-mahjong.html', 'West Lafayette IN', 'IN', 'indiana-mahjong.html', 'indiana-mahjong-hub.html'),
    ('terre-haute-in-2-mahjong.html', 'Terre Haute IN', 'IN', 'indiana-mahjong.html', 'indiana-mahjong-hub.html'),
    ('evansville-in-2-mahjong.html', 'Evansville IN', 'IN', 'indiana-mahjong.html', 'indiana-mahjong-hub.html'),
    ('west-des-moines-ia-8-mahjong.html', 'West Des Moines IA', 'IA', 'iowa-mahjong.html', 'iowa-mahjong-hub.html'),
    ('ankeny-ia-6-mahjong.html', 'Ankeny IA', 'IA', 'iowa-mahjong.html', 'iowa-mahjong-hub.html'),
    ('urbandale-ia-8-mahjong.html', 'Urbandale IA', 'IA', 'iowa-mahjong.html', 'iowa-mahjong-hub.html'),
    ('johnston-ia-2-mahjong.html', 'Johnston IA', 'IA', 'iowa-mahjong.html', 'iowa-mahjong-hub.html'),
    ('coralville-ia-2-mahjong.html', 'Coralville IA', 'IA', 'iowa-mahjong.html', 'iowa-mahjong-hub.html'),
    ('iowa-city-ia-2-mahjong.html', 'Iowa City IA', 'IA', 'iowa-mahjong.html', 'iowa-mahjong-hub.html'),
    ('waterloo-ia-8-mahjong.html', 'Waterloo IA', 'IA', 'iowa-mahjong.html', 'iowa-mahjong-hub.html'),
    ('cedar-falls-ia-2-mahjong.html', 'Cedar Falls IA', 'IA', 'iowa-mahjong.html', 'iowa-mahjong-hub.html'),
    ('dubuque-ia-2-mahjong.html', 'Dubuque IA', 'IA', 'iowa-mahjong.html', 'iowa-mahjong-hub.html'),
    ('sioux-city-ia-6-mahjong.html', 'Sioux City IA', 'IA', 'iowa-mahjong.html', 'iowa-mahjong-hub.html'),
    ('council-bluffs-ia-8-mahjong.html', 'Council Bluffs IA', 'IA', 'iowa-mahjong.html', 'iowa-mahjong-hub.html'),
    ('mason-city-ia-2-mahjong.html', 'Mason City IA', 'IA', 'iowa-mahjong.html', 'iowa-mahjong-hub.html'),
    ('fort-dodge-ia-2-mahjong.html', 'Fort Dodge IA', 'IA', 'iowa-mahjong.html', 'iowa-mahjong-hub.html'),
    ('burlington-ia-2-mahjong.html', 'Burlington IA', 'IA', 'iowa-mahjong.html', 'iowa-mahjong-hub.html'),
    ('muscatine-ia-2-mahjong.html', 'Muscatine IA', 'IA', 'iowa-mahjong.html', 'iowa-mahjong-hub.html'),
    ('overland-park-ks-8-mahjong.html', 'Overland Park KS', 'KS', 'kansas-mahjong.html', 'kansas-mahjong-hub.html'),
    ('olathe-ks-8-mahjong.html', 'Olathe KS', 'KS', 'kansas-mahjong.html', 'kansas-mahjong-hub.html'),
    ('lenexa-ks-8-mahjong.html', 'Lenexa KS', 'KS', 'kansas-mahjong.html', 'kansas-mahjong-hub.html'),
    ('shawnee-ks-2-mahjong.html', 'Shawnee KS', 'KS', 'kansas-mahjong.html', 'kansas-mahjong-hub.html'),
    ('manhattan-ks-8-mahjong.html', 'Manhattan KS', 'KS', 'kansas-mahjong.html', 'kansas-mahjong-hub.html'),
    ('lawrence-ks-8-mahjong.html', 'Lawrence KS', 'KS', 'kansas-mahjong.html', 'kansas-mahjong-hub.html'),
    ('hutchinson-ks-6-mahjong.html', 'Hutchinson KS', 'KS', 'kansas-mahjong.html', 'kansas-mahjong-hub.html'),
    ('salina-ks-2-mahjong.html', 'Salina KS', 'KS', 'kansas-mahjong.html', 'kansas-mahjong-hub.html'),
    ('dodge-city-ks-2-mahjong.html', 'Dodge City KS', 'KS', 'kansas-mahjong.html', 'kansas-mahjong-hub.html'),
    ('garden-city-ks-2-mahjong.html', 'Garden City KS', 'KS', 'kansas-mahjong.html', 'kansas-mahjong-hub.html'),
    ('emporia-ks-2-mahjong.html', 'Emporia KS', 'KS', 'kansas-mahjong.html', 'kansas-mahjong-hub.html'),
    ('pittsburg-ks-2-mahjong.html', 'Pittsburg KS', 'KS', 'kansas-mahjong.html', 'kansas-mahjong-hub.html'),
    ('hays-ks-2-mahjong.html', 'Hays KS', 'KS', 'kansas-mahjong.html', 'kansas-mahjong-hub.html'),
    ('great-bend-ks-2-mahjong.html', 'Great Bend KS', 'KS', 'kansas-mahjong.html', 'kansas-mahjong-hub.html'),
    ('mcpherson-ks-2-mahjong.html', 'McPherson KS', 'KS', 'kansas-mahjong.html', 'kansas-mahjong-hub.html'),
    ('grand-island-ne-2-mahjong.html', 'Grand Island NE', 'NE', 'nebraska-mahjong.html', 'nebraska-mahjong-hub.html'),
    ('kearney-ne-2-mahjong.html', 'Kearney NE', 'NE', 'nebraska-mahjong.html', 'nebraska-mahjong-hub.html'),
    ('norfolk-ne-2-mahjong.html', 'Norfolk NE', 'NE', 'nebraska-mahjong.html', 'nebraska-mahjong-hub.html'),
    ('columbus-ne-2-mahjong.html', 'Columbus NE', 'NE', 'nebraska-mahjong.html', 'nebraska-mahjong-hub.html'),
    ('fremont-ne-2-mahjong.html', 'Fremont NE', 'NE', 'nebraska-mahjong.html', 'nebraska-mahjong-hub.html'),
    ('bellevue-ne-2-mahjong.html', 'Bellevue NE', 'NE', 'nebraska-mahjong.html', 'nebraska-mahjong-hub.html'),
    ('papillion-ne-2-mahjong.html', 'Papillion NE', 'NE', 'nebraska-mahjong.html', 'nebraska-mahjong-hub.html'),
    ('la-vista-ne-2-mahjong.html', 'La Vista NE', 'NE', 'nebraska-mahjong.html', 'nebraska-mahjong-hub.html'),
    ('scottsbluff-ne-2-mahjong.html', 'Scottsbluff NE', 'NE', 'nebraska-mahjong.html', 'nebraska-mahjong-hub.html'),
    ('north-platte-ne-2-mahjong.html', 'North Platte NE', 'NE', 'nebraska-mahjong.html', 'nebraska-mahjong-hub.html'),
    ('hastings-ne-2-mahjong.html', 'Hastings NE', 'NE', 'nebraska-mahjong.html', 'nebraska-mahjong-hub.html'),
    ('beatrice-ne-2-mahjong.html', 'Beatrice NE', 'NE', 'nebraska-mahjong.html', 'nebraska-mahjong-hub.html'),
    ('mccook-ne-2-mahjong.html', 'McCook NE', 'NE', 'nebraska-mahjong.html', 'nebraska-mahjong-hub.html'),
    ('alliance-ne-2-mahjong.html', 'Alliance NE', 'NE', 'nebraska-mahjong.html', 'nebraska-mahjong-hub.html'),
    ('sidney-ne-2-mahjong.html', 'Sidney NE', 'NE', 'nebraska-mahjong.html', 'nebraska-mahjong-hub.html'),
    ('broken-arrow-ok-8-mahjong.html', 'Broken Arrow OK', 'OK', 'oklahoma-mahjong.html', 'oklahoma-mahjong-hub.html'),
    ('edmond-ok-2-mahjong.html', 'Edmond OK', 'OK', 'oklahoma-mahjong.html', 'oklahoma-mahjong-hub.html'),
    ('norman-ok-2-mahjong.html', 'Norman OK', 'OK', 'oklahoma-mahjong.html', 'oklahoma-mahjong-hub.html'),
    ('moore-ok-2-mahjong.html', 'Moore OK', 'OK', 'oklahoma-mahjong.html', 'oklahoma-mahjong-hub.html'),
    ('stillwater-ok-2-mahjong.html', 'Stillwater OK', 'OK', 'oklahoma-mahjong.html', 'oklahoma-mahjong-hub.html'),
    ('enid-ok-2-mahjong.html', 'Enid OK', 'OK', 'oklahoma-mahjong.html', 'oklahoma-mahjong-hub.html'),
    ('lawton-ok-8-mahjong.html', 'Lawton OK', 'OK', 'oklahoma-mahjong.html', 'oklahoma-mahjong-hub.html'),
    ('muskogee-ok-6-mahjong.html', 'Muskogee OK', 'OK', 'oklahoma-mahjong.html', 'oklahoma-mahjong-hub.html'),
    ('ada-ok-2-mahjong.html', 'Ada OK', 'OK', 'oklahoma-mahjong.html', 'oklahoma-mahjong-hub.html'),
    ('durant-ok-2-mahjong.html', 'Durant OK', 'OK', 'oklahoma-mahjong.html', 'oklahoma-mahjong-hub.html'),
    ('ardmore-ok-2-mahjong.html', 'Ardmore OK', 'OK', 'oklahoma-mahjong.html', 'oklahoma-mahjong-hub.html'),
    ('ponca-city-ok-2-mahjong.html', 'Ponca City OK', 'OK', 'oklahoma-mahjong.html', 'oklahoma-mahjong-hub.html'),
    ('bartlesville-ok-2-mahjong.html', 'Bartlesville OK', 'OK', 'oklahoma-mahjong.html', 'oklahoma-mahjong-hub.html'),
    ('guthrie-ok-2-mahjong.html', 'Guthrie OK', 'OK', 'oklahoma-mahjong.html', 'oklahoma-mahjong-hub.html'),
    ('claremore-ok-ok-mahjong.html', 'Claremore OK', 'OK', 'oklahoma-mahjong.html', 'oklahoma-mahjong-hub.html'),
    ('fayetteville-ar-3-mahjong.html', 'Fayetteville AR', 'AR', 'arkansas-mahjong.html', 'arkansas-mahjong-hub.html'),
    ('springdale-ar-2-mahjong.html', 'Springdale AR', 'AR', 'arkansas-mahjong.html', 'arkansas-mahjong-hub.html'),
    ('rogers-ar-9-mahjong.html', 'Rogers AR', 'AR', 'arkansas-mahjong.html', 'arkansas-mahjong-hub.html'),
    ('bentonville-ar-3-mahjong.html', 'Bentonville AR', 'AR', 'arkansas-mahjong.html', 'arkansas-mahjong-hub.html'),
    ('conway-ar-3-mahjong.html', 'Conway AR', 'AR', 'arkansas-mahjong.html', 'arkansas-mahjong-hub.html'),
    ('jonesboro-ar-3-mahjong.html', 'Jonesboro AR', 'AR', 'arkansas-mahjong.html', 'arkansas-mahjong-hub.html'),
    ('paragould-ar-3-mahjong.html', 'Paragould AR', 'AR', 'arkansas-mahjong.html', 'arkansas-mahjong-hub.html'),
    ('hot-springs-ar-3-mahjong.html', 'Hot Springs AR', 'AR', 'arkansas-mahjong.html', 'arkansas-mahjong-hub.html'),
    ('texarkana-ar-3-mahjong.html', 'Texarkana AR', 'AR', 'arkansas-mahjong.html', 'arkansas-mahjong-hub.html'),
    ('el-dorado-ar-3-mahjong.html', 'El Dorado AR', 'AR', 'arkansas-mahjong.html', 'arkansas-mahjong-hub.html'),
    ('magnolia-ar-2-mahjong.html', 'Magnolia AR', 'AR', 'arkansas-mahjong.html', 'arkansas-mahjong-hub.html'),
    ('camden-ar-2-mahjong.html', 'Camden AR', 'AR', 'arkansas-mahjong.html', 'arkansas-mahjong-hub.html'),
    ('arkadelphia-ar-2-mahjong.html', 'Arkadelphia AR', 'AR', 'arkansas-mahjong.html', 'arkansas-mahjong-hub.html'),
    ('batesville-ar-2-mahjong.html', 'Batesville AR', 'AR', 'arkansas-mahjong.html', 'arkansas-mahjong-hub.html'),
    ('mountain-home-ar-2-mahjong.html', 'Mountain Home AR', 'AR', 'arkansas-mahjong.html', 'arkansas-mahjong-hub.html'),
]
