# auto-generated city tuples — WAVE39_CITIES
WAVE39_CITIES = [
    ('trussville-al-mahjong.html', 'Trussville AL', 'AL', 'alabama-mahjong.html', 'alabama-mahjong-hub.html'),
    ('homewood-al-mahjong.html', 'Homewood AL', 'AL', 'alabama-mahjong.html', 'alabama-mahjong-hub.html'),
    ('mountain-brook-al-mahjong.html', 'Mountain Brook AL', 'AL', 'alabama-mahjong.html', 'alabama-mahjong-hub.html'),
    ('vestavia-hills-al-mahjong.html', 'Vestavia Hills AL', 'AL', 'alabama-mahjong.html', 'alabama-mahjong-hub.html'),
    ('pelham-al-mahjong.html', 'Pelham AL', 'AL', 'alabama-mahjong.html', 'alabama-mahjong-hub.html'),
    ('alabaster-al-mahjong.html', 'Alabaster AL', 'AL', 'alabama-mahjong.html', 'alabama-mahjong-hub.html'),
    ('calera-al-mahjong.html', 'Calera AL', 'AL', 'alabama-mahjong.html', 'alabama-mahjong-hub.html'),
    ('helena-al-mahjong.html', 'Helena AL', 'AL', 'alabama-mahjong.html', 'alabama-mahjong-hub.html'),
    ('chelsea-al-mahjong.html', 'Chelsea AL', 'AL', 'alabama-mahjong.html', 'alabama-mahjong-hub.html'),
    ('sylacauga-al-mahjong.html', 'Sylacauga AL', 'AL', 'alabama-mahjong.html', 'alabama-mahjong-hub.html'),
    ('alexander-city-al-mahjong.html', 'Alexander City AL', 'AL', 'alabama-mahjong.html', 'alabama-mahjong-hub.html'),
    ('eufaula-al-mahjong.html', 'Eufaula AL', 'AL', 'alabama-mahjong.html', 'alabama-mahjong-hub.html'),
    ('ozark-al-mahjong.html', 'Ozark AL', 'AL', 'alabama-mahjong.html', 'alabama-mahjong-hub.html'),
    ('andalusia-al-mahjong.html', 'Andalusia AL', 'AL', 'alabama-mahjong.html', 'alabama-mahjong-hub.html'),
    ('atmore-al-mahjong.html', 'Atmore AL', 'AL', 'alabama-mahjong.html', 'alabama-mahjong-hub.html'),
    ('bay-minette-al-mahjong.html', 'Bay Minette AL', 'AL', 'alabama-mahjong.html', 'alabama-mahjong-hub.html'),
    ('foley-al-mahjong.html', 'Foley AL', 'AL', 'alabama-mahjong.html', 'alabama-mahjong-hub.html'),
    ('spanish-fort-al-mahjong.html', 'Spanish Fort AL', 'AL', 'alabama-mahjong.html', 'alabama-mahjong-hub.html'),
    ('daphne-al-mahjong.html', 'Daphne AL', 'AL', 'alabama-mahjong.html', 'alabama-mahjong-hub.html'),
    ('saraland-al-mahjong.html', 'Saraland AL', 'AL', 'alabama-mahjong.html', 'alabama-mahjong-hub.html'),
    ('tillmans-corner-al-mahjong.html', 'Tillmans Corner AL', 'AL', 'alabama-mahjong.html', 'alabama-mahjong-hub.html'),
    ('theodore-al-mahjong.html', 'Theodore AL', 'AL', 'alabama-mahjong.html', 'alabama-mahjong-hub.html'),
    ('satsuma-al-mahjong.html', 'Satsuma AL', 'AL', 'alabama-mahjong.html', 'alabama-mahjong-hub.html'),
    ('citronelle-al-mahjong.html', 'Citronelle AL', 'AL', 'alabama-mahjong.html', 'alabama-mahjong-hub.html'),
    ('monroeville-al-mahjong.html', 'Monroeville AL', 'AL', 'alabama-mahjong.html', 'alabama-mahjong-hub.html'),
    ('thomasville-al-mahjong.html', 'Thomasville AL', 'AL', 'alabama-mahjong.html', 'alabama-mahjong-hub.html'),
    ('demopolis-al-mahjong.html', 'Demopolis AL', 'AL', 'alabama-mahjong.html', 'alabama-mahjong-hub.html'),
    ('livingston-al-mahjong.html', 'Livingston AL', 'AL', 'alabama-mahjong.html', 'alabama-mahjong-hub.html'),
    ('camden-al-mahjong.html', 'Camden AL', 'AL', 'alabama-mahjong.html', 'alabama-mahjong-hub.html'),
    ('greenville-al-mahjong.html', 'Greenville AL', 'AL', 'alabama-mahjong.html', 'alabama-mahjong-hub.html'),
    ('troy-al-mahjong.html', 'Troy AL', 'AL', 'alabama-mahjong.html', 'alabama-mahjong-hub.html'),
    ('headland-al-mahjong.html', 'Headland AL', 'AL', 'alabama-mahjong.html', 'alabama-mahjong-hub.html'),
    ('geneva-al-mahjong.html', 'Geneva AL', 'AL', 'alabama-mahjong.html', 'alabama-mahjong-hub.html'),
    ('hartselle-al-mahjong.html', 'Hartselle AL', 'AL', 'alabama-mahjong.html', 'alabama-mahjong-hub.html'),
    ('athens-al-al-mahjong.html', 'Athens AL', 'AL', 'alabama-mahjong.html', 'alabama-mahjong-hub.html'),
    ('moulton-al-mahjong.html', 'Moulton AL', 'AL', 'alabama-mahjong.html', 'alabama-mahjong-hub.html'),
    ('russellville-al-mahjong.html', 'Russellville AL', 'AL', 'alabama-mahjong.html', 'alabama-mahjong-hub.html'),
    ('jasper-al-al-mahjong.html', 'Jasper AL', 'AL', 'alabama-mahjong.html', 'alabama-mahjong-hub.html'),
    ('oneonta-al-mahjong.html', 'Oneonta AL', 'AL', 'alabama-mahjong.html', 'alabama-mahjong-hub.html'),
    ('guntersville-al-mahjong.html', 'Guntersville AL', 'AL', 'alabama-mahjong.html', 'alabama-mahjong-hub.html'),
    ('scottsboro-al-mahjong.html', 'Scottsboro AL', 'AL', 'alabama-mahjong.html', 'alabama-mahjong-hub.html'),
    ('fort-payne-al-mahjong.html', 'Fort Payne AL', 'AL', 'alabama-mahjong.html', 'alabama-mahjong-hub.html'),
    ('albertville-al-mahjong.html', 'Albertville AL', 'AL', 'alabama-mahjong.html', 'alabama-mahjong-hub.html'),
    ('boaz-al-mahjong.html', 'Boaz AL', 'AL', 'alabama-mahjong.html', 'alabama-mahjong-hub.html'),
    ('pell-city-al-mahjong.html', 'Pell City AL', 'AL', 'alabama-mahjong.html', 'alabama-mahjong-hub.html'),
    ('leeds-al-mahjong.html', 'Leeds AL', 'AL', 'alabama-mahjong.html', 'alabama-mahjong-hub.html'),
    ('madison-al-6-mahjong.html', 'Madison AL', 'AL', 'alabama-mahjong.html', 'alabama-mahjong-hub.html'),
    ('decatur-al-5-mahjong.html', 'Decatur AL', 'AL', 'alabama-mahjong.html', 'alabama-mahjong-hub.html'),
    ('florence-al-al-mahjong.html', 'Florence AL', 'AL', 'alabama-mahjong.html', 'alabama-mahjong-hub.html'),
    ('huntsville-al-6-mahjong.html', 'Huntsville AL', 'AL', 'alabama-mahjong.html', 'alabama-mahjong-hub.html'),
    ('dothan-al-al-mahjong.html', 'Dothan AL', 'AL', 'alabama-mahjong.html', 'alabama-mahjong-hub.html'),
    ('auburn-al-al-mahjong.html', 'Auburn AL', 'AL', 'alabama-mahjong.html', 'alabama-mahjong-hub.html'),
    ('opelika-al-al-mahjong.html', 'Opelika AL', 'AL', 'alabama-mahjong.html', 'alabama-mahjong-hub.html'),
    ('tuscaloosa-al-5-mahjong.html', 'Tuscaloosa AL', 'AL', 'alabama-mahjong.html', 'alabama-mahjong-hub.html'),
    ('gadsden-al-al-mahjong.html', 'Gadsden AL', 'AL', 'alabama-mahjong.html', 'alabama-mahjong-hub.html'),
    ('anniston-al-al-mahjong.html', 'Anniston AL', 'AL', 'alabama-mahjong.html', 'alabama-mahjong-hub.html'),
    ('cullman-al-al-mahjong.html', 'Cullman AL', 'AL', 'alabama-mahjong.html', 'alabama-mahjong-hub.html'),
    ('enterprise-al-al-mahjong.html', 'Enterprise AL', 'AL', 'alabama-mahjong.html', 'alabama-mahjong-hub.html'),
    ('selma-al-al-mahjong.html', 'Selma AL', 'AL', 'alabama-mahjong.html', 'alabama-mahjong-hub.html'),
    ('prattville-al-al-mahjong.html', 'Prattville AL', 'AL', 'alabama-mahjong.html', 'alabama-mahjong-hub.html'),
    ('fairhope-al-mahjong.html', 'Fairhope AL', 'AL', 'alabama-mahjong.html', 'alabama-mahjong-hub.html'),
    ('bentonville-ar-ar-mahjong.html', 'Bentonville AR', 'AR', 'arkansas-mahjong.html', 'arkansas-mahjong-hub.html'),
    ('rogers-ar-7-mahjong.html', 'Rogers AR', 'AR', 'arkansas-mahjong.html', 'arkansas-mahjong-hub.html'),
    ('bella-vista-ar-mahjong.html', 'Bella Vista AR', 'AR', 'arkansas-mahjong.html', 'arkansas-mahjong-hub.html'),
    ('siloam-springs-ar-mahjong.html', 'Siloam Springs AR', 'AR', 'arkansas-mahjong.html', 'arkansas-mahjong-hub.html'),
    ('searcy-ar-ar-mahjong.html', 'Searcy AR', 'AR', 'arkansas-mahjong.html', 'arkansas-mahjong-hub.html'),
    ('batesville-ar-mahjong.html', 'Batesville AR', 'AR', 'arkansas-mahjong.html', 'arkansas-mahjong-hub.html'),
    ('heber-springs-ar-mahjong.html', 'Heber Springs AR', 'AR', 'arkansas-mahjong.html', 'arkansas-mahjong-hub.html'),
    ('greers-ferry-ar-mahjong.html', 'Greers Ferry AR', 'AR', 'arkansas-mahjong.html', 'arkansas-mahjong-hub.html'),
    ('hot-springs-village-ar-mahjong.html', 'Hot Springs Village AR', 'AR', 'arkansas-mahjong.html', 'arkansas-mahjong-hub.html'),
    ('mena-ar-mahjong.html', 'Mena AR', 'AR', 'arkansas-mahjong.html', 'arkansas-mahjong-hub.html'),
    ('de-queen-ar-mahjong.html', 'De Queen AR', 'AR', 'arkansas-mahjong.html', 'arkansas-mahjong-hub.html'),
    ('hope-ar-mahjong.html', 'Hope AR', 'AR', 'arkansas-mahjong.html', 'arkansas-mahjong-hub.html'),
    ('camden-ar-mahjong.html', 'Camden AR', 'AR', 'arkansas-mahjong.html', 'arkansas-mahjong-hub.html'),
    ('el-dorado-ar-ar-mahjong.html', 'El Dorado AR', 'AR', 'arkansas-mahjong.html', 'arkansas-mahjong-hub.html'),
    ('magnolia-ar-mahjong.html', 'Magnolia AR', 'AR', 'arkansas-mahjong.html', 'arkansas-mahjong-hub.html'),
    ('stuttgart-ar-mahjong.html', 'Stuttgart AR', 'AR', 'arkansas-mahjong.html', 'arkansas-mahjong-hub.html'),
    ('forrest-city-ar-mahjong.html', 'Forrest City AR', 'AR', 'arkansas-mahjong.html', 'arkansas-mahjong-hub.html'),
    ('west-memphis-ar-mahjong.html', 'West Memphis AR', 'AR', 'arkansas-mahjong.html', 'arkansas-mahjong-hub.html'),
    ('blytheville-ar-mahjong.html', 'Blytheville AR', 'AR', 'arkansas-mahjong.html', 'arkansas-mahjong-hub.html'),
    ('paragould-ar-ar-mahjong.html', 'Paragould AR', 'AR', 'arkansas-mahjong.html', 'arkansas-mahjong-hub.html'),
    ('jonesboro-ar-ar-mahjong.html', 'Jonesboro AR', 'AR', 'arkansas-mahjong.html', 'arkansas-mahjong-hub.html'),
    ('mountain-home-ar-mahjong.html', 'Mountain Home AR', 'AR', 'arkansas-mahjong.html', 'arkansas-mahjong-hub.html'),
    ('harrison-ar-mahjong.html', 'Harrison AR', 'AR', 'arkansas-mahjong.html', 'arkansas-mahjong-hub.html'),
    ('eureka-springs-ar-mahjong.html', 'Eureka Springs AR', 'AR', 'arkansas-mahjong.html', 'arkansas-mahjong-hub.html'),
    ('russellville-ar-ar-mahjong.html', 'Russellville AR', 'AR', 'arkansas-mahjong.html', 'arkansas-mahjong-hub.html'),
    ('clarksville-ar-mahjong.html', 'Clarksville AR', 'AR', 'arkansas-mahjong.html', 'arkansas-mahjong-hub.html'),
    ('conway-ar-ar-mahjong.html', 'Conway AR', 'AR', 'arkansas-mahjong.html', 'arkansas-mahjong-hub.html'),
    ('maumelle-ar-mahjong.html', 'Maumelle AR', 'AR', 'arkansas-mahjong.html', 'arkansas-mahjong-hub.html'),
    ('sherwood-ar-mahjong.html', 'Sherwood AR', 'AR', 'arkansas-mahjong.html', 'arkansas-mahjong-hub.html'),
    ('jacksonville-ar-ar-mahjong.html', 'Jacksonville AR', 'AR', 'arkansas-mahjong.html', 'arkansas-mahjong-hub.html'),
    ('cabot-ar-mahjong.html', 'Cabot AR', 'AR', 'arkansas-mahjong.html', 'arkansas-mahjong-hub.html'),
    ('bryant-ar-mahjong.html', 'Bryant AR', 'AR', 'arkansas-mahjong.html', 'arkansas-mahjong-hub.html'),
    ('arkadelphia-ar-mahjong.html', 'Arkadelphia AR', 'AR', 'arkansas-mahjong.html', 'arkansas-mahjong-hub.html'),
    ('malvern-ar-mahjong.html', 'Malvern AR', 'AR', 'arkansas-mahjong.html', 'arkansas-mahjong-hub.html'),
    ('fayetteville-ar-ar-mahjong.html', 'Fayetteville AR', 'AR', 'arkansas-mahjong.html', 'arkansas-mahjong-hub.html'),
    ('springdale-ar-mahjong.html', 'Springdale AR', 'AR', 'arkansas-mahjong.html', 'arkansas-mahjong-hub.html'),
    ('hot-springs-ar-ar-mahjong.html', 'Hot Springs AR', 'AR', 'arkansas-mahjong.html', 'arkansas-mahjong-hub.html'),
    ('texarkana-ar-ar-mahjong.html', 'Texarkana AR', 'AR', 'arkansas-mahjong.html', 'arkansas-mahjong-hub.html'),
    ('ponte-vedra-beach-fl-mahjong.html', 'Ponte Vedra Beach FL', 'FL', 'florida-mahjong.html', 'florida-mahjong-hub.html'),
    ('atlantic-beach-fl-mahjong.html', 'Atlantic Beach FL', 'FL', 'florida-mahjong.html', 'florida-mahjong-hub.html'),
    ('neptune-beach-fl-mahjong.html', 'Neptune Beach FL', 'FL', 'florida-mahjong.html', 'florida-mahjong-hub.html'),
    ('fernandina-beach-fl-mahjong.html', 'Fernandina Beach FL', 'FL', 'florida-mahjong.html', 'florida-mahjong-hub.html'),
    ('amelia-island-fl-mahjong.html', 'Amelia Island FL', 'FL', 'florida-mahjong.html', 'florida-mahjong-hub.html'),
    ('st-augustine-beach-fl-mahjong.html', 'St Augustine Beach FL', 'FL', 'florida-mahjong.html', 'florida-mahjong-hub.html'),
    ('palm-coast-fl-fl-mahjong.html', 'Palm Coast FL', 'FL', 'florida-mahjong.html', 'florida-mahjong-hub.html'),
    ('flagler-beach-fl-mahjong.html', 'Flagler Beach FL', 'FL', 'florida-mahjong.html', 'florida-mahjong-hub.html'),
    ('new-smyrna-beach-fl-fl-mahjong.html', 'New Smyrna Beach FL', 'FL', 'florida-mahjong.html', 'florida-mahjong-hub.html'),
    ('edgewater-fl-mahjong.html', 'Edgewater FL', 'FL', 'florida-mahjong.html', 'florida-mahjong-hub.html'),
    ('titusville-fl-4-mahjong.html', 'Titusville FL', 'FL', 'florida-mahjong.html', 'florida-mahjong-hub.html'),
    ('melbourne-beach-fl-mahjong.html', 'Melbourne Beach FL', 'FL', 'florida-mahjong.html', 'florida-mahjong-hub.html'),
    ('indialantic-fl-mahjong.html', 'Indialantic FL', 'FL', 'florida-mahjong.html', 'florida-mahjong-hub.html'),
    ('sebastian-fl-mahjong.html', 'Sebastian FL', 'FL', 'florida-mahjong.html', 'florida-mahjong-hub.html'),
    ('stuart-fl-fl-mahjong.html', 'Stuart FL', 'FL', 'florida-mahjong.html', 'florida-mahjong-hub.html'),
    ('jensen-beach-fl-mahjong.html', 'Jensen Beach FL', 'FL', 'florida-mahjong.html', 'florida-mahjong-hub.html'),
    ('hobe-sound-fl-mahjong.html', 'Hobe Sound FL', 'FL', 'florida-mahjong.html', 'florida-mahjong-hub.html'),
    ('tequesta-fl-mahjong.html', 'Tequesta FL', 'FL', 'florida-mahjong.html', 'florida-mahjong-hub.html'),
    ('lantana-fl-mahjong.html', 'Lantana FL', 'FL', 'florida-mahjong.html', 'florida-mahjong-hub.html'),
    ('manalapan-fl-mahjong.html', 'Manalapan FL', 'FL', 'florida-mahjong.html', 'florida-mahjong-hub.html'),
    ('highland-beach-fl-mahjong.html', 'Highland Beach FL', 'FL', 'florida-mahjong.html', 'florida-mahjong-hub.html'),
    ('deerfield-beach-fl-7-mahjong.html', 'Deerfield Beach FL', 'FL', 'florida-mahjong.html', 'florida-mahjong-hub.html'),
    ('lauderdale-by-the-sea-fl-mahjong.html', 'Lauderdale-by-the-Sea FL', 'FL', 'florida-mahjong.html', 'florida-mahjong-hub.html'),
    ('sea-ranch-lakes-fl-mahjong.html', 'Sea Ranch Lakes FL', 'FL', 'florida-mahjong.html', 'florida-mahjong-hub.html'),
    ('pembroke-pines-fl-fl-mahjong.html', 'Pembroke Pines FL', 'FL', 'florida-mahjong.html', 'florida-mahjong-hub.html'),
    ('miramar-fl-mahjong.html', 'Miramar FL', 'FL', 'florida-mahjong.html', 'florida-mahjong-hub.html'),
    ('cooper-city-fl-mahjong.html', 'Cooper City FL', 'FL', 'florida-mahjong.html', 'florida-mahjong-hub.html'),
    ('davie-fl-6-mahjong.html', 'Davie FL', 'FL', 'florida-mahjong.html', 'florida-mahjong-hub.html'),
    ('plantation-fl-mahjong.html', 'Plantation FL', 'FL', 'florida-mahjong.html', 'florida-mahjong-hub.html'),
    ('sunrise-fl-4-mahjong.html', 'Sunrise FL', 'FL', 'florida-mahjong.html', 'florida-mahjong-hub.html'),
    ('coral-springs-fl-6-mahjong.html', 'Coral Springs FL', 'FL', 'florida-mahjong.html', 'florida-mahjong-hub.html'),
    ('parkland-fl-mahjong.html', 'Parkland FL', 'FL', 'florida-mahjong.html', 'florida-mahjong-hub.html'),
    ('margate-fl-mahjong.html', 'Margate FL', 'FL', 'florida-mahjong.html', 'florida-mahjong-hub.html'),
    ('tamarac-fl-mahjong.html', 'Tamarac FL', 'FL', 'florida-mahjong.html', 'florida-mahjong-hub.html'),
    ('north-port-fl-mahjong.html', 'North Port FL', 'FL', 'florida-mahjong.html', 'florida-mahjong-hub.html'),
    ('venice-fl-fl-mahjong.html', 'Venice FL', 'FL', 'florida-mahjong.html', 'florida-mahjong-hub.html'),
    ('englewood-fl-mahjong.html', 'Englewood FL', 'FL', 'florida-mahjong.html', 'florida-mahjong-hub.html'),
    ('punta-gorda-fl-fl-mahjong.html', 'Punta Gorda FL', 'FL', 'florida-mahjong.html', 'florida-mahjong-hub.html'),
    ('port-charlotte-fl-mahjong.html', 'Port Charlotte FL', 'FL', 'florida-mahjong.html', 'florida-mahjong-hub.html'),
    ('placida-fl-mahjong.html', 'Placida FL', 'FL', 'florida-mahjong.html', 'florida-mahjong-hub.html'),
    ('boca-grande-fl-mahjong.html', 'Boca Grande FL', 'FL', 'florida-mahjong.html', 'florida-mahjong-hub.html'),
    ('captiva-fl-mahjong.html', 'Captiva FL', 'FL', 'florida-mahjong.html', 'florida-mahjong-hub.html'),
    ('sanibel-fl-mahjong.html', 'Sanibel FL', 'FL', 'florida-mahjong.html', 'florida-mahjong-hub.html'),
    ('estero-fl-mahjong.html', 'Estero FL', 'FL', 'florida-mahjong.html', 'florida-mahjong-hub.html'),
    ('bonita-springs-fl-fl-mahjong.html', 'Bonita Springs FL', 'FL', 'florida-mahjong.html', 'florida-mahjong-hub.html'),
    ('marco-island-fl-fl-mahjong.html', 'Marco Island FL', 'FL', 'florida-mahjong.html', 'florida-mahjong-hub.html'),
    ('immokalee-fl-mahjong.html', 'Immokalee FL', 'FL', 'florida-mahjong.html', 'florida-mahjong-hub.html'),
    ('labelle-fl-mahjong.html', 'LaBelle FL', 'FL', 'florida-mahjong.html', 'florida-mahjong-hub.html'),
    ('clewiston-fl-mahjong.html', 'Clewiston FL', 'FL', 'florida-mahjong.html', 'florida-mahjong-hub.html'),
    ('belle-glade-fl-mahjong.html', 'Belle Glade FL', 'FL', 'florida-mahjong.html', 'florida-mahjong-hub.html'),
    ('lake-placid-fl-mahjong.html', 'Lake Placid FL', 'FL', 'florida-mahjong.html', 'florida-mahjong-hub.html'),
    ('avon-park-fl-mahjong.html', 'Avon Park FL', 'FL', 'florida-mahjong.html', 'florida-mahjong-hub.html'),
    ('wellington-fl-4-mahjong.html', 'Wellington FL', 'FL', 'florida-mahjong.html', 'florida-mahjong-hub.html'),
    ('royal-palm-beach-fl-mahjong.html', 'Royal Palm Beach FL', 'FL', 'florida-mahjong.html', 'florida-mahjong-hub.html'),
    ('lake-worth-fl-mahjong.html', 'Lake Worth FL', 'FL', 'florida-mahjong.html', 'florida-mahjong-hub.html'),
    ('greenacres-fl-mahjong.html', 'Greenacres FL', 'FL', 'florida-mahjong.html', 'florida-mahjong-hub.html'),
    ('palm-springs-fl-mahjong.html', 'Palm Springs FL', 'FL', 'florida-mahjong.html', 'florida-mahjong-hub.html'),
    ('north-miami-fl-6-mahjong.html', 'North Miami FL', 'FL', 'florida-mahjong.html', 'florida-mahjong-hub.html'),
    ('coral-gables-fl-6-mahjong.html', 'Coral Gables FL', 'FL', 'florida-mahjong.html', 'florida-mahjong-hub.html'),
    ('hialeah-fl-mahjong.html', 'Hialeah FL', 'FL', 'florida-mahjong.html', 'florida-mahjong-hub.html'),
    ('doral-fl-6-mahjong.html', 'Doral FL', 'FL', 'florida-mahjong.html', 'florida-mahjong-hub.html'),
    ('cutler-bay-fl-mahjong.html', 'Cutler Bay FL', 'FL', 'florida-mahjong.html', 'florida-mahjong-hub.html'),
    ('homestead-fl-mahjong.html', 'Homestead FL', 'FL', 'florida-mahjong.html', 'florida-mahjong-hub.html'),
    ('winter-garden-fl-mahjong.html', 'Winter Garden FL', 'FL', 'florida-mahjong.html', 'florida-mahjong-hub.html'),
    ('ocoee-fl-mahjong.html', 'Ocoee FL', 'FL', 'florida-mahjong.html', 'florida-mahjong-hub.html'),
    ('altamonte-springs-fl-mahjong.html', 'Altamonte Springs FL', 'FL', 'florida-mahjong.html', 'florida-mahjong-hub.html'),
    ('kissimmee-fl-7-mahjong.html', 'Kissimmee FL', 'FL', 'florida-mahjong.html', 'florida-mahjong-hub.html'),
    ('st-cloud-fl-mahjong.html', 'St Cloud FL', 'FL', 'florida-mahjong.html', 'florida-mahjong-hub.html'),
    ('canton-ga-mahjong.html', 'Canton GA', 'GA', 'georgia-mahjong.html', 'georgia-mahjong-hub.html'),
    ('woodstock-ga-ga-mahjong.html', 'Woodstock GA', 'GA', 'georgia-mahjong.html', 'georgia-mahjong-hub.html'),
    ('cumming-ga-mahjong.html', 'Cumming GA', 'GA', 'georgia-mahjong.html', 'georgia-mahjong-hub.html'),
    ('dahlonega-ga-mahjong.html', 'Dahlonega GA', 'GA', 'georgia-mahjong.html', 'georgia-mahjong-hub.html'),
    ('blue-ridge-ga-mahjong.html', 'Blue Ridge GA', 'GA', 'georgia-mahjong.html', 'georgia-mahjong-hub.html'),
    ('helen-ga-mahjong.html', 'Helen GA', 'GA', 'georgia-mahjong.html', 'georgia-mahjong-hub.html'),
    ('clayton-ga-mahjong.html', 'Clayton GA', 'GA', 'georgia-mahjong.html', 'georgia-mahjong-hub.html'),
    ('hiawassee-ga-mahjong.html', 'Hiawassee GA', 'GA', 'georgia-mahjong.html', 'georgia-mahjong-hub.html'),
    ('blairsville-ga-mahjong.html', 'Blairsville GA', 'GA', 'georgia-mahjong.html', 'georgia-mahjong-hub.html'),
    ('jasper-ga-mahjong.html', 'Jasper GA', 'GA', 'georgia-mahjong.html', 'georgia-mahjong-hub.html'),
    ('dallas-ga-mahjong.html', 'Dallas GA', 'GA', 'georgia-mahjong.html', 'georgia-mahjong-hub.html'),
    ('douglasville-ga-mahjong.html', 'Douglasville GA', 'GA', 'georgia-mahjong.html', 'georgia-mahjong-hub.html'),
    ('newnan-ga-ga-mahjong.html', 'Newnan GA', 'GA', 'georgia-mahjong.html', 'georgia-mahjong-hub.html'),
    ('fayetteville-ga-mahjong.html', 'Fayetteville GA', 'GA', 'georgia-mahjong.html', 'georgia-mahjong-hub.html'),
    ('peachtree-city-ga-ga-mahjong.html', 'Peachtree City GA', 'GA', 'georgia-mahjong.html', 'georgia-mahjong-hub.html'),
    ('tyrone-ga-mahjong.html', 'Tyrone GA', 'GA', 'georgia-mahjong.html', 'georgia-mahjong-hub.html'),
    ('sharpsburg-ga-mahjong.html', 'Sharpsburg GA', 'GA', 'georgia-mahjong.html', 'georgia-mahjong-hub.html'),
    ('lagrange-ga-ga-mahjong.html', 'LaGrange GA', 'GA', 'georgia-mahjong.html', 'georgia-mahjong-hub.html'),
    ('americus-ga-mahjong.html', 'Americus GA', 'GA', 'georgia-mahjong.html', 'georgia-mahjong-hub.html'),
    ('cordele-ga-mahjong.html', 'Cordele GA', 'GA', 'georgia-mahjong.html', 'georgia-mahjong-hub.html'),
    ('valdosta-ga-ga-mahjong.html', 'Valdosta GA', 'GA', 'georgia-mahjong.html', 'georgia-mahjong-hub.html'),
    ('brunswick-ga-ga-mahjong.html', 'Brunswick GA', 'GA', 'georgia-mahjong.html', 'georgia-mahjong-hub.html'),
    ('jekyll-island-ga-ga-mahjong.html', 'Jekyll Island GA', 'GA', 'georgia-mahjong.html', 'georgia-mahjong-hub.html'),
    ('st-marys-ga-mahjong.html', 'St Marys GA', 'GA', 'georgia-mahjong.html', 'georgia-mahjong-hub.html'),
    ('vidalia-ga-mahjong.html', 'Vidalia GA', 'GA', 'georgia-mahjong.html', 'georgia-mahjong-hub.html'),
    ('dublin-ga-mahjong.html', 'Dublin GA', 'GA', 'georgia-mahjong.html', 'georgia-mahjong-hub.html'),
    ('swainsboro-ga-mahjong.html', 'Swainsboro GA', 'GA', 'georgia-mahjong.html', 'georgia-mahjong-hub.html'),
    ('elberton-ga-mahjong.html', 'Elberton GA', 'GA', 'georgia-mahjong.html', 'georgia-mahjong-hub.html'),
    ('hartwell-ga-mahjong.html', 'Hartwell GA', 'GA', 'georgia-mahjong.html', 'georgia-mahjong-hub.html'),
    ('washington-ga-mahjong.html', 'Washington GA', 'GA', 'georgia-mahjong.html', 'georgia-mahjong-hub.html'),
    ('thomson-ga-mahjong.html', 'Thomson GA', 'GA', 'georgia-mahjong.html', 'georgia-mahjong-hub.html'),
    ('madison-ga-mahjong.html', 'Madison GA', 'GA', 'georgia-mahjong.html', 'georgia-mahjong-hub.html'),
    ('eatonton-ga-mahjong.html', 'Eatonton GA', 'GA', 'georgia-mahjong.html', 'georgia-mahjong-hub.html'),
    ('monticello-ga-mahjong.html', 'Monticello GA', 'GA', 'georgia-mahjong.html', 'georgia-mahjong-hub.html'),
    ('social-circle-ga-mahjong.html', 'Social Circle GA', 'GA', 'georgia-mahjong.html', 'georgia-mahjong-hub.html'),
    ('covington-ga-mahjong.html', 'Covington GA', 'GA', 'georgia-mahjong.html', 'georgia-mahjong-hub.html'),
    ('monroe-ga-mahjong.html', 'Monroe GA', 'GA', 'georgia-mahjong.html', 'georgia-mahjong-hub.html'),
    ('loganville-ga-mahjong.html', 'Loganville GA', 'GA', 'georgia-mahjong.html', 'georgia-mahjong-hub.html'),
    ('snellville-ga-ga-mahjong.html', 'Snellville GA', 'GA', 'georgia-mahjong.html', 'georgia-mahjong-hub.html'),
    ('lilburn-ga-mahjong.html', 'Lilburn GA', 'GA', 'georgia-mahjong.html', 'georgia-mahjong-hub.html'),
    ('stone-mountain-ga-mahjong.html', 'Stone Mountain GA', 'GA', 'georgia-mahjong.html', 'georgia-mahjong-hub.html'),
    ('tucker-ga-mahjong.html', 'Tucker GA', 'GA', 'georgia-mahjong.html', 'georgia-mahjong-hub.html'),
    ('decatur-ga-ga-mahjong.html', 'Decatur GA', 'GA', 'georgia-mahjong.html', 'georgia-mahjong-hub.html'),
    ('brookhaven-ga-mahjong.html', 'Brookhaven GA', 'GA', 'georgia-mahjong.html', 'georgia-mahjong-hub.html'),
    ('chamblee-ga-mahjong.html', 'Chamblee GA', 'GA', 'georgia-mahjong.html', 'georgia-mahjong-hub.html'),
    ('doraville-ga-mahjong.html', 'Doraville GA', 'GA', 'georgia-mahjong.html', 'georgia-mahjong-hub.html'),
    ('roswell-ga-ga-mahjong.html', 'Roswell GA', 'GA', 'georgia-mahjong.html', 'georgia-mahjong-hub.html'),
    ('marietta-ga-7-mahjong.html', 'Marietta GA', 'GA', 'georgia-mahjong.html', 'georgia-mahjong-hub.html'),
    ('kennesaw-ga-ga-mahjong.html', 'Kennesaw GA', 'GA', 'georgia-mahjong.html', 'georgia-mahjong-hub.html'),
    ('acworth-ga-mahjong.html', 'Acworth GA', 'GA', 'georgia-mahjong.html', 'georgia-mahjong-hub.html'),
    ('cartersville-ga-mahjong.html', 'Cartersville GA', 'GA', 'georgia-mahjong.html', 'georgia-mahjong-hub.html'),
    ('rome-ga-ga-mahjong.html', 'Rome GA', 'GA', 'georgia-mahjong.html', 'georgia-mahjong-hub.html'),
    ('calhoun-ga-mahjong.html', 'Calhoun GA', 'GA', 'georgia-mahjong.html', 'georgia-mahjong-hub.html'),
    ('dalton-ga-ga-mahjong.html', 'Dalton GA', 'GA', 'georgia-mahjong.html', 'georgia-mahjong-hub.html'),
    ('chatsworth-ga-mahjong.html', 'Chatsworth GA', 'GA', 'georgia-mahjong.html', 'georgia-mahjong-hub.html'),
    ('cleveland-ga-mahjong.html', 'Cleveland GA', 'GA', 'georgia-mahjong.html', 'georgia-mahjong-hub.html'),
    ('dunwoody-ga-mahjong.html', 'Dunwoody GA', 'GA', 'georgia-mahjong.html', 'georgia-mahjong-hub.html'),
    ('sandy-springs-ga-mahjong.html', 'Sandy Springs GA', 'GA', 'georgia-mahjong.html', 'georgia-mahjong-hub.html'),
    ('johns-creek-ga-6-mahjong.html', 'Johns Creek GA', 'GA', 'georgia-mahjong.html', 'georgia-mahjong-hub.html'),
    ('milton-ga-mahjong.html', 'Milton GA', 'GA', 'georgia-mahjong.html', 'georgia-mahjong-hub.html'),
    ('peachtree-corners-ga-mahjong.html', 'Peachtree Corners GA', 'GA', 'georgia-mahjong.html', 'georgia-mahjong-hub.html'),
    ('sugar-hill-ga-mahjong.html', 'Sugar Hill GA', 'GA', 'georgia-mahjong.html', 'georgia-mahjong-hub.html'),
    ('winder-ga-mahjong.html', 'Winder GA', 'GA', 'georgia-mahjong.html', 'georgia-mahjong-hub.html'),
    ('conyers-ga-mahjong.html', 'Conyers GA', 'GA', 'georgia-mahjong.html', 'georgia-mahjong-hub.html'),
    ('stockbridge-ga-mahjong.html', 'Stockbridge GA', 'GA', 'georgia-mahjong.html', 'georgia-mahjong-hub.html'),
    ('mcdonough-ga-mahjong.html', 'McDonough GA', 'GA', 'georgia-mahjong.html', 'georgia-mahjong-hub.html'),
    ('griffin-ga-mahjong.html', 'Griffin GA', 'GA', 'georgia-mahjong.html', 'georgia-mahjong-hub.html'),
    ('thomasville-ga-mahjong.html', 'Thomasville GA', 'GA', 'georgia-mahjong.html', 'georgia-mahjong-hub.html'),
    ('statesboro-ga-ga-mahjong.html', 'Statesboro GA', 'GA', 'georgia-mahjong.html', 'georgia-mahjong-hub.html'),
    ('waycross-ga-mahjong.html', 'Waycross GA', 'GA', 'georgia-mahjong.html', 'georgia-mahjong-hub.html'),
    ('milledgeville-ga-mahjong.html', 'Milledgeville GA', 'GA', 'georgia-mahjong.html', 'georgia-mahjong-hub.html'),
    ('toccoa-ga-mahjong.html', 'Toccoa GA', 'GA', 'georgia-mahjong.html', 'georgia-mahjong-hub.html'),
    ('danville-ky-ky-mahjong.html', 'Danville KY', 'KY', 'kentucky-mahjong.html', 'kentucky-mahjong-hub.html'),
    ('bardstown-ky-ky-mahjong.html', 'Bardstown KY', 'KY', 'kentucky-mahjong.html', 'kentucky-mahjong-hub.html'),
    ('shelbyville-ky-ky-mahjong.html', 'Shelbyville KY', 'KY', 'kentucky-mahjong.html', 'kentucky-mahjong-hub.html'),
    ('la-grange-ky-mahjong.html', 'La Grange KY', 'KY', 'kentucky-mahjong.html', 'kentucky-mahjong-hub.html'),
    ('prospect-ky-mahjong.html', 'Prospect KY', 'KY', 'kentucky-mahjong.html', 'kentucky-mahjong-hub.html'),
    ('anchorage-ky-mahjong.html', 'Anchorage KY', 'KY', 'kentucky-mahjong.html', 'kentucky-mahjong-hub.html'),
    ('st-matthews-ky-mahjong.html', 'St Matthews KY', 'KY', 'kentucky-mahjong.html', 'kentucky-mahjong-hub.html'),
    ('jeffersontown-ky-mahjong.html', 'Jeffersontown KY', 'KY', 'kentucky-mahjong.html', 'kentucky-mahjong-hub.html'),
    ('mount-washington-ky-mahjong.html', 'Mount Washington KY', 'KY', 'kentucky-mahjong.html', 'kentucky-mahjong-hub.html'),
    ('shepherdsville-ky-mahjong.html', 'Shepherdsville KY', 'KY', 'kentucky-mahjong.html', 'kentucky-mahjong-hub.html'),
    ('elizabethtown-ky-ky-mahjong.html', 'Elizabethtown KY', 'KY', 'kentucky-mahjong.html', 'kentucky-mahjong-hub.html'),
    ('radcliff-ky-mahjong.html', 'Radcliff KY', 'KY', 'kentucky-mahjong.html', 'kentucky-mahjong-hub.html'),
    ('campbellsville-ky-mahjong.html', 'Campbellsville KY', 'KY', 'kentucky-mahjong.html', 'kentucky-mahjong-hub.html'),
    ('somerset-ky-ky-mahjong.html', 'Somerset KY', 'KY', 'kentucky-mahjong.html', 'kentucky-mahjong-hub.html'),
    ('london-ky-mahjong.html', 'London KY', 'KY', 'kentucky-mahjong.html', 'kentucky-mahjong-hub.html'),
    ('corbin-ky-mahjong.html', 'Corbin KY', 'KY', 'kentucky-mahjong.html', 'kentucky-mahjong-hub.html'),
    ('williamsburg-ky-mahjong.html', 'Williamsburg KY', 'KY', 'kentucky-mahjong.html', 'kentucky-mahjong-hub.html'),
    ('barbourville-ky-mahjong.html', 'Barbourville KY', 'KY', 'kentucky-mahjong.html', 'kentucky-mahjong-hub.html'),
    ('middlesboro-ky-mahjong.html', 'Middlesboro KY', 'KY', 'kentucky-mahjong.html', 'kentucky-mahjong-hub.html'),
    ('pikeville-ky-mahjong.html', 'Pikeville KY', 'KY', 'kentucky-mahjong.html', 'kentucky-mahjong-hub.html'),
    ('prestonsburg-ky-mahjong.html', 'Prestonsburg KY', 'KY', 'kentucky-mahjong.html', 'kentucky-mahjong-hub.html'),
    ('paintsville-ky-mahjong.html', 'Paintsville KY', 'KY', 'kentucky-mahjong.html', 'kentucky-mahjong-hub.html'),
    ('ashland-ky-ky-mahjong.html', 'Ashland KY', 'KY', 'kentucky-mahjong.html', 'kentucky-mahjong-hub.html'),
    ('morehead-ky-mahjong.html', 'Morehead KY', 'KY', 'kentucky-mahjong.html', 'kentucky-mahjong-hub.html'),
    ('maysville-ky-ky-mahjong.html', 'Maysville KY', 'KY', 'kentucky-mahjong.html', 'kentucky-mahjong-hub.html'),
    ('winchester-ky-ky-mahjong.html', 'Winchester KY', 'KY', 'kentucky-mahjong.html', 'kentucky-mahjong-hub.html'),
    ('richmond-ky-ky-mahjong.html', 'Richmond KY', 'KY', 'kentucky-mahjong.html', 'kentucky-mahjong-hub.html'),
    ('berea-ky-mahjong.html', 'Berea KY', 'KY', 'kentucky-mahjong.html', 'kentucky-mahjong-hub.html'),
    ('nicholasville-ky-ky-mahjong.html', 'Nicholasville KY', 'KY', 'kentucky-mahjong.html', 'kentucky-mahjong-hub.html'),
    ('wilmore-ky-mahjong.html', 'Wilmore KY', 'KY', 'kentucky-mahjong.html', 'kentucky-mahjong-hub.html'),
    ('harrodsburg-ky-mahjong.html', 'Harrodsburg KY', 'KY', 'kentucky-mahjong.html', 'kentucky-mahjong-hub.html'),
    ('frankfort-ky-ky-mahjong.html', 'Frankfort KY', 'KY', 'kentucky-mahjong.html', 'kentucky-mahjong-hub.html'),
    ('paris-ky-mahjong.html', 'Paris KY', 'KY', 'kentucky-mahjong.html', 'kentucky-mahjong-hub.html'),
    ('georgetown-ky-ky-mahjong.html', 'Georgetown KY', 'KY', 'kentucky-mahjong.html', 'kentucky-mahjong-hub.html'),
    ('cynthiana-ky-mahjong.html', 'Cynthiana KY', 'KY', 'kentucky-mahjong.html', 'kentucky-mahjong-hub.html'),
    ('murray-ky-ky-mahjong.html', 'Murray KY', 'KY', 'kentucky-mahjong.html', 'kentucky-mahjong-hub.html'),
    ('mayfield-ky-mahjong.html', 'Mayfield KY', 'KY', 'kentucky-mahjong.html', 'kentucky-mahjong-hub.html'),
    ('paducah-ky-ky-mahjong.html', 'Paducah KY', 'KY', 'kentucky-mahjong.html', 'kentucky-mahjong-hub.html'),
    ('hopkinsville-ky-ky-mahjong.html', 'Hopkinsville KY', 'KY', 'kentucky-mahjong.html', 'kentucky-mahjong-hub.html'),
    ('madisonville-ky-ky-mahjong.html', 'Madisonville KY', 'KY', 'kentucky-mahjong.html', 'kentucky-mahjong-hub.html'),
    ('owensboro-ky-ky-mahjong.html', 'Owensboro KY', 'KY', 'kentucky-mahjong.html', 'kentucky-mahjong-hub.html'),
    ('henderson-ky-ky-mahjong.html', 'Henderson KY', 'KY', 'kentucky-mahjong.html', 'kentucky-mahjong-hub.html'),
    ('bowling-green-ky-ky-mahjong.html', 'Bowling Green KY', 'KY', 'kentucky-mahjong.html', 'kentucky-mahjong-hub.html'),
    ('georgetown-ky-2-mahjong.html', 'Georgetown KY', 'KY', 'kentucky-mahjong.html', 'kentucky-mahjong-hub.html'),
    ('florence-ky-ky-mahjong.html', 'Florence KY', 'KY', 'kentucky-mahjong.html', 'kentucky-mahjong-hub.html'),
    ('covington-ky-ky-mahjong.html', 'Covington KY', 'KY', 'kentucky-mahjong.html', 'kentucky-mahjong-hub.html'),
    ('newport-ky-mahjong.html', 'Newport KY', 'KY', 'kentucky-mahjong.html', 'kentucky-mahjong-hub.html'),
    ('mandeville-la-mahjong.html', 'Mandeville LA', 'LA', 'louisiana-mahjong.html', 'louisiana-mahjong-hub.html'),
    ('covington-la-mahjong.html', 'Covington LA', 'LA', 'louisiana-mahjong.html', 'louisiana-mahjong-hub.html'),
    ('slidell-la-la-mahjong.html', 'Slidell LA', 'LA', 'louisiana-mahjong.html', 'louisiana-mahjong-hub.html'),
    ('hammond-la-la-mahjong.html', 'Hammond LA', 'LA', 'louisiana-mahjong.html', 'louisiana-mahjong-hub.html'),
    ('ponchatoula-la-mahjong.html', 'Ponchatoula LA', 'LA', 'louisiana-mahjong.html', 'louisiana-mahjong-hub.html'),
    ('houma-la-la-mahjong.html', 'Houma LA', 'LA', 'louisiana-mahjong.html', 'louisiana-mahjong-hub.html'),
    ('thibodaux-la-la-mahjong.html', 'Thibodaux LA', 'LA', 'louisiana-mahjong.html', 'louisiana-mahjong-hub.html'),
    ('morgan-city-la-mahjong.html', 'Morgan City LA', 'LA', 'louisiana-mahjong.html', 'louisiana-mahjong-hub.html'),
    ('franklin-la-mahjong.html', 'Franklin LA', 'LA', 'louisiana-mahjong.html', 'louisiana-mahjong-hub.html'),
    ('abbeville-la-la-mahjong.html', 'Abbeville LA', 'LA', 'louisiana-mahjong.html', 'louisiana-mahjong-hub.html'),
    ('jennings-la-mahjong.html', 'Jennings LA', 'LA', 'louisiana-mahjong.html', 'louisiana-mahjong-hub.html'),
    ('sulphur-la-la-mahjong.html', 'Sulphur LA', 'LA', 'louisiana-mahjong.html', 'louisiana-mahjong-hub.html'),
    ('westlake-la-mahjong.html', 'Westlake LA', 'LA', 'louisiana-mahjong.html', 'louisiana-mahjong-hub.html'),
    ('deridder-la-mahjong.html', 'DeRidder LA', 'LA', 'louisiana-mahjong.html', 'louisiana-mahjong-hub.html'),
    ('leesville-la-mahjong.html', 'Leesville LA', 'LA', 'louisiana-mahjong.html', 'louisiana-mahjong-hub.html'),
    ('natchitoches-la-la-mahjong.html', 'Natchitoches LA', 'LA', 'louisiana-mahjong.html', 'louisiana-mahjong-hub.html'),
    ('ruston-la-la-mahjong.html', 'Ruston LA', 'LA', 'louisiana-mahjong.html', 'louisiana-mahjong-hub.html'),
    ('monroe-la-la-mahjong.html', 'Monroe LA', 'LA', 'louisiana-mahjong.html', 'louisiana-mahjong-hub.html'),
    ('west-monroe-la-mahjong.html', 'West Monroe LA', 'LA', 'louisiana-mahjong.html', 'louisiana-mahjong-hub.html'),
    ('bastrop-la-mahjong.html', 'Bastrop LA', 'LA', 'louisiana-mahjong.html', 'louisiana-mahjong-hub.html'),
    ('minden-la-la-mahjong.html', 'Minden LA', 'LA', 'louisiana-mahjong.html', 'louisiana-mahjong-hub.html'),
    ('bossier-city-la-la-mahjong.html', 'Bossier City LA', 'LA', 'louisiana-mahjong.html', 'louisiana-mahjong-hub.html'),
    ('shreveport-la-la-mahjong.html', 'Shreveport LA', 'LA', 'louisiana-mahjong.html', 'louisiana-mahjong-hub.html'),
    ('alexandria-la-7-mahjong.html', 'Alexandria LA', 'LA', 'louisiana-mahjong.html', 'louisiana-mahjong-hub.html'),
    ('pineville-la-la-mahjong.html', 'Pineville LA', 'LA', 'louisiana-mahjong.html', 'louisiana-mahjong-hub.html'),
    ('marksville-la-mahjong.html', 'Marksville LA', 'LA', 'louisiana-mahjong.html', 'louisiana-mahjong-hub.html'),
    ('opelousas-la-la-mahjong.html', 'Opelousas LA', 'LA', 'louisiana-mahjong.html', 'louisiana-mahjong-hub.html'),
    ('crowley-la-la-mahjong.html', 'Crowley LA', 'LA', 'louisiana-mahjong.html', 'louisiana-mahjong-hub.html'),
    ('lafayette-la-7-mahjong.html', 'Lafayette LA', 'LA', 'louisiana-mahjong.html', 'louisiana-mahjong-hub.html'),
    ('youngsville-la-mahjong.html', 'Youngsville LA', 'LA', 'louisiana-mahjong.html', 'louisiana-mahjong-hub.html'),
    ('broussard-la-mahjong.html', 'Broussard LA', 'LA', 'louisiana-mahjong.html', 'louisiana-mahjong-hub.html'),
    ('scott-la-mahjong.html', 'Scott LA', 'LA', 'louisiana-mahjong.html', 'louisiana-mahjong-hub.html'),
    ('breaux-bridge-la-mahjong.html', 'Breaux Bridge LA', 'LA', 'louisiana-mahjong.html', 'louisiana-mahjong-hub.html'),
    ('st-martinville-la-mahjong.html', 'St Martinville LA', 'LA', 'louisiana-mahjong.html', 'louisiana-mahjong-hub.html'),
    ('new-iberia-la-mahjong.html', 'New Iberia LA', 'LA', 'louisiana-mahjong.html', 'louisiana-mahjong-hub.html'),
    ('donaldsonville-la-mahjong.html', 'Donaldsonville LA', 'LA', 'louisiana-mahjong.html', 'louisiana-mahjong-hub.html'),
    ('plaquemine-la-mahjong.html', 'Plaquemine LA', 'LA', 'louisiana-mahjong.html', 'louisiana-mahjong-hub.html'),
    ('gonzales-la-mahjong.html', 'Gonzales LA', 'LA', 'louisiana-mahjong.html', 'louisiana-mahjong-hub.html'),
    ('denham-springs-la-mahjong.html', 'Denham Springs LA', 'LA', 'louisiana-mahjong.html', 'louisiana-mahjong-hub.html'),
    ('walker-la-mahjong.html', 'Walker LA', 'LA', 'louisiana-mahjong.html', 'louisiana-mahjong-hub.html'),
    ('zachary-la-la-mahjong.html', 'Zachary LA', 'LA', 'louisiana-mahjong.html', 'louisiana-mahjong-hub.html'),
    ('central-la-mahjong.html', 'Central LA', 'LA', 'louisiana-mahjong.html', 'louisiana-mahjong-hub.html'),
    ('baker-la-mahjong.html', 'Baker LA', 'LA', 'louisiana-mahjong.html', 'louisiana-mahjong-hub.html'),
    ('port-allen-la-mahjong.html', 'Port Allen LA', 'LA', 'louisiana-mahjong.html', 'louisiana-mahjong-hub.html'),
    ('brusly-la-mahjong.html', 'Brusly LA', 'LA', 'louisiana-mahjong.html', 'louisiana-mahjong-hub.html'),
    ('st-francisville-la-mahjong.html', 'St Francisville LA', 'LA', 'louisiana-mahjong.html', 'louisiana-mahjong-hub.html'),
    ('metairie-la-la-mahjong.html', 'Metairie LA', 'LA', 'louisiana-mahjong.html', 'louisiana-mahjong-hub.html'),
    ('kenner-la-5-mahjong.html', 'Kenner LA', 'LA', 'louisiana-mahjong.html', 'louisiana-mahjong-hub.html'),
    ('lake-charles-la-la-mahjong.html', 'Lake Charles LA', 'LA', 'louisiana-mahjong.html', 'louisiana-mahjong-hub.html'),
    ('ocean-springs-ms-ms-mahjong.html', 'Ocean Springs MS', 'MS', 'mississippi-mahjong.html', 'mississippi-mahjong-hub.html'),
    ('gautier-ms-mahjong.html', 'Gautier MS', 'MS', 'mississippi-mahjong.html', 'mississippi-mahjong-hub.html'),
    ('pascagoula-ms-ms-mahjong.html', 'Pascagoula MS', 'MS', 'mississippi-mahjong.html', 'mississippi-mahjong-hub.html'),
    ('long-beach-ms-mahjong.html', 'Long Beach MS', 'MS', 'mississippi-mahjong.html', 'mississippi-mahjong-hub.html'),
    ('pass-christian-ms-ms-mahjong.html', 'Pass Christian MS', 'MS', 'mississippi-mahjong.html', 'mississippi-mahjong-hub.html'),
    ('bay-st-louis-ms-ms-mahjong.html', 'Bay St Louis MS', 'MS', 'mississippi-mahjong.html', 'mississippi-mahjong-hub.html'),
    ('waveland-ms-mahjong.html', 'Waveland MS', 'MS', 'mississippi-mahjong.html', 'mississippi-mahjong-hub.html'),
    ('diamondhead-ms-mahjong.html', 'Diamondhead MS', 'MS', 'mississippi-mahjong.html', 'mississippi-mahjong-hub.html'),
    ('diberville-ms-mahjong.html', "D'Iberville MS", 'MS', 'mississippi-mahjong.html', 'mississippi-mahjong-hub.html'),
    ('gulfport-ms-5-mahjong.html', 'Gulfport MS', 'MS', 'mississippi-mahjong.html', 'mississippi-mahjong-hub.html'),
    ('starkville-ms-ms-mahjong.html', 'Starkville MS', 'MS', 'mississippi-mahjong.html', 'mississippi-mahjong-hub.html'),
    ('west-point-ms-mahjong.html', 'West Point MS', 'MS', 'mississippi-mahjong.html', 'mississippi-mahjong-hub.html'),
    ('columbus-ms-ms-ms-mahjong.html', 'Columbus MS', 'MS', 'mississippi-mahjong.html', 'mississippi-mahjong-hub.html'),
    ('philadelphia-ms-mahjong.html', 'Philadelphia MS', 'MS', 'mississippi-mahjong.html', 'mississippi-mahjong-hub.html'),
    ('meridian-ms-ms-mahjong.html', 'Meridian MS', 'MS', 'mississippi-mahjong.html', 'mississippi-mahjong-hub.html'),
    ('laurel-ms-mahjong.html', 'Laurel MS', 'MS', 'mississippi-mahjong.html', 'mississippi-mahjong-hub.html'),
    ('hattiesburg-ms-5-mahjong.html', 'Hattiesburg MS', 'MS', 'mississippi-mahjong.html', 'mississippi-mahjong-hub.html'),
    ('petal-ms-mahjong.html', 'Petal MS', 'MS', 'mississippi-mahjong.html', 'mississippi-mahjong-hub.html'),
    ('purvis-ms-mahjong.html', 'Purvis MS', 'MS', 'mississippi-mahjong.html', 'mississippi-mahjong-hub.html'),
    ('poplarville-ms-mahjong.html', 'Poplarville MS', 'MS', 'mississippi-mahjong.html', 'mississippi-mahjong-hub.html'),
    ('wiggins-ms-mahjong.html', 'Wiggins MS', 'MS', 'mississippi-mahjong.html', 'mississippi-mahjong-hub.html'),
    ('lucedale-ms-mahjong.html', 'Lucedale MS', 'MS', 'mississippi-mahjong.html', 'mississippi-mahjong-hub.html'),
    ('moss-point-ms-mahjong.html', 'Moss Point MS', 'MS', 'mississippi-mahjong.html', 'mississippi-mahjong-hub.html'),
    ('corinth-ms-ms-mahjong.html', 'Corinth MS', 'MS', 'mississippi-mahjong.html', 'mississippi-mahjong-hub.html'),
    ('booneville-ms-mahjong.html', 'Booneville MS', 'MS', 'mississippi-mahjong.html', 'mississippi-mahjong-hub.html'),
    ('new-albany-ms-mahjong.html', 'New Albany MS', 'MS', 'mississippi-mahjong.html', 'mississippi-mahjong-hub.html'),
    ('oxford-ms-ms-mahjong.html', 'Oxford MS', 'MS', 'mississippi-mahjong.html', 'mississippi-mahjong-hub.html'),
    ('batesville-ms-mahjong.html', 'Batesville MS', 'MS', 'mississippi-mahjong.html', 'mississippi-mahjong-hub.html'),
    ('clarksdale-ms-ms-mahjong.html', 'Clarksdale MS', 'MS', 'mississippi-mahjong.html', 'mississippi-mahjong-hub.html'),
    ('greenville-ms-ms-ms-mahjong.html', 'Greenville MS', 'MS', 'mississippi-mahjong.html', 'mississippi-mahjong-hub.html'),
    ('cleveland-ms-ms-ms-mahjong.html', 'Cleveland MS', 'MS', 'mississippi-mahjong.html', 'mississippi-mahjong-hub.html'),
    ('indianola-ms-ms-mahjong.html', 'Indianola MS', 'MS', 'mississippi-mahjong.html', 'mississippi-mahjong-hub.html'),
    ('yazoo-city-ms-mahjong.html', 'Yazoo City MS', 'MS', 'mississippi-mahjong.html', 'mississippi-mahjong-hub.html'),
    ('ridgeland-ms-mahjong.html', 'Ridgeland MS', 'MS', 'mississippi-mahjong.html', 'mississippi-mahjong-hub.html'),
    ('madison-ms-ms-mahjong.html', 'Madison MS', 'MS', 'mississippi-mahjong.html', 'mississippi-mahjong-hub.html'),
    ('brandon-ms-mahjong.html', 'Brandon MS', 'MS', 'mississippi-mahjong.html', 'mississippi-mahjong-hub.html'),
    ('pearl-ms-mahjong.html', 'Pearl MS', 'MS', 'mississippi-mahjong.html', 'mississippi-mahjong-hub.html'),
    ('clinton-ms-ms-mahjong.html', 'Clinton MS', 'MS', 'mississippi-mahjong.html', 'mississippi-mahjong-hub.html'),
    ('flowood-ms-mahjong.html', 'Flowood MS', 'MS', 'mississippi-mahjong.html', 'mississippi-mahjong-hub.html'),
    ('canton-ms-ms-mahjong.html', 'Canton MS', 'MS', 'mississippi-mahjong.html', 'mississippi-mahjong-hub.html'),
    ('brookhaven-ms-ms-mahjong.html', 'Brookhaven MS', 'MS', 'mississippi-mahjong.html', 'mississippi-mahjong-hub.html'),
    ('mccomb-ms-ms-mahjong.html', 'McComb MS', 'MS', 'mississippi-mahjong.html', 'mississippi-mahjong-hub.html'),
    ('biloxi-ms-ms-mahjong.html', 'Biloxi MS', 'MS', 'mississippi-mahjong.html', 'mississippi-mahjong-hub.html'),
    ('tupelo-ms-ms-mahjong.html', 'Tupelo MS', 'MS', 'mississippi-mahjong.html', 'mississippi-mahjong-hub.html'),
    ('greenville-ms-mahjong.html', 'Greenville MS', 'MS', 'mississippi-mahjong.html', 'mississippi-mahjong-hub.html'),
    ('columbus-ms-mahjong.html', 'Columbus MS', 'MS', 'mississippi-mahjong.html', 'mississippi-mahjong-hub.html'),
    ('vicksburg-ms-ms-mahjong.html', 'Vicksburg MS', 'MS', 'mississippi-mahjong.html', 'mississippi-mahjong-hub.html'),
    ('natchez-ms-ms-mahjong.html', 'Natchez MS', 'MS', 'mississippi-mahjong.html', 'mississippi-mahjong-hub.html'),
    ('picayune-ms-ms-mahjong.html', 'Picayune MS', 'MS', 'mississippi-mahjong.html', 'mississippi-mahjong-hub.html'),
    ('southern-pines-nc-mahjong.html', 'Southern Pines NC', 'NC', 'north-carolina-mahjong.html', 'north-carolina-mahjong-hub.html'),
    ('pinehurst-nc-mahjong.html', 'Pinehurst NC', 'NC', 'north-carolina-mahjong.html', 'north-carolina-mahjong-hub.html'),
    ('aberdeen-nc-mahjong.html', 'Aberdeen NC', 'NC', 'north-carolina-mahjong.html', 'north-carolina-mahjong-hub.html'),
    ('sanford-nc-mahjong.html', 'Sanford NC', 'NC', 'north-carolina-mahjong.html', 'north-carolina-mahjong-hub.html'),
    ('lillington-nc-mahjong.html', 'Lillington NC', 'NC', 'north-carolina-mahjong.html', 'north-carolina-mahjong-hub.html'),
    ('smithfield-nc-mahjong.html', 'Smithfield NC', 'NC', 'north-carolina-mahjong.html', 'north-carolina-mahjong-hub.html'),
    ('selma-nc-mahjong.html', 'Selma NC', 'NC', 'north-carolina-mahjong.html', 'north-carolina-mahjong-hub.html'),
    ('goldsboro-nc-nc-mahjong.html', 'Goldsboro NC', 'NC', 'north-carolina-mahjong.html', 'north-carolina-mahjong-hub.html'),
    ('kinston-nc-nc-mahjong.html', 'Kinston NC', 'NC', 'north-carolina-mahjong.html', 'north-carolina-mahjong-hub.html'),
    ('new-bern-nc-nc-mahjong.html', 'New Bern NC', 'NC', 'north-carolina-mahjong.html', 'north-carolina-mahjong-hub.html'),
    ('havelock-nc-mahjong.html', 'Havelock NC', 'NC', 'north-carolina-mahjong.html', 'north-carolina-mahjong-hub.html'),
    ('morehead-city-nc-mahjong.html', 'Morehead City NC', 'NC', 'north-carolina-mahjong.html', 'north-carolina-mahjong-hub.html'),
    ('beaufort-nc-mahjong.html', 'Beaufort NC', 'NC', 'north-carolina-mahjong.html', 'north-carolina-mahjong-hub.html'),
    ('atlantic-beach-nc-mahjong.html', 'Atlantic Beach NC', 'NC', 'north-carolina-mahjong.html', 'north-carolina-mahjong-hub.html'),
    ('emerald-isle-nc-mahjong.html', 'Emerald Isle NC', 'NC', 'north-carolina-mahjong.html', 'north-carolina-mahjong-hub.html'),
    ('swansboro-nc-mahjong.html', 'Swansboro NC', 'NC', 'north-carolina-mahjong.html', 'north-carolina-mahjong-hub.html'),
    ('jacksonville-nc-7-mahjong.html', 'Jacksonville NC', 'NC', 'north-carolina-mahjong.html', 'north-carolina-mahjong-hub.html'),
    ('lumberton-nc-nc-mahjong.html', 'Lumberton NC', 'NC', 'north-carolina-mahjong.html', 'north-carolina-mahjong-hub.html'),
    ('whiteville-nc-mahjong.html', 'Whiteville NC', 'NC', 'north-carolina-mahjong.html', 'north-carolina-mahjong-hub.html'),
    ('southport-nc-mahjong.html', 'Southport NC', 'NC', 'north-carolina-mahjong.html', 'north-carolina-mahjong-hub.html'),
    ('oak-island-nc-mahjong.html', 'Oak Island NC', 'NC', 'north-carolina-mahjong.html', 'north-carolina-mahjong-hub.html'),
    ('sunset-beach-nc-mahjong.html', 'Sunset Beach NC', 'NC', 'north-carolina-mahjong.html', 'north-carolina-mahjong-hub.html'),
    ('calabash-nc-mahjong.html', 'Calabash NC', 'NC', 'north-carolina-mahjong.html', 'north-carolina-mahjong-hub.html'),
    ('shallotte-nc-mahjong.html', 'Shallotte NC', 'NC', 'north-carolina-mahjong.html', 'north-carolina-mahjong-hub.html'),
    ('elizabethtown-nc-mahjong.html', 'Elizabethtown NC', 'NC', 'north-carolina-mahjong.html', 'north-carolina-mahjong-hub.html'),
    ('laurinburg-nc-mahjong.html', 'Laurinburg NC', 'NC', 'north-carolina-mahjong.html', 'north-carolina-mahjong-hub.html'),
    ('rockingham-nc-mahjong.html', 'Rockingham NC', 'NC', 'north-carolina-mahjong.html', 'north-carolina-mahjong-hub.html'),
    ('hamlet-nc-mahjong.html', 'Hamlet NC', 'NC', 'north-carolina-mahjong.html', 'north-carolina-mahjong-hub.html'),
    ('asheboro-nc-mahjong.html', 'Asheboro NC', 'NC', 'north-carolina-mahjong.html', 'north-carolina-mahjong-hub.html'),
    ('lexington-nc-mahjong.html', 'Lexington NC', 'NC', 'north-carolina-mahjong.html', 'north-carolina-mahjong-hub.html'),
    ('thomasville-nc-mahjong.html', 'Thomasville NC', 'NC', 'north-carolina-mahjong.html', 'north-carolina-mahjong-hub.html'),
    ('high-point-nc-mahjong.html', 'High Point NC', 'NC', 'north-carolina-mahjong.html', 'north-carolina-mahjong-hub.html'),
    ('jamestown-nc-mahjong.html', 'Jamestown NC', 'NC', 'north-carolina-mahjong.html', 'north-carolina-mahjong-hub.html'),
    ('summerfield-nc-mahjong.html', 'Summerfield NC', 'NC', 'north-carolina-mahjong.html', 'north-carolina-mahjong-hub.html'),
    ('oak-ridge-nc-mahjong.html', 'Oak Ridge NC', 'NC', 'north-carolina-mahjong.html', 'north-carolina-mahjong-hub.html'),
    ('king-nc-mahjong.html', 'King NC', 'NC', 'north-carolina-mahjong.html', 'north-carolina-mahjong-hub.html'),
    ('mount-airy-nc-mahjong.html', 'Mount Airy NC', 'NC', 'north-carolina-mahjong.html', 'north-carolina-mahjong-hub.html'),
    ('elkin-nc-mahjong.html', 'Elkin NC', 'NC', 'north-carolina-mahjong.html', 'north-carolina-mahjong-hub.html'),
    ('north-wilkesboro-nc-mahjong.html', 'North Wilkesboro NC', 'NC', 'north-carolina-mahjong.html', 'north-carolina-mahjong-hub.html'),
    ('lenoir-nc-mahjong.html', 'Lenoir NC', 'NC', 'north-carolina-mahjong.html', 'north-carolina-mahjong-hub.html'),
    ('morganton-nc-mahjong.html', 'Morganton NC', 'NC', 'north-carolina-mahjong.html', 'north-carolina-mahjong-hub.html'),
    ('marion-nc-mahjong.html', 'Marion NC', 'NC', 'north-carolina-mahjong.html', 'north-carolina-mahjong-hub.html'),
    ('black-mountain-nc-mahjong.html', 'Black Mountain NC', 'NC', 'north-carolina-mahjong.html', 'north-carolina-mahjong-hub.html'),
    ('weaverville-nc-mahjong.html', 'Weaverville NC', 'NC', 'north-carolina-mahjong.html', 'north-carolina-mahjong-hub.html'),
    ('mars-hill-nc-mahjong.html', 'Mars Hill NC', 'NC', 'north-carolina-mahjong.html', 'north-carolina-mahjong-hub.html'),
    ('brevard-nc-nc-mahjong.html', 'Brevard NC', 'NC', 'north-carolina-mahjong.html', 'north-carolina-mahjong-hub.html'),
    ('sylva-nc-mahjong.html', 'Sylva NC', 'NC', 'north-carolina-mahjong.html', 'north-carolina-mahjong-hub.html'),
    ('franklin-nc-mahjong.html', 'Franklin NC', 'NC', 'north-carolina-mahjong.html', 'north-carolina-mahjong-hub.html'),
    ('highlands-nc-nc-mahjong.html', 'Highlands NC', 'NC', 'north-carolina-mahjong.html', 'north-carolina-mahjong-hub.html'),
    ('cashiers-nc-mahjong.html', 'Cashiers NC', 'NC', 'north-carolina-mahjong.html', 'north-carolina-mahjong-hub.html'),
    ('cherokee-nc-mahjong.html', 'Cherokee NC', 'NC', 'north-carolina-mahjong.html', 'north-carolina-mahjong-hub.html'),
    ('murphy-nc-mahjong.html', 'Murphy NC', 'NC', 'north-carolina-mahjong.html', 'north-carolina-mahjong-hub.html'),
    ('andrews-nc-mahjong.html', 'Andrews NC', 'NC', 'north-carolina-mahjong.html', 'north-carolina-mahjong-hub.html'),
    ('apex-nc-5-mahjong.html', 'Apex NC', 'NC', 'north-carolina-mahjong.html', 'north-carolina-mahjong-hub.html'),
    ('holly-springs-nc-mahjong.html', 'Holly Springs NC', 'NC', 'north-carolina-mahjong.html', 'north-carolina-mahjong-hub.html'),
    ('wake-forest-nc-mahjong.html', 'Wake Forest NC', 'NC', 'north-carolina-mahjong.html', 'north-carolina-mahjong-hub.html'),
    ('garner-nc-mahjong.html', 'Garner NC', 'NC', 'north-carolina-mahjong.html', 'north-carolina-mahjong-hub.html'),
    ('clayton-nc-mahjong.html', 'Clayton NC', 'NC', 'north-carolina-mahjong.html', 'north-carolina-mahjong-hub.html'),
    ('morrisville-nc-mahjong.html', 'Morrisville NC', 'NC', 'north-carolina-mahjong.html', 'north-carolina-mahjong-hub.html'),
    ('fuquay-varina-nc-mahjong.html', 'Fuquay-Varina NC', 'NC', 'north-carolina-mahjong.html', 'north-carolina-mahjong-hub.html'),
    ('albemarle-nc-mahjong.html', 'Albemarle NC', 'NC', 'north-carolina-mahjong.html', 'north-carolina-mahjong-hub.html'),
    ('kernersville-nc-mahjong.html', 'Kernersville NC', 'NC', 'north-carolina-mahjong.html', 'north-carolina-mahjong-hub.html'),
    ('mooresville-nc-nc-mahjong.html', 'Mooresville NC', 'NC', 'north-carolina-mahjong.html', 'north-carolina-mahjong-hub.html'),
    ('huntersville-nc-7-mahjong.html', 'Huntersville NC', 'NC', 'north-carolina-mahjong.html', 'north-carolina-mahjong-hub.html'),
    ('cornelius-nc-nc-mahjong.html', 'Cornelius NC', 'NC', 'north-carolina-mahjong.html', 'north-carolina-mahjong-hub.html'),
    ('davidson-nc-mahjong.html', 'Davidson NC', 'NC', 'north-carolina-mahjong.html', 'north-carolina-mahjong-hub.html'),
    ('stallings-nc-mahjong.html', 'Stallings NC', 'NC', 'north-carolina-mahjong.html', 'north-carolina-mahjong-hub.html'),
    ('weddington-nc-mahjong.html', 'Weddington NC', 'NC', 'north-carolina-mahjong.html', 'north-carolina-mahjong-hub.html'),
    ('matthews-nc-nc-mahjong.html', 'Matthews NC', 'NC', 'north-carolina-mahjong.html', 'north-carolina-mahjong-hub.html'),
    ('clemson-sc-sc-mahjong.html', 'Clemson SC', 'SC', 'south-carolina-mahjong.html', 'south-carolina-mahjong-hub.html'),
    ('seneca-sc-sc-mahjong.html', 'Seneca SC', 'SC', 'south-carolina-mahjong.html', 'south-carolina-mahjong-hub.html'),
    ('easley-sc-sc-mahjong.html', 'Easley SC', 'SC', 'south-carolina-mahjong.html', 'south-carolina-mahjong-hub.html'),
    ('pickens-sc-mahjong.html', 'Pickens SC', 'SC', 'south-carolina-mahjong.html', 'south-carolina-mahjong-hub.html'),
    ('liberty-sc-mahjong.html', 'Liberty SC', 'SC', 'south-carolina-mahjong.html', 'south-carolina-mahjong-hub.html'),
    ('williamston-sc-mahjong.html', 'Williamston SC', 'SC', 'south-carolina-mahjong.html', 'south-carolina-mahjong-hub.html'),
    ('anderson-sc-sc-mahjong.html', 'Anderson SC', 'SC', 'south-carolina-mahjong.html', 'south-carolina-mahjong-hub.html'),
    ('belton-sc-mahjong.html', 'Belton SC', 'SC', 'south-carolina-mahjong.html', 'south-carolina-mahjong-hub.html'),
    ('honea-path-sc-mahjong.html', 'Honea Path SC', 'SC', 'south-carolina-mahjong.html', 'south-carolina-mahjong-hub.html'),
    ('abbeville-sc-mahjong.html', 'Abbeville SC', 'SC', 'south-carolina-mahjong.html', 'south-carolina-mahjong-hub.html'),
    ('greenwood-sc-mahjong.html', 'Greenwood SC', 'SC', 'south-carolina-mahjong.html', 'south-carolina-mahjong-hub.html'),
    ('laurens-sc-mahjong.html', 'Laurens SC', 'SC', 'south-carolina-mahjong.html', 'south-carolina-mahjong-hub.html'),
    ('clinton-sc-mahjong.html', 'Clinton SC', 'SC', 'south-carolina-mahjong.html', 'south-carolina-mahjong-hub.html'),
    ('newberry-sc-mahjong.html', 'Newberry SC', 'SC', 'south-carolina-mahjong.html', 'south-carolina-mahjong-hub.html'),
    ('winnsboro-sc-mahjong.html', 'Winnsboro SC', 'SC', 'south-carolina-mahjong.html', 'south-carolina-mahjong-hub.html'),
    ('blythewood-sc-mahjong.html', 'Blythewood SC', 'SC', 'south-carolina-mahjong.html', 'south-carolina-mahjong-hub.html'),
    ('irmo-sc-mahjong.html', 'Irmo SC', 'SC', 'south-carolina-mahjong.html', 'south-carolina-mahjong-hub.html'),
    ('lexington-sc-mahjong.html', 'Lexington SC', 'SC', 'south-carolina-mahjong.html', 'south-carolina-mahjong-hub.html'),
    ('west-columbia-sc-mahjong.html', 'West Columbia SC', 'SC', 'south-carolina-mahjong.html', 'south-carolina-mahjong-hub.html'),
    ('cayce-sc-mahjong.html', 'Cayce SC', 'SC', 'south-carolina-mahjong.html', 'south-carolina-mahjong-hub.html'),
    ('batesburg-leesville-sc-mahjong.html', 'Batesburg-Leesville SC', 'SC', 'south-carolina-mahjong.html', 'south-carolina-mahjong-hub.html'),
    ('orangeburg-sc-sc-mahjong.html', 'Orangeburg SC', 'SC', 'south-carolina-mahjong.html', 'south-carolina-mahjong-hub.html'),
    ('bamberg-sc-mahjong.html', 'Bamberg SC', 'SC', 'south-carolina-mahjong.html', 'south-carolina-mahjong-hub.html'),
    ('walterboro-sc-mahjong.html', 'Walterboro SC', 'SC', 'south-carolina-mahjong.html', 'south-carolina-mahjong-hub.html'),
    ('ridgeland-sc-mahjong.html', 'Ridgeland SC', 'SC', 'south-carolina-mahjong.html', 'south-carolina-mahjong-hub.html'),
    ('hardeeville-sc-mahjong.html', 'Hardeeville SC', 'SC', 'south-carolina-mahjong.html', 'south-carolina-mahjong-hub.html'),
    ('beaufort-sc-sc-mahjong.html', 'Beaufort SC', 'SC', 'south-carolina-mahjong.html', 'south-carolina-mahjong-hub.html'),
    ('port-royal-sc-mahjong.html', 'Port Royal SC', 'SC', 'south-carolina-mahjong.html', 'south-carolina-mahjong-hub.html'),
    ('folly-beach-sc-mahjong.html', 'Folly Beach SC', 'SC', 'south-carolina-mahjong.html', 'south-carolina-mahjong-hub.html'),
    ('isle-of-palms-sc-mahjong.html', 'Isle of Palms SC', 'SC', 'south-carolina-mahjong.html', 'south-carolina-mahjong-hub.html'),
    ('sullivans-island-sc-mahjong.html', "Sullivan's Island SC", 'SC', 'south-carolina-mahjong.html', 'south-carolina-mahjong-hub.html'),
    ('goose-creek-sc-sc-mahjong.html', 'Goose Creek SC', 'SC', 'south-carolina-mahjong.html', 'south-carolina-mahjong-hub.html'),
    ('moncks-corner-sc-mahjong.html', 'Moncks Corner SC', 'SC', 'south-carolina-mahjong.html', 'south-carolina-mahjong-hub.html'),
    ('georgetown-sc-mahjong.html', 'Georgetown SC', 'SC', 'south-carolina-mahjong.html', 'south-carolina-mahjong-hub.html'),
    ('murrells-inlet-sc-mahjong.html', 'Murrells Inlet SC', 'SC', 'south-carolina-mahjong.html', 'south-carolina-mahjong-hub.html'),
    ('surfside-beach-sc-mahjong.html', 'Surfside Beach SC', 'SC', 'south-carolina-mahjong.html', 'south-carolina-mahjong-hub.html'),
    ('conway-sc-mahjong.html', 'Conway SC', 'SC', 'south-carolina-mahjong.html', 'south-carolina-mahjong-hub.html'),
    ('little-river-sc-mahjong.html', 'Little River SC', 'SC', 'south-carolina-mahjong.html', 'south-carolina-mahjong-hub.html'),
    ('north-myrtle-beach-sc-mahjong.html', 'North Myrtle Beach SC', 'SC', 'south-carolina-mahjong.html', 'south-carolina-mahjong-hub.html'),
    ('loris-sc-mahjong.html', 'Loris SC', 'SC', 'south-carolina-mahjong.html', 'south-carolina-mahjong-hub.html'),
    ('bennettsville-sc-mahjong.html', 'Bennettsville SC', 'SC', 'south-carolina-mahjong.html', 'south-carolina-mahjong-hub.html'),
    ('dillon-sc-mahjong.html', 'Dillon SC', 'SC', 'south-carolina-mahjong.html', 'south-carolina-mahjong-hub.html'),
    ('marion-sc-mahjong.html', 'Marion SC', 'SC', 'south-carolina-mahjong.html', 'south-carolina-mahjong-hub.html'),
    ('lake-city-sc-mahjong.html', 'Lake City SC', 'SC', 'south-carolina-mahjong.html', 'south-carolina-mahjong-hub.html'),
    ('manning-sc-mahjong.html', 'Manning SC', 'SC', 'south-carolina-mahjong.html', 'south-carolina-mahjong-hub.html'),
    ('bishopville-sc-mahjong.html', 'Bishopville SC', 'SC', 'south-carolina-mahjong.html', 'south-carolina-mahjong-hub.html'),
    ('fort-mill-sc-sc-mahjong.html', 'Fort Mill SC', 'SC', 'south-carolina-mahjong.html', 'south-carolina-mahjong-hub.html'),
]
