# auto-generated booking / near-me city tuples
WAVE40_BOOKING_CITIES = [
    ('florence-al-lessons-near-me.html', 'Florence AL', 'AL', 'alabama-mahjong.html', 'florence-al-mahjong.html', 'mahjong-lessons-near-me-alabama.html'),
    ('decatur-al-lessons-near-me.html', 'Decatur AL', 'AL', 'alabama-mahjong.html', 'decatur-al-mahjong.html', 'mahjong-lessons-near-me-alabama.html'),
    ('opelika-al-lessons-near-me.html', 'Opelika AL', 'AL', 'alabama-mahjong.html', 'opelika-al-mahjong.html', 'mahjong-lessons-near-me-alabama.html'),
    ('phenix-city-al-lessons-near-me.html', 'Phenix City', 'AL', 'alabama-mahjong.html', 'phenix-city-al-mahjong.html', 'mahjong-lessons-near-me-alabama.html'),
    ('enterprise-al-lessons-near-me.html', 'Enterprise AL', 'AL', 'alabama-mahjong.html', 'enterprise-al-mahjong.html', 'mahjong-lessons-near-me-alabama.html'),
    ('selma-al-lessons-near-me.html', 'Selma AL', 'AL', 'alabama-mahjong.html', 'selma-al-mahjong.html', 'mahjong-lessons-near-me-alabama.html'),
    ('anniston-al-lessons-near-me.html', 'Anniston AL', 'AL', 'alabama-mahjong.html', 'anniston-al-mahjong.html', 'mahjong-lessons-near-me-alabama.html'),
    ('cullman-al-lessons-near-me.html', 'Cullman AL', 'AL', 'alabama-mahjong.html', 'cullman-al-mahjong.html', 'mahjong-lessons-near-me-alabama.html'),
    ('hoover-al-lessons-near-me.html', 'Hoover AL', 'AL', 'alabama-mahjong.html', 'hoover-al-mahjong.html', 'mahjong-lessons-near-me-alabama.html'),
    ('prattville-al-lessons-near-me.html', 'Prattville AL', 'AL', 'alabama-mahjong.html', 'prattville-al-mahjong.html', 'mahjong-lessons-near-me-alabama.html'),
    ('sitka-ak-lessons-near-me.html', 'Sitka AK', 'AK', 'alaska-mahjong.html', 'sitka-ak-mahjong.html', 'mahjong-lessons-near-me-alaska.html'),
    ('kodiak-ak-lessons-near-me.html', 'Kodiak AK', 'AK', 'alaska-mahjong.html', 'kodiak-ak-mahjong.html', 'mahjong-lessons-near-me-alaska.html'),
    ('kenai-ak-lessons-near-me.html', 'Kenai AK', 'AK', 'alaska-mahjong.html', 'kenai-ak-mahjong.html', 'mahjong-lessons-near-me-alaska.html'),
    ('soldotna-ak-lessons-near-me.html', 'Soldotna AK', 'AK', 'alaska-mahjong.html', 'soldotna-ak-mahjong.html', 'mahjong-lessons-near-me-alaska.html'),
    ('homer-ak-lessons-near-me.html', 'Homer AK', 'AK', 'alaska-mahjong.html', 'homer-ak-mahjong.html', 'mahjong-lessons-near-me-alaska.html'),
    ('palmer-ak-lessons-near-me.html', 'Palmer AK', 'AK', 'alaska-mahjong.html', 'palmer-ak-mahjong.html', 'mahjong-lessons-near-me-alaska.html'),
    ('valdez-ak-lessons-near-me.html', 'Valdez AK', 'AK', 'alaska-mahjong.html', 'valdez-ak-mahjong.html', 'mahjong-lessons-near-me-alaska.html'),
    ('nome-ak-lessons-near-me.html', 'Nome AK', 'AK', 'alaska-mahjong.html', 'nome-ak-mahjong.html', 'mahjong-lessons-near-me-alaska.html'),
    ('bethel-ak-lessons-near-me.html', 'Bethel AK', 'AK', 'alaska-mahjong.html', 'bethel-ak-mahjong.html', 'mahjong-lessons-near-me-alaska.html'),
    ('cordova-ak-lessons-near-me.html', 'Cordova AK', 'AK', 'alaska-mahjong.html', 'cordova-ak-mahjong.html', 'mahjong-lessons-near-me-alaska.html'),
    ('lake-havasu-city-az-lessons-near-me.html', 'Lake Havasu City', 'AZ', 'arizona-mahjong.html', 'lake-havasu-city-az-mahjong.html', 'mahjong-lessons-near-me-arizona.html'),
    ('bullhead-city-az-lessons-near-me.html', 'Bullhead City', 'AZ', 'arizona-mahjong.html', 'bullhead-city-az-mahjong.html', 'mahjong-lessons-near-me-arizona.html'),
    ('sierra-vista-az-lessons-near-me.html', 'Sierra Vista', 'AZ', 'arizona-mahjong.html', 'sierra-vista-az-mahjong.html', 'mahjong-lessons-near-me-arizona.html'),
    ('casa-grande-az-lessons-near-me.html', 'Casa Grande', 'AZ', 'arizona-mahjong.html', 'casa-grande-az-mahjong.html', 'mahjong-lessons-near-me-arizona.html'),
    ('maricopa-az-lessons-near-me.html', 'Maricopa AZ', 'AZ', 'arizona-mahjong.html', 'maricopa-az-mahjong.html', 'mahjong-lessons-near-me-arizona.html'),
    ('oro-valley-az-lessons-near-me.html', 'Oro Valley', 'AZ', 'arizona-mahjong.html', 'oro-valley-az-mahjong.html', 'mahjong-lessons-near-me-arizona.html'),
    ('apache-junction-az-lessons-near-me.html', 'Apache Junction', 'AZ', 'arizona-mahjong.html', 'apache-junction-az-mahjong.html', 'mahjong-lessons-near-me-arizona.html'),
    ('hot-springs-ar-lessons-near-me.html', 'Hot Springs', 'AR', 'arkansas-mahjong.html', 'hot-springs-ar-mahjong.html', 'mahjong-lessons-near-me-arkansas.html'),
    ('conway-ar-lessons-near-me.html', 'Conway AR', 'AR', 'arkansas-mahjong.html', 'conway-ar-mahjong.html', 'mahjong-lessons-near-me-arkansas.html'),
    ('rogers-ar-lessons-near-me.html', 'Rogers AR', 'AR', 'arkansas-mahjong.html', 'rogers-ar-mahjong.html', 'mahjong-lessons-near-me-arkansas.html'),
    ('bentonville-ar-lessons-near-me.html', 'Bentonville AR', 'AR', 'arkansas-mahjong.html', 'bentonville-ar-mahjong.html', 'mahjong-lessons-near-me-arkansas.html'),
    ('benton-ar-lessons-near-me.html', 'Benton AR', 'AR', 'arkansas-mahjong.html', 'benton-ar-mahjong.html', 'mahjong-lessons-near-me-arkansas.html'),
    ('texarkana-ar-lessons-near-me.html', 'Texarkana AR', 'AR', 'arkansas-mahjong.html', 'texarkana-ar-mahjong.html', 'mahjong-lessons-near-me-arkansas.html'),
    ('el-dorado-ar-lessons-near-me.html', 'El Dorado', 'AR', 'arkansas-mahjong.html', 'el-dorado-ar-mahjong.html', 'mahjong-lessons-near-me-arkansas.html'),
    ('searcy-ar-lessons-near-me.html', 'Searcy AR', 'AR', 'arkansas-mahjong.html', 'searcy-ar-mahjong.html', 'mahjong-lessons-near-me-arkansas.html'),
    ('russellville-ar-lessons-near-me.html', 'Russellville AR', 'AR', 'arkansas-mahjong.html', 'russellville-ar-mahjong.html', 'mahjong-lessons-near-me-arkansas.html'),
    ('paragould-ar-lessons-near-me.html', 'Paragould AR', 'AR', 'arkansas-mahjong.html', 'paragould-ar-mahjong.html', 'mahjong-lessons-near-me-arkansas.html'),
    ('oxnard-ca-lessons-near-me.html', 'Oxnard CA', 'CA', 'california-mahjong.html', 'oxnard-ca-mahjong.html', 'mahjong-lessons-near-me-california.html'),
    ('thousand-oaks-ca-lessons-near-me.html', 'Thousand Oaks', 'CA', 'california-mahjong.html', 'thousand-oaks-ca-mahjong.html', 'mahjong-lessons-near-me-california.html'),
    ('ventura-ca-lessons-near-me.html', 'Ventura CA', 'CA', 'california-mahjong.html', 'ventura-ca-mahjong.html', 'mahjong-lessons-near-me-california.html'),
    ('salinas-ca-lessons-near-me.html', 'Salinas CA', 'CA', 'california-mahjong.html', 'salinas-ca-mahjong.html', 'mahjong-lessons-near-me-california.html'),
    ('chico-ca-lessons-near-me.html', 'Chico CA', 'CA', 'california-mahjong.html', 'chico-ca-mahjong.html', 'mahjong-lessons-near-me-california.html'),
    ('redding-ca-lessons-near-me.html', 'Redding CA', 'CA', 'california-mahjong.html', 'redding-ca-mahjong.html', 'mahjong-lessons-near-me-california.html'),
    ('eureka-ca-lessons-near-me.html', 'Eureka CA', 'CA', 'california-mahjong.html', 'eureka-ca-mahjong.html', 'mahjong-lessons-near-me-california.html'),
    ('san-luis-obispo-ca-lessons-near-me.html', 'San Luis Obispo', 'CA', 'california-mahjong.html', 'san-luis-obispo-ca-mahjong.html', 'mahjong-lessons-near-me-california.html'),
    ('paso-robles-ca-lessons-near-me.html', 'Paso Robles', 'CA', 'california-mahjong.html', 'paso-robles-ca-mahjong.html', 'mahjong-lessons-near-me-california.html'),
    ('napa-ca-lessons-near-me.html', 'Napa CA', 'CA', 'california-mahjong.html', 'napa-ca-mahjong.html', 'mahjong-lessons-near-me-california.html'),
    ('vallejo-ca-lessons-near-me.html', 'Vallejo CA', 'CA', 'california-mahjong.html', 'vallejo-ca-mahjong.html', 'mahjong-lessons-near-me-california.html'),
    ('fairfield-ca-lessons-near-me.html', 'Fairfield CA', 'CA', 'california-mahjong.html', 'fairfield-ca-mahjong.html', 'mahjong-lessons-near-me-california.html'),
    ('antioch-ca-lessons-near-me.html', 'Antioch CA', 'CA', 'california-mahjong.html', 'antioch-ca-mahjong.html', 'mahjong-lessons-near-me-california.html'),
    ('concord-ca-lessons-near-me.html', 'Concord CA', 'CA', 'california-mahjong.html', 'concord-ca-mahjong.html', 'mahjong-lessons-near-me-california.html'),
    ('walnut-creek-ca-lessons-near-me.html', 'Walnut Creek', 'CA', 'california-mahjong.html', 'walnut-creek-ca-mahjong.html', 'mahjong-lessons-near-me-california.html'),
    ('san-mateo-ca-lessons-near-me.html', 'San Mateo', 'CA', 'california-mahjong.html', 'san-mateo-ca-mahjong.html', 'mahjong-lessons-near-me-california.html'),
    ('redwood-city-ca-lessons-near-me.html', 'Redwood City', 'CA', 'california-mahjong.html', 'redwood-city-ca-mahjong.html', 'mahjong-lessons-near-me-california.html'),
    ('palo-alto-ca-lessons-near-me.html', 'Palo Alto', 'CA', 'california-mahjong.html', 'palo-alto-ca-mahjong.html', 'mahjong-lessons-near-me-california.html'),
    ('mountain-view-ca-lessons-near-me.html', 'Mountain View', 'CA', 'california-mahjong.html', 'mountain-view-ca-mahjong.html', 'mahjong-lessons-near-me-california.html'),
    ('santa-cruz-ca-lessons-near-me.html', 'Santa Cruz', 'CA', 'california-mahjong.html', 'santa-cruz-ca-mahjong.html', 'mahjong-lessons-near-me-california.html'),
    ('colorado-springs-co-lessons-near-me.html', 'Colorado Springs', 'CO', 'colorado-mahjong.html', 'colorado-springs-co-mahjong.html', 'mahjong-lessons-near-me-colorado.html'),
    ('pueblo-co-lessons-near-me.html', 'Pueblo CO', 'CO', 'colorado-mahjong.html', 'pueblo-co-mahjong.html', 'mahjong-lessons-near-me-colorado.html'),
    ('loveland-co-lessons-near-me.html', 'Loveland CO', 'CO', 'colorado-mahjong.html', 'loveland-co-mahjong.html', 'mahjong-lessons-near-me-colorado.html'),
    ('longmont-co-lessons-near-me.html', 'Longmont CO', 'CO', 'colorado-mahjong.html', 'longmont-co-mahjong.html', 'mahjong-lessons-near-me-colorado.html'),
    ('broomfield-co-lessons-near-me.html', 'Broomfield CO', 'CO', 'colorado-mahjong.html', 'broomfield-co-mahjong.html', 'mahjong-lessons-near-me-colorado.html'),
    ('westminster-co-lessons-near-me.html', 'Westminster CO', 'CO', 'colorado-mahjong.html', 'westminster-co-mahjong.html', 'mahjong-lessons-near-me-colorado.html'),
    ('lakewood-co-lessons-near-me.html', 'Lakewood CO', 'CO', 'colorado-mahjong.html', 'lakewood-co-mahjong.html', 'mahjong-lessons-near-me-colorado.html'),
    ('littleton-co-lessons-near-me.html', 'Littleton CO', 'CO', 'colorado-mahjong.html', 'littleton-co-mahjong.html', 'mahjong-lessons-near-me-colorado.html'),
    ('norwalk-ct-lessons-near-me.html', 'Norwalk CT', 'CT', 'connecticut-mahjong.html', 'norwalk-ct-mahjong.html', 'mahjong-lessons-near-me-connecticut.html'),
    ('danbury-ct-lessons-near-me.html', 'Danbury CT', 'CT', 'connecticut-mahjong.html', 'danbury-ct-mahjong.html', 'mahjong-lessons-near-me-connecticut.html'),
    ('waterbury-ct-lessons-near-me.html', 'Waterbury CT', 'CT', 'connecticut-mahjong.html', 'waterbury-ct-mahjong.html', 'mahjong-lessons-near-me-connecticut.html'),
    ('new-britain-ct-lessons-near-me.html', 'New Britain', 'CT', 'connecticut-mahjong.html', 'new-britain-ct-mahjong.html', 'mahjong-lessons-near-me-connecticut.html'),
    ('bristol-ct-lessons-near-me.html', 'Bristol CT', 'CT', 'connecticut-mahjong.html', 'bristol-ct-mahjong.html', 'mahjong-lessons-near-me-connecticut.html'),
    ('meriden-ct-lessons-near-me.html', 'Meriden CT', 'CT', 'connecticut-mahjong.html', 'meriden-ct-mahjong.html', 'mahjong-lessons-near-me-connecticut.html'),
    ('middletown-ct-lessons-near-me.html', 'Middletown CT', 'CT', 'connecticut-mahjong.html', 'middletown-ct-mahjong.html', 'mahjong-lessons-near-me-connecticut.html'),
    ('norwich-ct-lessons-near-me.html', 'Norwich CT', 'CT', 'connecticut-mahjong.html', 'norwich-ct-mahjong.html', 'mahjong-lessons-near-me-connecticut.html'),
    ('middletown-de-lessons-near-me.html', 'Middletown DE', 'DE', 'delaware-mahjong.html', 'middletown-de-mahjong.html', 'mahjong-lessons-near-me-delaware.html'),
    ('smyrna-de-lessons-near-me.html', 'Smyrna DE', 'DE', 'delaware-mahjong.html', 'smyrna-de-mahjong.html', 'mahjong-lessons-near-me-delaware.html'),
    ('seaford-de-lessons-near-me.html', 'Seaford DE', 'DE', 'delaware-mahjong.html', 'seaford-de-mahjong.html', 'mahjong-lessons-near-me-delaware.html'),
    ('georgetown-de-lessons-near-me.html', 'Georgetown DE', 'DE', 'delaware-mahjong.html', 'georgetown-de-mahjong.html', 'mahjong-lessons-near-me-delaware.html'),
    ('elsmere-de-lessons-near-me.html', 'Elsmere DE', 'DE', 'delaware-mahjong.html', 'elsmere-de-mahjong.html', 'mahjong-lessons-near-me-delaware.html'),
    ('new-castle-de-lessons-near-me.html', 'New Castle', 'DE', 'delaware-mahjong.html', 'new-castle-de-mahjong.html', 'mahjong-lessons-near-me-delaware.html'),
    ('bear-de-lessons-near-me.html', 'Bear DE', 'DE', 'delaware-mahjong.html', 'bear-de-mahjong.html', 'mahjong-lessons-near-me-delaware.html'),
    ('hockessin-de-lessons-near-me.html', 'Hockessin DE', 'DE', 'delaware-mahjong.html', 'hockessin-de-mahjong.html', 'mahjong-lessons-near-me-delaware.html'),
    ('claymont-de-lessons-near-me.html', 'Claymont DE', 'DE', 'delaware-mahjong.html', 'claymont-de-mahjong.html', 'mahjong-lessons-near-me-delaware.html'),
    ('laurel-de-lessons-near-me.html', 'Laurel DE', 'DE', 'delaware-mahjong.html', 'laurel-de-mahjong.html', 'mahjong-lessons-near-me-delaware.html'),
    ('sarasota-fl-lessons-near-me.html', 'Sarasota FL', 'FL', 'florida-mahjong.html', 'sarasota-fl-mahjong.html', 'mahjong-lessons-near-me-florida.html'),
    ('bradenton-fl-lessons-near-me.html', 'Bradenton FL', 'FL', 'florida-mahjong.html', 'bradenton-fl-mahjong.html', 'mahjong-lessons-near-me-florida.html'),
    ('venice-fl-lessons-near-me.html', 'Venice FL', 'FL', 'florida-mahjong.html', 'venice-fl-mahjong.html', 'mahjong-lessons-near-me-florida.html'),
    ('punta-gorda-fl-lessons-near-me.html', 'Punta Gorda', 'FL', 'florida-mahjong.html', 'punta-gorda-fl-mahjong.html', 'mahjong-lessons-near-me-florida.html'),
    ('naples-fl-lessons-near-me.html', 'Naples FL', 'FL', 'florida-mahjong.html', 'naples-fl-mahjong.html', 'mahjong-lessons-near-me-florida.html'),
    ('bonita-springs-fl-lessons-near-me.html', 'Bonita Springs', 'FL', 'florida-mahjong.html', 'bonita-springs-fl-mahjong.html', 'mahjong-lessons-near-me-florida.html'),
    ('delray-beach-fl-lessons-near-me.html', 'Delray Beach', 'FL', 'florida-mahjong.html', 'delray-beach-fl-mahjong.html', 'mahjong-lessons-near-me-florida.html'),
    ('deerfield-beach-fl-lessons-near-me.html', 'Deerfield Beach', 'FL', 'florida-mahjong.html', 'deerfield-beach-fl-mahjong.html', 'mahjong-lessons-near-me-florida.html'),
    ('hollywood-fl-lessons-near-me.html', 'Hollywood FL', 'FL', 'florida-mahjong.html', 'hollywood-fl-mahjong.html', 'mahjong-lessons-near-me-florida.html'),
    ('pembroke-pines-fl-lessons-near-me.html', 'Pembroke Pines', 'FL', 'florida-mahjong.html', 'pembroke-pines-fl-mahjong.html', 'mahjong-lessons-near-me-florida.html'),
    ('kissimmee-fl-lessons-near-me.html', 'Kissimmee FL', 'FL', 'florida-mahjong.html', 'kissimmee-fl-mahjong.html', 'mahjong-lessons-near-me-florida.html'),
    ('sanford-fl-lessons-near-me.html', 'Sanford FL', 'FL', 'florida-mahjong.html', 'sanford-fl-mahjong.html', 'mahjong-lessons-near-me-florida.html'),
    ('apopka-fl-lessons-near-me.html', 'Apopka FL', 'FL', 'florida-mahjong.html', 'apopka-fl-mahjong.html', 'mahjong-lessons-near-me-florida.html'),
    ('clermont-fl-lessons-near-me.html', 'Clermont FL', 'FL', 'florida-mahjong.html', 'clermont-fl-mahjong.html', 'mahjong-lessons-near-me-florida.html'),
    ('palm-coast-fl-lessons-near-me.html', 'Palm Coast', 'FL', 'florida-mahjong.html', 'palm-coast-fl-mahjong.html', 'mahjong-lessons-near-me-florida.html'),
    ('ormond-beach-fl-lessons-near-me.html', 'Ormond Beach', 'FL', 'florida-mahjong.html', 'ormond-beach-fl-mahjong.html', 'mahjong-lessons-near-me-florida.html'),
    ('new-smyrna-beach-fl-lessons-near-me.html', 'New Smyrna Beach', 'FL', 'florida-mahjong.html', 'new-smyrna-beach-fl-mahjong.html', 'mahjong-lessons-near-me-florida.html'),
    ('fort-pierce-fl-lessons-near-me.html', 'Fort Pierce', 'FL', 'florida-mahjong.html', 'fort-pierce-fl-mahjong.html', 'mahjong-lessons-near-me-florida.html'),
    ('stuart-fl-lessons-near-me.html', 'Stuart FL', 'FL', 'florida-mahjong.html', 'stuart-fl-mahjong.html', 'mahjong-lessons-near-me-florida.html'),
    ('gainesville-ga-lessons-near-me.html', 'Gainesville GA', 'GA', 'georgia-mahjong.html', 'gainesville-ga-mahjong.html', 'mahjong-lessons-near-me-georgia.html'),
    ('carrollton-ga-lessons-near-me.html', 'Carrollton GA', 'GA', 'georgia-mahjong.html', 'carrollton-ga-mahjong.html', 'mahjong-lessons-near-me-georgia.html'),
    ('newnan-ga-lessons-near-me.html', 'Newnan GA', 'GA', 'georgia-mahjong.html', 'newnan-ga-mahjong.html', 'mahjong-lessons-near-me-georgia.html'),
    ('lagrange-ga-lessons-near-me.html', 'LaGrange GA', 'GA', 'georgia-mahjong.html', 'lagrange-ga-mahjong.html', 'mahjong-lessons-near-me-georgia.html'),
    ('hinesville-ga-lessons-near-me.html', 'Hinesville GA', 'GA', 'georgia-mahjong.html', 'hinesville-ga-mahjong.html', 'mahjong-lessons-near-me-georgia.html'),
    ('peachtree-city-ga-lessons-near-me.html', 'Peachtree City', 'GA', 'georgia-mahjong.html', 'peachtree-city-ga-mahjong.html', 'mahjong-lessons-near-me-georgia.html'),
    ('woodstock-ga-lessons-near-me.html', 'Woodstock GA', 'GA', 'georgia-mahjong.html', 'woodstock-ga-mahjong.html', 'mahjong-lessons-near-me-georgia.html'),
    ('marietta-ga-lessons-near-me.html', 'Marietta GA', 'GA', 'georgia-mahjong.html', 'marietta-ga-mahjong.html', 'mahjong-lessons-near-me-georgia.html'),
    ('roswell-ga-lessons-near-me.html', 'Roswell GA', 'GA', 'georgia-mahjong.html', 'roswell-ga-mahjong.html', 'mahjong-lessons-near-me-georgia.html'),
    ('alpharetta-ga-lessons-near-me.html', 'Alpharetta GA', 'GA', 'georgia-mahjong.html', 'alpharetta-ga-mahjong.html', 'mahjong-lessons-near-me-georgia.html'),
    ('duluth-ga-lessons-near-me.html', 'Duluth GA', 'GA', 'georgia-mahjong.html', 'duluth-ga-mahjong.html', 'mahjong-lessons-near-me-georgia.html'),
    ('lawrenceville-ga-lessons-near-me.html', 'Lawrenceville', 'GA', 'georgia-mahjong.html', 'lawrenceville-ga-mahjong.html', 'mahjong-lessons-near-me-georgia.html'),
    ('snellville-ga-lessons-near-me.html', 'Snellville GA', 'GA', 'georgia-mahjong.html', 'snellville-ga-mahjong.html', 'mahjong-lessons-near-me-georgia.html'),
    ('kennesaw-ga-lessons-near-me.html', 'Kennesaw GA', 'GA', 'georgia-mahjong.html', 'kennesaw-ga-mahjong.html', 'mahjong-lessons-near-me-georgia.html'),
    ('kapolei-hi-lessons-near-me.html', 'Kapolei HI', 'HI', 'hawaii-mahjong.html', 'kapolei-hi-mahjong.html', 'mahjong-lessons-near-me-hawaii.html'),
    ('ewa-beach-hi-lessons-near-me.html', 'Ewa Beach', 'HI', 'hawaii-mahjong.html', 'ewa-beach-hi-mahjong.html', 'mahjong-lessons-near-me-hawaii.html'),
    ('pearl-city-hi-lessons-near-me.html', 'Pearl City', 'HI', 'hawaii-mahjong.html', 'pearl-city-hi-mahjong.html', 'mahjong-lessons-near-me-hawaii.html'),
    ('kaneohe-hi-lessons-near-me.html', 'Kaneohe HI', 'HI', 'hawaii-mahjong.html', 'kaneohe-hi-mahjong.html', 'mahjong-lessons-near-me-hawaii.html'),
    ('mililani-hi-lessons-near-me.html', 'Mililani HI', 'HI', 'hawaii-mahjong.html', 'mililani-hi-mahjong.html', 'mahjong-lessons-near-me-hawaii.html'),
    ('waipahu-hi-lessons-near-me.html', 'Waipahu HI', 'HI', 'hawaii-mahjong.html', 'waipahu-hi-mahjong.html', 'mahjong-lessons-near-me-hawaii.html'),
    ('lihue-hi-lessons-near-me.html', 'Lihue HI', 'HI', 'hawaii-mahjong.html', 'lihue-hi-mahjong.html', 'mahjong-lessons-near-me-hawaii.html'),
    ('kahului-hi-lessons-near-me.html', 'Kahului HI', 'HI', 'hawaii-mahjong.html', 'kahului-hi-mahjong.html', 'mahjong-lessons-near-me-hawaii.html'),
    ('kihei-hi-lessons-near-me.html', 'Kihei HI', 'HI', 'hawaii-mahjong.html', 'kihei-hi-mahjong.html', 'mahjong-lessons-near-me-hawaii.html'),
    ('waimea-hi-lessons-near-me.html', 'Waimea HI', 'HI', 'hawaii-mahjong.html', 'waimea-hi-mahjong.html', 'mahjong-lessons-near-me-hawaii.html'),
    ('caldwell-id-lessons-near-me.html', 'Caldwell ID', 'ID', 'idaho-mahjong.html', 'caldwell-id-mahjong.html', 'mahjong-lessons-near-me-idaho.html'),
    ('eagle-id-lessons-near-me.html', 'Eagle ID', 'ID', 'idaho-mahjong.html', 'eagle-id-mahjong.html', 'mahjong-lessons-near-me-idaho.html'),
    ('ammon-id-lessons-near-me.html', 'Ammon ID', 'ID', 'idaho-mahjong.html', 'ammon-id-mahjong.html', 'mahjong-lessons-near-me-idaho.html'),
    ('rexburg-id-lessons-near-me.html', 'Rexburg ID', 'ID', 'idaho-mahjong.html', 'rexburg-id-mahjong.html', 'mahjong-lessons-near-me-idaho.html'),
    ('moscow-id-lessons-near-me.html', 'Moscow ID', 'ID', 'idaho-mahjong.html', 'moscow-id-mahjong.html', 'mahjong-lessons-near-me-idaho.html'),
    ('lewiston-id-lessons-near-me.html', 'Lewiston ID', 'ID', 'idaho-mahjong.html', 'lewiston-id-mahjong.html', 'mahjong-lessons-near-me-idaho.html'),
    ('post-falls-id-lessons-near-me.html', 'Post Falls', 'ID', 'idaho-mahjong.html', 'post-falls-id-mahjong.html', 'mahjong-lessons-near-me-idaho.html'),
    ('hayden-id-lessons-near-me.html', 'Hayden ID', 'ID', 'idaho-mahjong.html', 'hayden-id-mahjong.html', 'mahjong-lessons-near-me-idaho.html'),
    ('aurora-il-lessons-near-me.html', 'Aurora IL', 'IL', 'illinois-mahjong.html', 'aurora-il-mahjong.html', 'mahjong-lessons-near-me-illinois.html'),
    ('joliet-il-lessons-near-me.html', 'Joliet IL', 'IL', 'illinois-mahjong.html', 'joliet-il-mahjong.html', 'mahjong-lessons-near-me-illinois.html'),
    ('evanston-il-lessons-near-me.html', 'Evanston IL', 'IL', 'illinois-mahjong.html', 'evanston-il-mahjong.html', 'mahjong-lessons-near-me-illinois.html'),
    ('schaumburg-il-lessons-near-me.html', 'Schaumburg IL', 'IL', 'illinois-mahjong.html', 'schaumburg-il-mahjong.html', 'mahjong-lessons-near-me-illinois.html'),
    ('oak-park-il-lessons-near-me.html', 'Oak Park', 'IL', 'illinois-mahjong.html', 'oak-park-il-mahjong.html', 'mahjong-lessons-near-me-illinois.html'),
    ('skokie-il-lessons-near-me.html', 'Skokie IL', 'IL', 'illinois-mahjong.html', 'skokie-il-mahjong.html', 'mahjong-lessons-near-me-illinois.html'),
    ('bloomington-il-lessons-near-me.html', 'Bloomington IL', 'IL', 'illinois-mahjong.html', 'bloomington-il-mahjong.html', 'mahjong-lessons-near-me-illinois.html'),
    ('moline-il-lessons-near-me.html', 'Moline IL', 'IL', 'illinois-mahjong.html', 'moline-il-mahjong.html', 'mahjong-lessons-near-me-illinois.html'),
    ('quincy-il-lessons-near-me.html', 'Quincy IL', 'IL', 'illinois-mahjong.html', 'quincy-il-mahjong.html', 'mahjong-lessons-near-me-illinois.html'),
    ('carbondale-il-lessons-near-me.html', 'Carbondale IL', 'IL', 'illinois-mahjong.html', 'carbondale-il-mahjong.html', 'mahjong-lessons-near-me-illinois.html'),
    ('normal-il-lessons-near-me.html', 'Normal IL', 'IL', 'illinois-mahjong.html', 'normal-il-mahjong.html', 'mahjong-lessons-near-me-illinois.html'),
    ('decatur-il-lessons-near-me.html', 'Decatur IL', 'IL', 'illinois-mahjong.html', 'decatur-il-mahjong.html', 'mahjong-lessons-near-me-illinois.html'),
    ('waukegan-il-lessons-near-me.html', 'Waukegan IL', 'IL', 'illinois-mahjong.html', 'waukegan-il-mahjong.html', 'mahjong-lessons-near-me-illinois.html'),
    ('cicero-il-lessons-near-me.html', 'Cicero IL', 'IL', 'illinois-mahjong.html', 'cicero-il-mahjong.html', 'mahjong-lessons-near-me-illinois.html'),
    ('elgin-il-lessons-near-me.html', 'Elgin IL', 'IL', 'illinois-mahjong.html', 'elgin-il-mahjong.html', 'mahjong-lessons-near-me-illinois.html'),
    ('kokomo-in-lessons-near-me.html', 'Kokomo IN', 'IN', 'indiana-mahjong.html', 'kokomo-in-mahjong.html', 'mahjong-lessons-near-me-indiana.html'),
    ('anderson-in-lessons-near-me.html', 'Anderson IN', 'IN', 'indiana-mahjong.html', 'anderson-in-mahjong.html', 'mahjong-lessons-near-me-indiana.html'),
    ('noblesville-in-lessons-near-me.html', 'Noblesville IN', 'IN', 'indiana-mahjong.html', 'noblesville-in-mahjong.html', 'mahjong-lessons-near-me-indiana.html'),
    ('greenwood-in-lessons-near-me.html', 'Greenwood IN', 'IN', 'indiana-mahjong.html', 'greenwood-in-mahjong.html', 'mahjong-lessons-near-me-indiana.html'),
    ('hammond-in-lessons-near-me.html', 'Hammond IN', 'IN', 'indiana-mahjong.html', 'hammond-in-mahjong.html', 'mahjong-lessons-near-me-indiana.html'),
    ('gary-in-lessons-near-me.html', 'Gary IN', 'IN', 'indiana-mahjong.html', 'gary-in-mahjong.html', 'mahjong-lessons-near-me-indiana.html'),
    ('lafayette-in-lessons-near-me.html', 'Lafayette IN', 'IN', 'indiana-mahjong.html', 'lafayette-in-mahjong.html', 'mahjong-lessons-near-me-indiana.html'),
    ('west-lafayette-in-lessons-near-me.html', 'West Lafayette', 'IN', 'indiana-mahjong.html', 'west-lafayette-in-mahjong.html', 'mahjong-lessons-near-me-indiana.html'),
    ('mishawaka-in-lessons-near-me.html', 'Mishawaka IN', 'IN', 'indiana-mahjong.html', 'mishawaka-in-mahjong.html', 'mahjong-lessons-near-me-indiana.html'),
    ('elkhart-in-lessons-near-me.html', 'Elkhart IN', 'IN', 'indiana-mahjong.html', 'elkhart-in-mahjong.html', 'mahjong-lessons-near-me-indiana.html'),
    ('columbus-in-lessons-near-me.html', 'Columbus IN', 'IN', 'indiana-mahjong.html', 'columbus-in-mahjong.html', 'mahjong-lessons-near-me-indiana.html'),
    ('jeffersonville-in-lessons-near-me.html', 'Jeffersonville', 'IN', 'indiana-mahjong.html', 'jeffersonville-in-mahjong.html', 'mahjong-lessons-near-me-indiana.html'),
    ('new-albany-in-lessons-near-me.html', 'New Albany', 'IN', 'indiana-mahjong.html', 'new-albany-in-mahjong.html', 'mahjong-lessons-near-me-indiana.html'),
    ('richmond-in-lessons-near-me.html', 'Richmond IN', 'IN', 'indiana-mahjong.html', 'richmond-in-mahjong.html', 'mahjong-lessons-near-me-indiana.html'),
    ('marion-in-lessons-near-me.html', 'Marion IN', 'IN', 'indiana-mahjong.html', 'marion-in-mahjong.html', 'mahjong-lessons-near-me-indiana.html'),
    ('waterloo-ia-lessons-near-me.html', 'Waterloo IA', 'IA', 'iowa-mahjong.html', 'waterloo-ia-mahjong.html', 'mahjong-lessons-near-me-iowa.html'),
    ('mason-city-ia-lessons-near-me.html', 'Mason City', 'IA', 'iowa-mahjong.html', 'mason-city-ia-mahjong.html', 'mahjong-lessons-near-me-iowa.html'),
    ('fort-dodge-ia-lessons-near-me.html', 'Fort Dodge', 'IA', 'iowa-mahjong.html', 'fort-dodge-ia-mahjong.html', 'mahjong-lessons-near-me-iowa.html'),
    ('marshalltown-ia-lessons-near-me.html', 'Marshalltown IA', 'IA', 'iowa-mahjong.html', 'marshalltown-ia-mahjong.html', 'mahjong-lessons-near-me-iowa.html'),
    ('burlington-ia-lessons-near-me.html', 'Burlington IA', 'IA', 'iowa-mahjong.html', 'burlington-ia-mahjong.html', 'mahjong-lessons-near-me-iowa.html'),
    ('clinton-ia-lessons-near-me.html', 'Clinton IA', 'IA', 'iowa-mahjong.html', 'clinton-ia-mahjong.html', 'mahjong-lessons-near-me-iowa.html'),
    ('muscatine-ia-lessons-near-me.html', 'Muscatine IA', 'IA', 'iowa-mahjong.html', 'muscatine-ia-mahjong.html', 'mahjong-lessons-near-me-iowa.html'),
    ('ottumwa-ia-lessons-near-me.html', 'Ottumwa IA', 'IA', 'iowa-mahjong.html', 'ottumwa-ia-mahjong.html', 'mahjong-lessons-near-me-iowa.html'),
    ('ankeny-ia-lessons-near-me.html', 'Ankeny IA', 'IA', 'iowa-mahjong.html', 'ankeny-ia-mahjong.html', 'mahjong-lessons-near-me-iowa.html'),
    ('urbandale-ia-lessons-near-me.html', 'Urbandale IA', 'IA', 'iowa-mahjong.html', 'urbandale-ia-mahjong.html', 'mahjong-lessons-near-me-iowa.html'),
    ('west-des-moines-ia-lessons-near-me.html', 'West Des Moines', 'IA', 'iowa-mahjong.html', 'west-des-moines-ia-mahjong.html', 'mahjong-lessons-near-me-iowa.html'),
    ('council-bluffs-ia-lessons-near-me.html', 'Council Bluffs', 'IA', 'iowa-mahjong.html', 'council-bluffs-ia-mahjong.html', 'mahjong-lessons-near-me-iowa.html'),
    ('dubuque-ia-lessons-near-me.html', 'Dubuque IA', 'IA', 'iowa-mahjong.html', 'dubuque-ia-mahjong.html', 'mahjong-lessons-near-me-iowa.html'),
    ('cedar-falls-ia-lessons-near-me.html', 'Cedar Falls', 'IA', 'iowa-mahjong.html', 'cedar-falls-ia-mahjong.html', 'mahjong-lessons-near-me-iowa.html'),
    ('coralville-ia-lessons-near-me.html', 'Coralville IA', 'IA', 'iowa-mahjong.html', 'coralville-ia-mahjong.html', 'mahjong-lessons-near-me-iowa.html'),
    ('north-liberty-ia-lessons-near-me.html', 'North Liberty', 'IA', 'iowa-mahjong.html', 'north-liberty-ia-mahjong.html', 'mahjong-lessons-near-me-iowa.html'),
    ('johnston-ia-lessons-near-me.html', 'Johnston IA', 'IA', 'iowa-mahjong.html', 'johnston-ia-mahjong.html', 'mahjong-lessons-near-me-iowa.html'),
    ('altoona-ia-lessons-near-me.html', 'Altoona IA', 'IA', 'iowa-mahjong.html', 'altoona-ia-mahjong.html', 'mahjong-lessons-near-me-iowa.html'),
    ('manhattan-ks-lessons-near-me.html', 'Manhattan KS', 'KS', 'kansas-mahjong.html', 'manhattan-ks-mahjong.html', 'mahjong-lessons-near-me-kansas.html'),
    ('hutchinson-ks-lessons-near-me.html', 'Hutchinson KS', 'KS', 'kansas-mahjong.html', 'hutchinson-ks-mahjong.html', 'mahjong-lessons-near-me-kansas.html'),
    ('salina-ks-lessons-near-me.html', 'Salina KS', 'KS', 'kansas-mahjong.html', 'salina-ks-mahjong.html', 'mahjong-lessons-near-me-kansas.html'),
    ('hays-ks-lessons-near-me.html', 'Hays KS', 'KS', 'kansas-mahjong.html', 'hays-ks-mahjong.html', 'mahjong-lessons-near-me-kansas.html'),
    ('pittsburg-ks-lessons-near-me.html', 'Pittsburg KS', 'KS', 'kansas-mahjong.html', 'pittsburg-ks-mahjong.html', 'mahjong-lessons-near-me-kansas.html'),
    ('emporia-ks-lessons-near-me.html', 'Emporia KS', 'KS', 'kansas-mahjong.html', 'emporia-ks-mahjong.html', 'mahjong-lessons-near-me-kansas.html'),
    ('dodge-city-ks-lessons-near-me.html', 'Dodge City', 'KS', 'kansas-mahjong.html', 'dodge-city-ks-mahjong.html', 'mahjong-lessons-near-me-kansas.html'),
    ('garden-city-ks-lessons-near-me.html', 'Garden City', 'KS', 'kansas-mahjong.html', 'garden-city-ks-mahjong.html', 'mahjong-lessons-near-me-kansas.html'),
    ('liberal-ks-lessons-near-me.html', 'Liberal KS', 'KS', 'kansas-mahjong.html', 'liberal-ks-mahjong.html', 'mahjong-lessons-near-me-kansas.html'),
    ('great-bend-ks-lessons-near-me.html', 'Great Bend', 'KS', 'kansas-mahjong.html', 'great-bend-ks-mahjong.html', 'mahjong-lessons-near-me-kansas.html'),
    ('junction-city-ks-lessons-near-me.html', 'Junction City', 'KS', 'kansas-mahjong.html', 'junction-city-ks-mahjong.html', 'mahjong-lessons-near-me-kansas.html'),
    ('leavenworth-ks-lessons-near-me.html', 'Leavenworth KS', 'KS', 'kansas-mahjong.html', 'leavenworth-ks-mahjong.html', 'mahjong-lessons-near-me-kansas.html'),
    ('shawnee-ks-lessons-near-me.html', 'Shawnee KS', 'KS', 'kansas-mahjong.html', 'shawnee-ks-mahjong.html', 'mahjong-lessons-near-me-kansas.html'),
    ('lenexa-ks-lessons-near-me.html', 'Lenexa KS', 'KS', 'kansas-mahjong.html', 'lenexa-ks-mahjong.html', 'mahjong-lessons-near-me-kansas.html'),
    ('olathe-ks-lessons-near-me.html', 'Olathe KS', 'KS', 'kansas-mahjong.html', 'olathe-ks-mahjong.html', 'mahjong-lessons-near-me-kansas.html'),
    ('haysville-ks-lessons-near-me.html', 'Haysville KS', 'KS', 'kansas-mahjong.html', 'haysville-ks-mahjong.html', 'mahjong-lessons-near-me-kansas.html'),
    ('derby-ks-lessons-near-me.html', 'Derby KS', 'KS', 'kansas-mahjong.html', 'derby-ks-mahjong.html', 'mahjong-lessons-near-me-kansas.html'),
    ('arkansas-city-ks-lessons-near-me.html', 'Arkansas City', 'KS', 'kansas-mahjong.html', 'arkansas-city-ks-mahjong.html', 'mahjong-lessons-near-me-kansas.html'),
    ('newton-ks-lessons-near-me.html', 'Newton KS', 'KS', 'kansas-mahjong.html', 'newton-ks-mahjong.html', 'mahjong-lessons-near-me-kansas.html'),
    ('mcpherson-ks-lessons-near-me.html', 'McPherson KS', 'KS', 'kansas-mahjong.html', 'mcpherson-ks-mahjong.html', 'mahjong-lessons-near-me-kansas.html'),
    ('richmond-ky-lessons-near-me.html', 'Richmond KY', 'KY', 'kentucky-mahjong.html', 'richmond-ky-mahjong.html', 'mahjong-lessons-near-me-kentucky.html'),
    ('florence-ky-lessons-near-me.html', 'Florence KY', 'KY', 'kentucky-mahjong.html', 'florence-ky-mahjong.html', 'mahjong-lessons-near-me-kentucky.html'),
    ('covington-ky-lessons-near-me.html', 'Covington KY', 'KY', 'kentucky-mahjong.html', 'covington-ky-mahjong.html', 'mahjong-lessons-near-me-kentucky.html'),
    ('georgetown-ky-lessons-near-me.html', 'Georgetown KY', 'KY', 'kentucky-mahjong.html', 'georgetown-ky-mahjong.html', 'mahjong-lessons-near-me-kentucky.html'),
    ('hopkinsville-ky-lessons-near-me.html', 'Hopkinsville KY', 'KY', 'kentucky-mahjong.html', 'hopkinsville-ky-mahjong.html', 'mahjong-lessons-near-me-kentucky.html'),
    ('paducah-ky-lessons-near-me.html', 'Paducah KY', 'KY', 'kentucky-mahjong.html', 'paducah-ky-mahjong.html', 'mahjong-lessons-near-me-kentucky.html'),
    ('elizabethtown-ky-lessons-near-me.html', 'Elizabethtown', 'KY', 'kentucky-mahjong.html', 'elizabethtown-ky-mahjong.html', 'mahjong-lessons-near-me-kentucky.html'),
    ('ashland-ky-lessons-near-me.html', 'Ashland KY', 'KY', 'kentucky-mahjong.html', 'ashland-ky-mahjong.html', 'mahjong-lessons-near-me-kentucky.html'),
    ('somerset-ky-lessons-near-me.html', 'Somerset KY', 'KY', 'kentucky-mahjong.html', 'somerset-ky-mahjong.html', 'mahjong-lessons-near-me-kentucky.html'),
    ('frankfort-ky-lessons-near-me.html', 'Frankfort KY', 'KY', 'kentucky-mahjong.html', 'frankfort-ky-mahjong.html', 'mahjong-lessons-near-me-kentucky.html'),
    ('henderson-ky-lessons-near-me.html', 'Henderson KY', 'KY', 'kentucky-mahjong.html', 'henderson-ky-mahjong.html', 'mahjong-lessons-near-me-kentucky.html'),
    ('madisonville-ky-lessons-near-me.html', 'Madisonville KY', 'KY', 'kentucky-mahjong.html', 'madisonville-ky-mahjong.html', 'mahjong-lessons-near-me-kentucky.html'),
    ('murray-ky-lessons-near-me.html', 'Murray KY', 'KY', 'kentucky-mahjong.html', 'murray-ky-mahjong.html', 'mahjong-lessons-near-me-kentucky.html'),
    ('danville-ky-lessons-near-me.html', 'Danville KY', 'KY', 'kentucky-mahjong.html', 'danville-ky-mahjong.html', 'mahjong-lessons-near-me-kentucky.html'),
    ('bardstown-ky-lessons-near-me.html', 'Bardstown KY', 'KY', 'kentucky-mahjong.html', 'bardstown-ky-mahjong.html', 'mahjong-lessons-near-me-kentucky.html'),
    ('shelbyville-ky-lessons-near-me.html', 'Shelbyville KY', 'KY', 'kentucky-mahjong.html', 'shelbyville-ky-mahjong.html', 'mahjong-lessons-near-me-kentucky.html'),
    ('nicholasville-ky-lessons-near-me.html', 'Nicholasville', 'KY', 'kentucky-mahjong.html', 'nicholasville-ky-mahjong.html', 'mahjong-lessons-near-me-kentucky.html'),
    ('winchester-ky-lessons-near-me.html', 'Winchester KY', 'KY', 'kentucky-mahjong.html', 'winchester-ky-mahjong.html', 'mahjong-lessons-near-me-kentucky.html'),
    ('maysville-ky-lessons-near-me.html', 'Maysville KY', 'KY', 'kentucky-mahjong.html', 'maysville-ky-mahjong.html', 'mahjong-lessons-near-me-kentucky.html'),
    ('lafayette-la-lessons-near-me.html', 'Lafayette LA', 'LA', 'louisiana-mahjong.html', 'lafayette-la-mahjong.html', 'mahjong-lessons-near-me-louisiana.html'),
    ('alexandria-la-lessons-near-me.html', 'Alexandria LA', 'LA', 'louisiana-mahjong.html', 'alexandria-la-mahjong.html', 'mahjong-lessons-near-me-louisiana.html'),
    ('houma-la-lessons-near-me.html', 'Houma LA', 'LA', 'louisiana-mahjong.html', 'houma-la-mahjong.html', 'mahjong-lessons-near-me-louisiana.html'),
    ('thibodaux-la-lessons-near-me.html', 'Thibodaux LA', 'LA', 'louisiana-mahjong.html', 'thibodaux-la-mahjong.html', 'mahjong-lessons-near-me-louisiana.html'),
    ('slidell-la-lessons-near-me.html', 'Slidell LA', 'LA', 'louisiana-mahjong.html', 'slidell-la-mahjong.html', 'mahjong-lessons-near-me-louisiana.html'),
    ('hammond-la-lessons-near-me.html', 'Hammond LA', 'LA', 'louisiana-mahjong.html', 'hammond-la-mahjong.html', 'mahjong-lessons-near-me-louisiana.html'),
    ('ruston-la-lessons-near-me.html', 'Ruston LA', 'LA', 'louisiana-mahjong.html', 'ruston-la-mahjong.html', 'mahjong-lessons-near-me-louisiana.html'),
    ('natchitoches-la-lessons-near-me.html', 'Natchitoches LA', 'LA', 'louisiana-mahjong.html', 'natchitoches-la-mahjong.html', 'mahjong-lessons-near-me-louisiana.html'),
    ('bossier-city-la-lessons-near-me.html', 'Bossier City', 'LA', 'louisiana-mahjong.html', 'bossier-city-la-mahjong.html', 'mahjong-lessons-near-me-louisiana.html'),
    ('kenner-la-lessons-near-me.html', 'Kenner LA', 'LA', 'louisiana-mahjong.html', 'kenner-la-mahjong.html', 'mahjong-lessons-near-me-louisiana.html'),
    ('marrero-la-lessons-near-me.html', 'Marrero LA', 'LA', 'louisiana-mahjong.html', 'marrero-la-mahjong.html', 'mahjong-lessons-near-me-louisiana.html'),
    ('zachary-la-lessons-near-me.html', 'Zachary LA', 'LA', 'louisiana-mahjong.html', 'zachary-la-mahjong.html', 'mahjong-lessons-near-me-louisiana.html'),
    ('sulphur-la-lessons-near-me.html', 'Sulphur LA', 'LA', 'louisiana-mahjong.html', 'sulphur-la-mahjong.html', 'mahjong-lessons-near-me-louisiana.html'),
    ('opelousas-la-lessons-near-me.html', 'Opelousas LA', 'LA', 'louisiana-mahjong.html', 'opelousas-la-mahjong.html', 'mahjong-lessons-near-me-louisiana.html'),
    ('crowley-la-lessons-near-me.html', 'Crowley LA', 'LA', 'louisiana-mahjong.html', 'crowley-la-mahjong.html', 'mahjong-lessons-near-me-louisiana.html'),
    ('minden-la-lessons-near-me.html', 'Minden LA', 'LA', 'louisiana-mahjong.html', 'minden-la-mahjong.html', 'mahjong-lessons-near-me-louisiana.html'),
    ('pineville-la-lessons-near-me.html', 'Pineville LA', 'LA', 'louisiana-mahjong.html', 'pineville-la-mahjong.html', 'mahjong-lessons-near-me-louisiana.html'),
    ('saco-me-lessons-near-me.html', 'Saco ME', 'ME', 'maine-mahjong.html', 'saco-me-mahjong.html', 'mahjong-lessons-near-me-maine.html'),
    ('sanford-me-lessons-near-me.html', 'Sanford ME', 'ME', 'maine-mahjong.html', 'sanford-me-mahjong.html', 'mahjong-lessons-near-me-maine.html'),
    ('waterville-me-lessons-near-me.html', 'Waterville ME', 'ME', 'maine-mahjong.html', 'waterville-me-mahjong.html', 'mahjong-lessons-near-me-maine.html'),
    ('presque-isle-me-lessons-near-me.html', 'Presque Isle', 'ME', 'maine-mahjong.html', 'presque-isle-me-mahjong.html', 'mahjong-lessons-near-me-maine.html'),
    ('caribou-me-lessons-near-me.html', 'Caribou ME', 'ME', 'maine-mahjong.html', 'caribou-me-mahjong.html', 'mahjong-lessons-near-me-maine.html'),
    ('brewer-me-lessons-near-me.html', 'Brewer ME', 'ME', 'maine-mahjong.html', 'brewer-me-mahjong.html', 'mahjong-lessons-near-me-maine.html'),
    ('belfast-me-lessons-near-me.html', 'Belfast ME', 'ME', 'maine-mahjong.html', 'belfast-me-mahjong.html', 'mahjong-lessons-near-me-maine.html'),
    ('camden-me-lessons-near-me.html', 'Camden ME', 'ME', 'maine-mahjong.html', 'camden-me-mahjong.html', 'mahjong-lessons-near-me-maine.html'),
    ('york-me-lessons-near-me.html', 'York ME', 'ME', 'maine-mahjong.html', 'york-me-mahjong.html', 'mahjong-lessons-near-me-maine.html'),
    ('kittery-me-lessons-near-me.html', 'Kittery ME', 'ME', 'maine-mahjong.html', 'kittery-me-mahjong.html', 'mahjong-lessons-near-me-maine.html'),
    ('scarborough-me-lessons-near-me.html', 'Scarborough ME', 'ME', 'maine-mahjong.html', 'scarborough-me-mahjong.html', 'mahjong-lessons-near-me-maine.html'),
    ('gorham-me-lessons-near-me.html', 'Gorham ME', 'ME', 'maine-mahjong.html', 'gorham-me-mahjong.html', 'mahjong-lessons-near-me-maine.html'),
    ('windham-me-lessons-near-me.html', 'Windham ME', 'ME', 'maine-mahjong.html', 'windham-me-mahjong.html', 'mahjong-lessons-near-me-maine.html'),
    ('brunswick-me-lessons-near-me.html', 'Brunswick ME', 'ME', 'maine-mahjong.html', 'brunswick-me-mahjong.html', 'mahjong-lessons-near-me-maine.html'),
    ('topsham-me-lessons-near-me.html', 'Topsham ME', 'ME', 'maine-mahjong.html', 'topsham-me-mahjong.html', 'mahjong-lessons-near-me-maine.html'),
    ('auburn-me-lessons-near-me.html', 'Auburn ME', 'ME', 'maine-mahjong.html', 'auburn-me-mahjong.html', 'mahjong-lessons-near-me-maine.html'),
    ('old-orchard-beach-me-lessons-near-me.html', 'Old Orchard Beach', 'ME', 'maine-mahjong.html', 'old-orchard-beach-me-mahjong.html', 'mahjong-lessons-near-me-maine.html'),
    ('falmouth-me-lessons-near-me.html', 'Falmouth ME', 'ME', 'maine-mahjong.html', 'falmouth-me-mahjong.html', 'mahjong-lessons-near-me-maine.html'),
    ('cape-elizabeth-me-lessons-near-me.html', 'Cape Elizabeth', 'ME', 'maine-mahjong.html', 'cape-elizabeth-me-mahjong.html', 'mahjong-lessons-near-me-maine.html'),
    ('hagerstown-md-lessons-near-me.html', 'Hagerstown MD', 'MD', 'maryland-mahjong.html', 'hagerstown-md-mahjong.html', 'mahjong-lessons-near-me-maryland.html'),
    ('salisbury-md-lessons-near-me.html', 'Salisbury MD', 'MD', 'maryland-mahjong.html', 'salisbury-md-mahjong.html', 'mahjong-lessons-near-me-maryland.html'),
    ('ocean-city-md-lessons-near-me.html', 'Ocean City', 'MD', 'maryland-mahjong.html', 'ocean-city-md-mahjong.html', 'mahjong-lessons-near-me-maryland.html'),
    ('easton-md-lessons-near-me.html', 'Easton MD', 'MD', 'maryland-mahjong.html', 'easton-md-mahjong.html', 'mahjong-lessons-near-me-maryland.html'),
    ('cambridge-md-lessons-near-me.html', 'Cambridge MD', 'MD', 'maryland-mahjong.html', 'cambridge-md-mahjong.html', 'mahjong-lessons-near-me-maryland.html'),
    ('laurel-md-lessons-near-me.html', 'Laurel MD', 'MD', 'maryland-mahjong.html', 'laurel-md-mahjong.html', 'mahjong-lessons-near-me-maryland.html'),
    ('college-park-md-lessons-near-me.html', 'College Park', 'MD', 'maryland-mahjong.html', 'college-park-md-mahjong.html', 'mahjong-lessons-near-me-maryland.html'),
    ('rockville-md-lessons-near-me.html', 'Rockville MD', 'MD', 'maryland-mahjong.html', 'rockville-md-mahjong.html', 'mahjong-lessons-near-me-maryland.html'),
    ('silver-spring-md-lessons-near-me.html', 'Silver Spring', 'MD', 'maryland-mahjong.html', 'silver-spring-md-mahjong.html', 'mahjong-lessons-near-me-maryland.html'),
    ('towson-md-lessons-near-me.html', 'Towson MD', 'MD', 'maryland-mahjong.html', 'towson-md-mahjong.html', 'mahjong-lessons-near-me-maryland.html'),
    ('ellicott-city-md-lessons-near-me.html', 'Ellicott City', 'MD', 'maryland-mahjong.html', 'ellicott-city-md-mahjong.html', 'mahjong-lessons-near-me-maryland.html'),
    ('germantown-md-lessons-near-me.html', 'Germantown MD', 'MD', 'maryland-mahjong.html', 'germantown-md-mahjong.html', 'mahjong-lessons-near-me-maryland.html'),
    ('waldorf-md-lessons-near-me.html', 'Waldorf MD', 'MD', 'maryland-mahjong.html', 'waldorf-md-mahjong.html', 'mahjong-lessons-near-me-maryland.html'),
    ('lexington-park-md-lessons-near-me.html', 'Lexington Park', 'MD', 'maryland-mahjong.html', 'lexington-park-md-mahjong.html', 'mahjong-lessons-near-me-maryland.html'),
    ('aberdeen-md-lessons-near-me.html', 'Aberdeen MD', 'MD', 'maryland-mahjong.html', 'aberdeen-md-mahjong.html', 'mahjong-lessons-near-me-maryland.html'),
    ('westminster-md-lessons-near-me.html', 'Westminster MD', 'MD', 'maryland-mahjong.html', 'westminster-md-mahjong.html', 'mahjong-lessons-near-me-maryland.html'),
    ('cumberland-md-lessons-near-me.html', 'Cumberland MD', 'MD', 'maryland-mahjong.html', 'cumberland-md-mahjong.html', 'mahjong-lessons-near-me-maryland.html'),
    ('bel-air-md-lessons-near-me.html', 'Bel Air', 'MD', 'maryland-mahjong.html', 'bel-air-md-mahjong.html', 'mahjong-lessons-near-me-maryland.html'),
    ('cambridge-ma-lessons-near-me.html', 'Cambridge MA', 'MA', 'massachusetts-mahjong.html', 'cambridge-ma-mahjong.html', 'mahjong-lessons-near-me-massachusetts.html'),
    ('somerville-ma-lessons-near-me.html', 'Somerville MA', 'MA', 'massachusetts-mahjong.html', 'somerville-ma-mahjong.html', 'mahjong-lessons-near-me-massachusetts.html'),
    ('quincy-ma-lessons-near-me.html', 'Quincy MA', 'MA', 'massachusetts-mahjong.html', 'quincy-ma-mahjong.html', 'mahjong-lessons-near-me-massachusetts.html'),
    ('framingham-ma-lessons-near-me.html', 'Framingham MA', 'MA', 'massachusetts-mahjong.html', 'framingham-ma-mahjong.html', 'mahjong-lessons-near-me-massachusetts.html'),
    ('newton-ma-lessons-near-me.html', 'Newton MA', 'MA', 'massachusetts-mahjong.html', 'newton-ma-mahjong.html', 'mahjong-lessons-near-me-massachusetts.html'),
    ('waltham-ma-lessons-near-me.html', 'Waltham MA', 'MA', 'massachusetts-mahjong.html', 'waltham-ma-mahjong.html', 'mahjong-lessons-near-me-massachusetts.html'),
    ('malden-ma-lessons-near-me.html', 'Malden MA', 'MA', 'massachusetts-mahjong.html', 'malden-ma-mahjong.html', 'mahjong-lessons-near-me-massachusetts.html'),
    ('medford-ma-lessons-near-me.html', 'Medford MA', 'MA', 'massachusetts-mahjong.html', 'medford-ma-mahjong.html', 'mahjong-lessons-near-me-massachusetts.html'),
    ('taunton-ma-lessons-near-me.html', 'Taunton MA', 'MA', 'massachusetts-mahjong.html', 'taunton-ma-mahjong.html', 'mahjong-lessons-near-me-massachusetts.html'),
    ('fall-river-ma-lessons-near-me.html', 'Fall River', 'MA', 'massachusetts-mahjong.html', 'fall-river-ma-mahjong.html', 'mahjong-lessons-near-me-massachusetts.html'),
    ('new-bedford-ma-lessons-near-me.html', 'New Bedford', 'MA', 'massachusetts-mahjong.html', 'new-bedford-ma-mahjong.html', 'mahjong-lessons-near-me-massachusetts.html'),
    ('pittsfield-ma-lessons-near-me.html', 'Pittsfield MA', 'MA', 'massachusetts-mahjong.html', 'pittsfield-ma-mahjong.html', 'mahjong-lessons-near-me-massachusetts.html'),
    ('gloucester-ma-lessons-near-me.html', 'Gloucester MA', 'MA', 'massachusetts-mahjong.html', 'gloucester-ma-mahjong.html', 'mahjong-lessons-near-me-massachusetts.html'),
    ('salem-ma-lessons-near-me.html', 'Salem MA', 'MA', 'massachusetts-mahjong.html', 'salem-ma-mahjong.html', 'mahjong-lessons-near-me-massachusetts.html'),
    ('beverly-ma-lessons-near-me.html', 'Beverly MA', 'MA', 'massachusetts-mahjong.html', 'beverly-ma-mahjong.html', 'mahjong-lessons-near-me-massachusetts.html'),
    ('hingham-ma-lessons-near-me.html', 'Hingham MA', 'MA', 'massachusetts-mahjong.html', 'hingham-ma-mahjong.html', 'mahjong-lessons-near-me-massachusetts.html'),
    ('lexington-ma-lessons-near-me.html', 'Lexington MA', 'MA', 'massachusetts-mahjong.html', 'lexington-ma-mahjong.html', 'mahjong-lessons-near-me-massachusetts.html'),
    ('concord-ma-ma-lessons-near-me.html', 'Concord MA', 'MA', 'massachusetts-mahjong.html', 'concord-ma-ma-mahjong.html', 'mahjong-lessons-near-me-massachusetts.html'),
    ('andover-ma-lessons-near-me.html', 'Andover MA', 'MA', 'massachusetts-mahjong.html', 'andover-ma-mahjong.html', 'mahjong-lessons-near-me-massachusetts.html'),
    ('natick-ma-lessons-near-me.html', 'Natick MA', 'MA', 'massachusetts-mahjong.html', 'natick-ma-mahjong.html', 'mahjong-lessons-near-me-massachusetts.html'),
    ('lansing-mi-lessons-near-me.html', 'Lansing MI', 'MI', 'michigan-mahjong.html', 'lansing-mi-mahjong.html', 'mahjong-lessons-near-me-michigan.html'),
    ('flint-mi-lessons-near-me.html', 'Flint MI', 'MI', 'michigan-mahjong.html', 'flint-mi-mahjong.html', 'mahjong-lessons-near-me-michigan.html'),
    ('saginaw-mi-lessons-near-me.html', 'Saginaw MI', 'MI', 'michigan-mahjong.html', 'saginaw-mi-mahjong.html', 'mahjong-lessons-near-me-michigan.html'),
    ('traverse-city-mi-lessons-near-me.html', 'Traverse City', 'MI', 'michigan-mahjong.html', 'traverse-city-mi-mahjong.html', 'mahjong-lessons-near-me-michigan.html'),
    ('petoskey-mi-lessons-near-me.html', 'Petoskey MI', 'MI', 'michigan-mahjong.html', 'petoskey-mi-mahjong.html', 'mahjong-lessons-near-me-michigan.html'),
    ('marquette-mi-lessons-near-me.html', 'Marquette MI', 'MI', 'michigan-mahjong.html', 'marquette-mi-mahjong.html', 'mahjong-lessons-near-me-michigan.html'),
    ('holland-mi-lessons-near-me.html', 'Holland MI', 'MI', 'michigan-mahjong.html', 'holland-mi-mahjong.html', 'mahjong-lessons-near-me-michigan.html'),
    ('muskegon-mi-lessons-near-me.html', 'Muskegon MI', 'MI', 'michigan-mahjong.html', 'muskegon-mi-mahjong.html', 'mahjong-lessons-near-me-michigan.html'),
    ('battle-creek-mi-lessons-near-me.html', 'Battle Creek', 'MI', 'michigan-mahjong.html', 'battle-creek-mi-mahjong.html', 'mahjong-lessons-near-me-michigan.html'),
    ('jackson-mi-lessons-near-me.html', 'Jackson MI', 'MI', 'michigan-mahjong.html', 'jackson-mi-mahjong.html', 'mahjong-lessons-near-me-michigan.html'),
    ('bay-city-mi-lessons-near-me.html', 'Bay City', 'MI', 'michigan-mahjong.html', 'bay-city-mi-mahjong.html', 'mahjong-lessons-near-me-michigan.html'),
    ('midland-mi-lessons-near-me.html', 'Midland MI', 'MI', 'michigan-mahjong.html', 'midland-mi-mahjong.html', 'mahjong-lessons-near-me-michigan.html'),
    ('mount-pleasant-mi-lessons-near-me.html', 'Mount Pleasant', 'MI', 'michigan-mahjong.html', 'mount-pleasant-mi-mahjong.html', 'mahjong-lessons-near-me-michigan.html'),
    ('east-lansing-mi-lessons-near-me.html', 'East Lansing', 'MI', 'michigan-mahjong.html', 'east-lansing-mi-mahjong.html', 'mahjong-lessons-near-me-michigan.html'),
    ('novi-mi-lessons-near-me.html', 'Novi MI', 'MI', 'michigan-mahjong.html', 'novi-mi-mahjong.html', 'mahjong-lessons-near-me-michigan.html'),
    ('troy-mi-lessons-near-me.html', 'Troy MI', 'MI', 'michigan-mahjong.html', 'troy-mi-mahjong.html', 'mahjong-lessons-near-me-michigan.html'),
    ('rochester-hills-mi-lessons-near-me.html', 'Rochester Hills', 'MI', 'michigan-mahjong.html', 'rochester-hills-mi-mahjong.html', 'mahjong-lessons-near-me-michigan.html'),
    ('dearborn-mi-lessons-near-me.html', 'Dearborn MI', 'MI', 'michigan-mahjong.html', 'dearborn-mi-mahjong.html', 'mahjong-lessons-near-me-michigan.html'),
    ('wyoming-mi-lessons-near-me.html', 'Wyoming MI', 'MI', 'michigan-mahjong.html', 'wyoming-mi-mahjong.html', 'mahjong-lessons-near-me-michigan.html'),
    ('kentwood-mi-lessons-near-me.html', 'Kentwood MI', 'MI', 'michigan-mahjong.html', 'kentwood-mi-mahjong.html', 'mahjong-lessons-near-me-michigan.html'),
    ('moorhead-mn-lessons-near-me.html', 'Moorhead MN', 'MN', 'minnesota-state-mahjong.html', 'moorhead-mn-mahjong.html', 'mahjong-lessons-near-me-minnesota.html'),
    ('bemidji-mn-lessons-near-me.html', 'Bemidji MN', 'MN', 'minnesota-state-mahjong.html', 'bemidji-mn-mahjong.html', 'mahjong-lessons-near-me-minnesota.html'),
    ('alexandria-mn-lessons-near-me.html', 'Alexandria MN', 'MN', 'minnesota-state-mahjong.html', 'alexandria-mn-mahjong.html', 'mahjong-lessons-near-me-minnesota.html'),
    ('willmar-mn-lessons-near-me.html', 'Willmar MN', 'MN', 'minnesota-state-mahjong.html', 'willmar-mn-mahjong.html', 'mahjong-lessons-near-me-minnesota.html'),
    ('winona-mn-lessons-near-me.html', 'Winona MN', 'MN', 'minnesota-state-mahjong.html', 'winona-mn-mahjong.html', 'mahjong-lessons-near-me-minnesota.html'),
    ('faribault-mn-lessons-near-me.html', 'Faribault MN', 'MN', 'minnesota-state-mahjong.html', 'faribault-mn-mahjong.html', 'mahjong-lessons-near-me-minnesota.html'),
    ('owatonna-mn-lessons-near-me.html', 'Owatonna MN', 'MN', 'minnesota-state-mahjong.html', 'owatonna-mn-mahjong.html', 'mahjong-lessons-near-me-minnesota.html'),
    ('hutchinson-mn-lessons-near-me.html', 'Hutchinson MN', 'MN', 'minnesota-state-mahjong.html', 'hutchinson-mn-mahjong.html', 'mahjong-lessons-near-me-minnesota.html'),
    ('brainerd-mn-lessons-near-me.html', 'Brainerd MN', 'MN', 'minnesota-state-mahjong.html', 'brainerd-mn-mahjong.html', 'mahjong-lessons-near-me-minnesota.html'),
    ('grand-rapids-mn-mn-lessons-near-me.html', 'Grand Rapids MN', 'MN', 'minnesota-state-mahjong.html', 'grand-rapids-mn-mn-mahjong.html', 'mahjong-lessons-near-me-minnesota.html'),
    ('virginia-mn-lessons-near-me.html', 'Virginia MN', 'MN', 'minnesota-state-mahjong.html', 'virginia-mn-mahjong.html', 'mahjong-lessons-near-me-minnesota.html'),
    ('hibbing-mn-lessons-near-me.html', 'Hibbing MN', 'MN', 'minnesota-state-mahjong.html', 'hibbing-mn-mahjong.html', 'mahjong-lessons-near-me-minnesota.html'),
    ('stillwater-mn-lessons-near-me.html', 'Stillwater MN', 'MN', 'minnesota-state-mahjong.html', 'stillwater-mn-mahjong.html', 'mahjong-lessons-near-me-minnesota.html'),
    ('lakeville-mn-lessons-near-me.html', 'Lakeville MN', 'MN', 'minnesota-state-mahjong.html', 'lakeville-mn-mahjong.html', 'mahjong-lessons-near-me-minnesota.html'),
    ('burnsville-mn-lessons-near-me.html', 'Burnsville MN', 'MN', 'minnesota-state-mahjong.html', 'burnsville-mn-mahjong.html', 'mahjong-lessons-near-me-minnesota.html'),
    ('eagan-mn-lessons-near-me.html', 'Eagan MN', 'MN', 'minnesota-state-mahjong.html', 'eagan-mn-mahjong.html', 'mahjong-lessons-near-me-minnesota.html'),
    ('woodbury-mn-lessons-near-me.html', 'Woodbury MN', 'MN', 'minnesota-state-mahjong.html', 'woodbury-mn-mahjong.html', 'mahjong-lessons-near-me-minnesota.html'),
    ('tupelo-ms-lessons-near-me.html', 'Tupelo MS', 'MS', 'mississippi-mahjong.html', 'tupelo-ms-mahjong.html', 'mahjong-lessons-near-me-mississippi.html'),
    ('greenville-ms-ms-lessons-near-me.html', 'Greenville MS', 'MS', 'mississippi-mahjong.html', 'greenville-ms-ms-mahjong.html', 'mahjong-lessons-near-me-mississippi.html'),
    ('oxford-ms-lessons-near-me.html', 'Oxford MS', 'MS', 'mississippi-mahjong.html', 'oxford-ms-mahjong.html', 'mahjong-lessons-near-me-mississippi.html'),
    ('starkville-ms-lessons-near-me.html', 'Starkville MS', 'MS', 'mississippi-mahjong.html', 'starkville-ms-mahjong.html', 'mahjong-lessons-near-me-mississippi.html'),
    ('columbus-ms-ms-lessons-near-me.html', 'Columbus MS', 'MS', 'mississippi-mahjong.html', 'columbus-ms-ms-mahjong.html', 'mahjong-lessons-near-me-mississippi.html'),
    ('vicksburg-ms-lessons-near-me.html', 'Vicksburg MS', 'MS', 'mississippi-mahjong.html', 'vicksburg-ms-mahjong.html', 'mahjong-lessons-near-me-mississippi.html'),
    ('natchez-ms-lessons-near-me.html', 'Natchez MS', 'MS', 'mississippi-mahjong.html', 'natchez-ms-mahjong.html', 'mahjong-lessons-near-me-mississippi.html'),
    ('laurel-ms-ms-lessons-near-me.html', 'Laurel MS', 'MS', 'mississippi-mahjong.html', 'laurel-ms-ms-mahjong.html', 'mahjong-lessons-near-me-mississippi.html'),
    ('mccomb-ms-lessons-near-me.html', 'McComb MS', 'MS', 'mississippi-mahjong.html', 'mccomb-ms-mahjong.html', 'mahjong-lessons-near-me-mississippi.html'),
    ('corinth-ms-lessons-near-me.html', 'Corinth MS', 'MS', 'mississippi-mahjong.html', 'corinth-ms-mahjong.html', 'mahjong-lessons-near-me-mississippi.html'),
    ('cleveland-ms-ms-lessons-near-me.html', 'Cleveland MS', 'MS', 'mississippi-mahjong.html', 'cleveland-ms-ms-mahjong.html', 'mahjong-lessons-near-me-mississippi.html'),
    ('greenwood-ms-ms-lessons-near-me.html', 'Greenwood MS', 'MS', 'mississippi-mahjong.html', 'greenwood-ms-ms-mahjong.html', 'mahjong-lessons-near-me-mississippi.html'),
    ('clarksdale-ms-lessons-near-me.html', 'Clarksdale MS', 'MS', 'mississippi-mahjong.html', 'clarksdale-ms-mahjong.html', 'mahjong-lessons-near-me-mississippi.html'),
    ('indianola-ms-lessons-near-me.html', 'Indianola MS', 'MS', 'mississippi-mahjong.html', 'indianola-ms-mahjong.html', 'mahjong-lessons-near-me-mississippi.html'),
    ('brookhaven-ms-lessons-near-me.html', 'Brookhaven MS', 'MS', 'mississippi-mahjong.html', 'brookhaven-ms-mahjong.html', 'mahjong-lessons-near-me-mississippi.html'),
    ('picayune-ms-lessons-near-me.html', 'Picayune MS', 'MS', 'mississippi-mahjong.html', 'picayune-ms-mahjong.html', 'mahjong-lessons-near-me-mississippi.html'),
    ('ocean-springs-ms-lessons-near-me.html', 'Ocean Springs', 'MS', 'mississippi-mahjong.html', 'ocean-springs-ms-mahjong.html', 'mahjong-lessons-near-me-mississippi.html'),
    ('pascagoula-ms-lessons-near-me.html', 'Pascagoula MS', 'MS', 'mississippi-mahjong.html', 'pascagoula-ms-mahjong.html', 'mahjong-lessons-near-me-mississippi.html'),
    ('bay-st-louis-ms-lessons-near-me.html', 'Bay St Louis', 'MS', 'mississippi-mahjong.html', 'bay-st-louis-ms-mahjong.html', 'mahjong-lessons-near-me-mississippi.html'),
    ('pass-christian-ms-lessons-near-me.html', 'Pass Christian', 'MS', 'mississippi-mahjong.html', 'pass-christian-ms-mahjong.html', 'mahjong-lessons-near-me-mississippi.html'),
    ('independence-mo-lessons-near-me.html', 'Independence MO', 'MO', 'missouri-mahjong.html', 'independence-mo-mahjong.html', 'mahjong-lessons-near-me-missouri.html'),
    ('lees-summit-mo-lessons-near-me.html', "Lee's Summit", 'MO', 'missouri-mahjong.html', 'lees-summit-mo-mahjong.html', 'mahjong-lessons-near-me-missouri.html'),
    ('blue-springs-mo-lessons-near-me.html', 'Blue Springs', 'MO', 'missouri-mahjong.html', 'blue-springs-mo-mahjong.html', 'mahjong-lessons-near-me-missouri.html'),
    ('jefferson-city-mo-lessons-near-me.html', 'Jefferson City', 'MO', 'missouri-mahjong.html', 'jefferson-city-mo-mahjong.html', 'mahjong-lessons-near-me-missouri.html'),
    ('joplin-mo-lessons-near-me.html', 'Joplin MO', 'MO', 'missouri-mahjong.html', 'joplin-mo-mahjong.html', 'mahjong-lessons-near-me-missouri.html'),
    ('branson-mo-lessons-near-me.html', 'Branson MO', 'MO', 'missouri-mahjong.html', 'branson-mo-mahjong.html', 'mahjong-lessons-near-me-missouri.html'),
    ('lake-ozark-mo-lessons-near-me.html', 'Lake Ozark', 'MO', 'missouri-mahjong.html', 'lake-ozark-mo-mahjong.html', 'mahjong-lessons-near-me-missouri.html'),
    ('sedalia-mo-lessons-near-me.html', 'Sedalia MO', 'MO', 'missouri-mahjong.html', 'sedalia-mo-mahjong.html', 'mahjong-lessons-near-me-missouri.html'),
    ('warrensburg-mo-lessons-near-me.html', 'Warrensburg MO', 'MO', 'missouri-mahjong.html', 'warrensburg-mo-mahjong.html', 'mahjong-lessons-near-me-missouri.html'),
    ('kirksville-mo-lessons-near-me.html', 'Kirksville MO', 'MO', 'missouri-mahjong.html', 'kirksville-mo-mahjong.html', 'mahjong-lessons-near-me-missouri.html'),
    ('rolla-mo-lessons-near-me.html', 'Rolla MO', 'MO', 'missouri-mahjong.html', 'rolla-mo-mahjong.html', 'mahjong-lessons-near-me-missouri.html'),
    ('poplar-bluff-mo-lessons-near-me.html', 'Poplar Bluff', 'MO', 'missouri-mahjong.html', 'poplar-bluff-mo-mahjong.html', 'mahjong-lessons-near-me-missouri.html'),
    ('cape-girardeau-mo-lessons-near-me.html', 'Cape Girardeau', 'MO', 'missouri-mahjong.html', 'cape-girardeau-mo-mahjong.html', 'mahjong-lessons-near-me-missouri.html'),
    ('sikeston-mo-lessons-near-me.html', 'Sikeston MO', 'MO', 'missouri-mahjong.html', 'sikeston-mo-mahjong.html', 'mahjong-lessons-near-me-missouri.html'),
    ('hannibal-mo-lessons-near-me.html', 'Hannibal MO', 'MO', 'missouri-mahjong.html', 'hannibal-mo-mahjong.html', 'mahjong-lessons-near-me-missouri.html'),
    ('nixa-mo-lessons-near-me.html', 'Nixa MO', 'MO', 'missouri-mahjong.html', 'nixa-mo-mahjong.html', 'mahjong-lessons-near-me-missouri.html'),
    ('ozark-mo-lessons-near-me.html', 'Ozark MO', 'MO', 'missouri-mahjong.html', 'ozark-mo-mahjong.html', 'mahjong-lessons-near-me-missouri.html'),
    ('chesterfield-mo-lessons-near-me.html', 'Chesterfield MO', 'MO', 'missouri-mahjong.html', 'chesterfield-mo-mahjong.html', 'mahjong-lessons-near-me-missouri.html'),
    ('florissant-mo-lessons-near-me.html', 'Florissant MO', 'MO', 'missouri-mahjong.html', 'florissant-mo-mahjong.html', 'mahjong-lessons-near-me-missouri.html'),
    ('butte-mt-lessons-near-me.html', 'Butte MT', 'MT', 'montana-mahjong.html', 'butte-mt-mahjong.html', 'mahjong-lessons-near-me-montana.html'),
    ('kalispell-mt-lessons-near-me.html', 'Kalispell MT', 'MT', 'montana-mahjong.html', 'kalispell-mt-mahjong.html', 'mahjong-lessons-near-me-montana.html'),
    ('whitefish-mt-lessons-near-me.html', 'Whitefish MT', 'MT', 'montana-mahjong.html', 'whitefish-mt-mahjong.html', 'mahjong-lessons-near-me-montana.html'),
    ('havre-mt-lessons-near-me.html', 'Havre MT', 'MT', 'montana-mahjong.html', 'havre-mt-mahjong.html', 'mahjong-lessons-near-me-montana.html'),
    ('miles-city-mt-lessons-near-me.html', 'Miles City', 'MT', 'montana-mahjong.html', 'miles-city-mt-mahjong.html', 'mahjong-lessons-near-me-montana.html'),
    ('livingston-mt-lessons-near-me.html', 'Livingston MT', 'MT', 'montana-mahjong.html', 'livingston-mt-mahjong.html', 'mahjong-lessons-near-me-montana.html'),
    ('hamilton-mt-lessons-near-me.html', 'Hamilton MT', 'MT', 'montana-mahjong.html', 'hamilton-mt-mahjong.html', 'mahjong-lessons-near-me-montana.html'),
    ('polson-mt-lessons-near-me.html', 'Polson MT', 'MT', 'montana-mahjong.html', 'polson-mt-mahjong.html', 'mahjong-lessons-near-me-montana.html'),
    ('lewistown-mt-lessons-near-me.html', 'Lewistown MT', 'MT', 'montana-mahjong.html', 'lewistown-mt-mahjong.html', 'mahjong-lessons-near-me-montana.html'),
    ('glendive-mt-lessons-near-me.html', 'Glendive MT', 'MT', 'montana-mahjong.html', 'glendive-mt-mahjong.html', 'mahjong-lessons-near-me-montana.html'),
    ('sidney-mt-lessons-near-me.html', 'Sidney MT', 'MT', 'montana-mahjong.html', 'sidney-mt-mahjong.html', 'mahjong-lessons-near-me-montana.html'),
    ('dillon-mt-lessons-near-me.html', 'Dillon MT', 'MT', 'montana-mahjong.html', 'dillon-mt-mahjong.html', 'mahjong-lessons-near-me-montana.html'),
    ('anaconda-mt-lessons-near-me.html', 'Anaconda MT', 'MT', 'montana-mahjong.html', 'anaconda-mt-mahjong.html', 'mahjong-lessons-near-me-montana.html'),
    ('red-lodge-mt-lessons-near-me.html', 'Red Lodge', 'MT', 'montana-mahjong.html', 'red-lodge-mt-mahjong.html', 'mahjong-lessons-near-me-montana.html'),
    ('columbia-falls-mt-lessons-near-me.html', 'Columbia Falls', 'MT', 'montana-mahjong.html', 'columbia-falls-mt-mahjong.html', 'mahjong-lessons-near-me-montana.html'),
    ('big-sky-mt-lessons-near-me.html', 'Big Sky', 'MT', 'montana-mahjong.html', 'big-sky-mt-mahjong.html', 'mahjong-lessons-near-me-montana.html'),
    ('laurel-mt-mt-lessons-near-me.html', 'Laurel MT', 'MT', 'montana-mahjong.html', 'laurel-mt-mt-mahjong.html', 'mahjong-lessons-near-me-montana.html'),
    ('north-platte-ne-lessons-near-me.html', 'North Platte', 'NE', 'nebraska-mahjong.html', 'north-platte-ne-mahjong.html', 'mahjong-lessons-near-me-nebraska.html'),
    ('scottsbluff-ne-lessons-near-me.html', 'Scottsbluff NE', 'NE', 'nebraska-mahjong.html', 'scottsbluff-ne-mahjong.html', 'mahjong-lessons-near-me-nebraska.html'),
    ('alliance-ne-lessons-near-me.html', 'Alliance NE', 'NE', 'nebraska-mahjong.html', 'alliance-ne-mahjong.html', 'mahjong-lessons-near-me-nebraska.html'),
    ('norfolk-ne-lessons-near-me.html', 'Norfolk NE', 'NE', 'nebraska-mahjong.html', 'norfolk-ne-mahjong.html', 'mahjong-lessons-near-me-nebraska.html'),
    ('columbus-ne-ne-lessons-near-me.html', 'Columbus NE', 'NE', 'nebraska-mahjong.html', 'columbus-ne-ne-mahjong.html', 'mahjong-lessons-near-me-nebraska.html'),
    ('fremont-ne-lessons-near-me.html', 'Fremont NE', 'NE', 'nebraska-mahjong.html', 'fremont-ne-mahjong.html', 'mahjong-lessons-near-me-nebraska.html'),
    ('papillion-ne-lessons-near-me.html', 'Papillion NE', 'NE', 'nebraska-mahjong.html', 'papillion-ne-mahjong.html', 'mahjong-lessons-near-me-nebraska.html'),
    ('la-vista-ne-lessons-near-me.html', 'La Vista', 'NE', 'nebraska-mahjong.html', 'la-vista-ne-mahjong.html', 'mahjong-lessons-near-me-nebraska.html'),
    ('hastings-ne-lessons-near-me.html', 'Hastings NE', 'NE', 'nebraska-mahjong.html', 'hastings-ne-mahjong.html', 'mahjong-lessons-near-me-nebraska.html'),
    ('beatrice-ne-lessons-near-me.html', 'Beatrice NE', 'NE', 'nebraska-mahjong.html', 'beatrice-ne-mahjong.html', 'mahjong-lessons-near-me-nebraska.html'),
    ('mccook-ne-lessons-near-me.html', 'McCook NE', 'NE', 'nebraska-mahjong.html', 'mccook-ne-mahjong.html', 'mahjong-lessons-near-me-nebraska.html'),
    ('sidney-ne-ne-lessons-near-me.html', 'Sidney NE', 'NE', 'nebraska-mahjong.html', 'sidney-ne-ne-mahjong.html', 'mahjong-lessons-near-me-nebraska.html'),
    ('york-ne-ne-lessons-near-me.html', 'York NE', 'NE', 'nebraska-mahjong.html', 'york-ne-ne-mahjong.html', 'mahjong-lessons-near-me-nebraska.html'),
    ('lexington-ne-ne-lessons-near-me.html', 'Lexington NE', 'NE', 'nebraska-mahjong.html', 'lexington-ne-ne-mahjong.html', 'mahjong-lessons-near-me-nebraska.html'),
    ('holdrege-ne-lessons-near-me.html', 'Holdrege NE', 'NE', 'nebraska-mahjong.html', 'holdrege-ne-mahjong.html', 'mahjong-lessons-near-me-nebraska.html'),
    ('chadron-ne-lessons-near-me.html', 'Chadron NE', 'NE', 'nebraska-mahjong.html', 'chadron-ne-mahjong.html', 'mahjong-lessons-near-me-nebraska.html'),
    ('wayne-ne-lessons-near-me.html', 'Wayne NE', 'NE', 'nebraska-mahjong.html', 'wayne-ne-mahjong.html', 'mahjong-lessons-near-me-nebraska.html'),
    ('carson-city-nv-lessons-near-me.html', 'Carson City', 'NV', 'nevada-mahjong.html', 'carson-city-nv-mahjong.html', 'mahjong-lessons-near-me-nevada.html'),
    ('sparks-nv-lessons-near-me.html', 'Sparks NV', 'NV', 'nevada-mahjong.html', 'sparks-nv-mahjong.html', 'mahjong-lessons-near-me-nevada.html'),
    ('elko-nv-lessons-near-me.html', 'Elko NV', 'NV', 'nevada-mahjong.html', 'elko-nv-mahjong.html', 'mahjong-lessons-near-me-nevada.html'),
    ('mesquite-nv-lessons-near-me.html', 'Mesquite NV', 'NV', 'nevada-mahjong.html', 'mesquite-nv-mahjong.html', 'mahjong-lessons-near-me-nevada.html'),
    ('boulder-city-nv-lessons-near-me.html', 'Boulder City', 'NV', 'nevada-mahjong.html', 'boulder-city-nv-mahjong.html', 'mahjong-lessons-near-me-nevada.html'),
    ('pahrump-nv-lessons-near-me.html', 'Pahrump NV', 'NV', 'nevada-mahjong.html', 'pahrump-nv-mahjong.html', 'mahjong-lessons-near-me-nevada.html'),
    ('fallon-nv-lessons-near-me.html', 'Fallon NV', 'NV', 'nevada-mahjong.html', 'fallon-nv-mahjong.html', 'mahjong-lessons-near-me-nevada.html'),
    ('winnemucca-nv-lessons-near-me.html', 'Winnemucca NV', 'NV', 'nevada-mahjong.html', 'winnemucca-nv-mahjong.html', 'mahjong-lessons-near-me-nevada.html'),
    ('fernley-nv-lessons-near-me.html', 'Fernley NV', 'NV', 'nevada-mahjong.html', 'fernley-nv-mahjong.html', 'mahjong-lessons-near-me-nevada.html'),
    ('minden-nv-lessons-near-me.html', 'Minden NV', 'NV', 'nevada-mahjong.html', 'minden-nv-mahjong.html', 'mahjong-lessons-near-me-nevada.html'),
    ('incline-village-nv-lessons-near-me.html', 'Incline Village', 'NV', 'nevada-mahjong.html', 'incline-village-nv-mahjong.html', 'mahjong-lessons-near-me-nevada.html'),
    ('stateline-nv-lessons-near-me.html', 'Stateline NV', 'NV', 'nevada-mahjong.html', 'stateline-nv-mahjong.html', 'mahjong-lessons-near-me-nevada.html'),
    ('laughlin-nv-lessons-near-me.html', 'Laughlin NV', 'NV', 'nevada-mahjong.html', 'laughlin-nv-mahjong.html', 'mahjong-lessons-near-me-nevada.html'),
    ('north-las-vegas-nv-lessons-near-me.html', 'North Las Vegas', 'NV', 'nevada-mahjong.html', 'north-las-vegas-nv-mahjong.html', 'mahjong-lessons-near-me-nevada.html'),
    ('summerlin-nv-lessons-near-me.html', 'Summerlin NV', 'NV', 'nevada-mahjong.html', 'summerlin-nv-mahjong.html', 'mahjong-lessons-near-me-nevada.html'),
    ('spring-valley-nv-lessons-near-me.html', 'Spring Valley', 'NV', 'nevada-mahjong.html', 'spring-valley-nv-mahjong.html', 'mahjong-lessons-near-me-nevada.html'),
    ('enterprise-nv-nv-lessons-near-me.html', 'Enterprise NV', 'NV', 'nevada-mahjong.html', 'enterprise-nv-nv-mahjong.html', 'mahjong-lessons-near-me-nevada.html'),
    ('virginia-city-nv-lessons-near-me.html', 'Virginia City', 'NV', 'nevada-mahjong.html', 'virginia-city-nv-mahjong.html', 'mahjong-lessons-near-me-nevada.html'),
    ('dover-nh-lessons-near-me.html', 'Dover NH', 'NH', 'new-hampshire-mahjong.html', 'dover-nh-mahjong.html', 'mahjong-lessons-near-me-new hampshire.html'),
    ('rochester-nh-nh-lessons-near-me.html', 'Rochester NH', 'NH', 'new-hampshire-mahjong.html', 'rochester-nh-nh-mahjong.html', 'mahjong-lessons-near-me-new hampshire.html'),
    ('laconia-nh-lessons-near-me.html', 'Laconia NH', 'NH', 'new-hampshire-mahjong.html', 'laconia-nh-mahjong.html', 'mahjong-lessons-near-me-new hampshire.html'),
    ('claremont-nh-lessons-near-me.html', 'Claremont NH', 'NH', 'new-hampshire-mahjong.html', 'claremont-nh-mahjong.html', 'mahjong-lessons-near-me-new hampshire.html'),
    ('berlin-nh-nh-lessons-near-me.html', 'Berlin NH', 'NH', 'new-hampshire-mahjong.html', 'berlin-nh-nh-mahjong.html', 'mahjong-lessons-near-me-new hampshire.html'),
    ('littleton-nh-lessons-near-me.html', 'Littleton NH', 'NH', 'new-hampshire-mahjong.html', 'littleton-nh-mahjong.html', 'mahjong-lessons-near-me-new hampshire.html'),
    ('hampton-nh-lessons-near-me.html', 'Hampton NH', 'NH', 'new-hampshire-mahjong.html', 'hampton-nh-mahjong.html', 'mahjong-lessons-near-me-new hampshire.html'),
    ('rye-nh-lessons-near-me.html', 'Rye NH', 'NH', 'new-hampshire-mahjong.html', 'rye-nh-mahjong.html', 'mahjong-lessons-near-me-new hampshire.html'),
    ('durham-nh-lessons-near-me.html', 'Durham NH', 'NH', 'new-hampshire-mahjong.html', 'durham-nh-mahjong.html', 'mahjong-lessons-near-me-new hampshire.html'),
    ('hudson-nh-nh-lessons-near-me.html', 'Hudson NH', 'NH', 'new-hampshire-mahjong.html', 'hudson-nh-nh-mahjong.html', 'mahjong-lessons-near-me-new hampshire.html'),
    ('milford-nh-nh-lessons-near-me.html', 'Milford NH', 'NH', 'new-hampshire-mahjong.html', 'milford-nh-nh-mahjong.html', 'mahjong-lessons-near-me-new hampshire.html'),
    ('amherst-nh-nh-lessons-near-me.html', 'Amherst NH', 'NH', 'new-hampshire-mahjong.html', 'amherst-nh-nh-mahjong.html', 'mahjong-lessons-near-me-new hampshire.html'),
    ('bedford-nh-nh-lessons-near-me.html', 'Bedford NH', 'NH', 'new-hampshire-mahjong.html', 'bedford-nh-nh-mahjong.html', 'mahjong-lessons-near-me-new hampshire.html'),
    ('goffstown-nh-lessons-near-me.html', 'Goffstown NH', 'NH', 'new-hampshire-mahjong.html', 'goffstown-nh-mahjong.html', 'mahjong-lessons-near-me-new hampshire.html'),
    ('hooksett-nh-lessons-near-me.html', 'Hooksett NH', 'NH', 'new-hampshire-mahjong.html', 'hooksett-nh-mahjong.html', 'mahjong-lessons-near-me-new hampshire.html'),
    ('salem-nh-nh-lessons-near-me.html', 'Salem NH', 'NH', 'new-hampshire-mahjong.html', 'salem-nh-nh-mahjong.html', 'mahjong-lessons-near-me-new hampshire.html'),
    ('windham-nh-nh-lessons-near-me.html', 'Windham NH', 'NH', 'new-hampshire-mahjong.html', 'windham-nh-nh-mahjong.html', 'mahjong-lessons-near-me-new hampshire.html'),
    ('pelham-nh-lessons-near-me.html', 'Pelham NH', 'NH', 'new-hampshire-mahjong.html', 'pelham-nh-mahjong.html', 'mahjong-lessons-near-me-new hampshire.html'),
    ('londonderry-nh-lessons-near-me.html', 'Londonderry NH', 'NH', 'new-hampshire-mahjong.html', 'londonderry-nh-mahjong.html', 'mahjong-lessons-near-me-new hampshire.html'),
    ('morristown-nj-lessons-near-me.html', 'Morristown NJ', 'NJ', 'new-jersey-mahjong.html', 'morristown-nj-mahjong.html', 'mahjong-lessons-near-me-new jersey.html'),
    ('montclair-nj-lessons-near-me.html', 'Montclair NJ', 'NJ', 'new-jersey-mahjong.html', 'montclair-nj-mahjong.html', 'mahjong-lessons-near-me-new jersey.html'),
    ('ridgewood-nj-lessons-near-me.html', 'Ridgewood NJ', 'NJ', 'new-jersey-mahjong.html', 'ridgewood-nj-mahjong.html', 'mahjong-lessons-near-me-new jersey.html'),
    ('summit-nj-lessons-near-me.html', 'Summit NJ', 'NJ', 'new-jersey-mahjong.html', 'summit-nj-mahjong.html', 'mahjong-lessons-near-me-new jersey.html'),
    ('westfield-nj-lessons-near-me.html', 'Westfield NJ', 'NJ', 'new-jersey-mahjong.html', 'westfield-nj-mahjong.html', 'mahjong-lessons-near-me-new jersey.html'),
    ('red-bank-nj-lessons-near-me.html', 'Red Bank', 'NJ', 'new-jersey-mahjong.html', 'red-bank-nj-mahjong.html', 'mahjong-lessons-near-me-new jersey.html'),
    ('toms-river-nj-lessons-near-me.html', 'Toms River', 'NJ', 'new-jersey-mahjong.html', 'toms-river-nj-mahjong.html', 'mahjong-lessons-near-me-new jersey.html'),
    ('brick-nj-lessons-near-me.html', 'Brick NJ', 'NJ', 'new-jersey-mahjong.html', 'brick-nj-mahjong.html', 'mahjong-lessons-near-me-new jersey.html'),
    ('cherry-hill-nj-lessons-near-me.html', 'Cherry Hill', 'NJ', 'new-jersey-mahjong.html', 'cherry-hill-nj-mahjong.html', 'mahjong-lessons-near-me-new jersey.html'),
    ('voorhees-nj-lessons-near-me.html', 'Voorhees NJ', 'NJ', 'new-jersey-mahjong.html', 'voorhees-nj-mahjong.html', 'mahjong-lessons-near-me-new jersey.html'),
    ('edison-nj-lessons-near-me.html', 'Edison NJ', 'NJ', 'new-jersey-mahjong.html', 'edison-nj-mahjong.html', 'mahjong-lessons-near-me-new jersey.html'),
    ('woodbridge-nj-lessons-near-me.html', 'Woodbridge NJ', 'NJ', 'new-jersey-mahjong.html', 'woodbridge-nj-mahjong.html', 'mahjong-lessons-near-me-new jersey.html'),
    ('parsippany-nj-lessons-near-me.html', 'Parsippany NJ', 'NJ', 'new-jersey-mahjong.html', 'parsippany-nj-mahjong.html', 'mahjong-lessons-near-me-new jersey.html'),
    ('wayne-nj-nj-lessons-near-me.html', 'Wayne NJ', 'NJ', 'new-jersey-mahjong.html', 'wayne-nj-nj-mahjong.html', 'mahjong-lessons-near-me-new jersey.html'),
    ('ramsey-nj-lessons-near-me.html', 'Ramsey NJ', 'NJ', 'new-jersey-mahjong.html', 'ramsey-nj-mahjong.html', 'mahjong-lessons-near-me-new jersey.html'),
    ('hackensack-nj-lessons-near-me.html', 'Hackensack NJ', 'NJ', 'new-jersey-mahjong.html', 'hackensack-nj-mahjong.html', 'mahjong-lessons-near-me-new jersey.html'),
    ('teaneck-nj-lessons-near-me.html', 'Teaneck NJ', 'NJ', 'new-jersey-mahjong.html', 'teaneck-nj-mahjong.html', 'mahjong-lessons-near-me-new jersey.html'),
    ('fort-lee-nj-lessons-near-me.html', 'Fort Lee', 'NJ', 'new-jersey-mahjong.html', 'fort-lee-nj-mahjong.html', 'mahjong-lessons-near-me-new jersey.html'),
    ('englewood-nj-lessons-near-me.html', 'Englewood NJ', 'NJ', 'new-jersey-mahjong.html', 'englewood-nj-mahjong.html', 'mahjong-lessons-near-me-new jersey.html'),
    ('ruidoso-nm-lessons-near-me.html', 'Ruidoso NM', 'NM', 'new-mexico-mahjong.html', 'ruidoso-nm-mahjong.html', 'mahjong-lessons-near-me-new mexico.html'),
    ('silver-city-nm-lessons-near-me.html', 'Silver City', 'NM', 'new-mexico-mahjong.html', 'silver-city-nm-mahjong.html', 'mahjong-lessons-near-me-new mexico.html'),
    ('gallup-nm-lessons-near-me.html', 'Gallup NM', 'NM', 'new-mexico-mahjong.html', 'gallup-nm-mahjong.html', 'mahjong-lessons-near-me-new mexico.html'),
    ('clovis-nm-nm-lessons-near-me.html', 'Clovis NM', 'NM', 'new-mexico-mahjong.html', 'clovis-nm-nm-mahjong.html', 'mahjong-lessons-near-me-new mexico.html'),
    ('portales-nm-lessons-near-me.html', 'Portales NM', 'NM', 'new-mexico-mahjong.html', 'portales-nm-mahjong.html', 'mahjong-lessons-near-me-new mexico.html'),
    ('hobbs-nm-lessons-near-me.html', 'Hobbs NM', 'NM', 'new-mexico-mahjong.html', 'hobbs-nm-mahjong.html', 'mahjong-lessons-near-me-new mexico.html'),
    ('artesia-nm-lessons-near-me.html', 'Artesia NM', 'NM', 'new-mexico-mahjong.html', 'artesia-nm-mahjong.html', 'mahjong-lessons-near-me-new mexico.html'),
    ('los-alamos-nm-lessons-near-me.html', 'Los Alamos', 'NM', 'new-mexico-mahjong.html', 'los-alamos-nm-mahjong.html', 'mahjong-lessons-near-me-new mexico.html'),
    ('espanola-nm-lessons-near-me.html', 'Espanola NM', 'NM', 'new-mexico-mahjong.html', 'espanola-nm-mahjong.html', 'mahjong-lessons-near-me-new mexico.html'),
    ('las-vegas-nm-nm-lessons-near-me.html', 'Las Vegas NM', 'NM', 'new-mexico-mahjong.html', 'las-vegas-nm-nm-mahjong.html', 'mahjong-lessons-near-me-new mexico.html'),
    ('deming-nm-lessons-near-me.html', 'Deming NM', 'NM', 'new-mexico-mahjong.html', 'deming-nm-mahjong.html', 'mahjong-lessons-near-me-new mexico.html'),
    ('socorro-nm-lessons-near-me.html', 'Socorro NM', 'NM', 'new-mexico-mahjong.html', 'socorro-nm-mahjong.html', 'mahjong-lessons-near-me-new mexico.html'),
    ('truth-or-consequences-nm-lessons-near-me.html', 'Truth or Consequences', 'NM', 'new-mexico-mahjong.html', 'truth-or-consequences-nm-mahjong.html', 'mahjong-lessons-near-me-new mexico.html'),
    ('belen-nm-lessons-near-me.html', 'Belen NM', 'NM', 'new-mexico-mahjong.html', 'belen-nm-mahjong.html', 'mahjong-lessons-near-me-new mexico.html'),
    ('los-lunas-nm-lessons-near-me.html', 'Los Lunas', 'NM', 'new-mexico-mahjong.html', 'los-lunas-nm-mahjong.html', 'mahjong-lessons-near-me-new mexico.html'),
    ('bernalillo-nm-lessons-near-me.html', 'Bernalillo NM', 'NM', 'new-mexico-mahjong.html', 'bernalillo-nm-mahjong.html', 'mahjong-lessons-near-me-new mexico.html'),
    ('corrales-nm-lessons-near-me.html', 'Corrales NM', 'NM', 'new-mexico-mahjong.html', 'corrales-nm-mahjong.html', 'mahjong-lessons-near-me-new mexico.html'),
    ('schenectady-ny-lessons-near-me.html', 'Schenectady NY', 'NY', 'new-york-mahjong.html', 'schenectady-ny-mahjong.html', 'mahjong-lessons-near-me-new york.html'),
    ('troy-ny-lessons-near-me.html', 'Troy NY', 'NY', 'new-york-mahjong.html', 'troy-ny-mahjong.html', 'mahjong-lessons-near-me-new york.html'),
    ('saratoga-springs-ny-lessons-near-me.html', 'Saratoga Springs', 'NY', 'new-york-mahjong.html', 'saratoga-springs-ny-mahjong.html', 'mahjong-lessons-near-me-new york.html'),
    ('kingston-ny-lessons-near-me.html', 'Kingston NY', 'NY', 'new-york-mahjong.html', 'kingston-ny-mahjong.html', 'mahjong-lessons-near-me-new york.html'),
    ('newburgh-ny-lessons-near-me.html', 'Newburgh NY', 'NY', 'new-york-mahjong.html', 'newburgh-ny-mahjong.html', 'mahjong-lessons-near-me-new york.html'),
    ('middletown-ny-ny-lessons-near-me.html', 'Middletown NY', 'NY', 'new-york-mahjong.html', 'middletown-ny-ny-mahjong.html', 'mahjong-lessons-near-me-new york.html'),
    ('jamestown-ny-lessons-near-me.html', 'Jamestown NY', 'NY', 'new-york-mahjong.html', 'jamestown-ny-mahjong.html', 'mahjong-lessons-near-me-new york.html'),
    ('olean-ny-lessons-near-me.html', 'Olean NY', 'NY', 'new-york-mahjong.html', 'olean-ny-mahjong.html', 'mahjong-lessons-near-me-new york.html'),
    ('canandaigua-ny-lessons-near-me.html', 'Canandaigua NY', 'NY', 'new-york-mahjong.html', 'canandaigua-ny-mahjong.html', 'mahjong-lessons-near-me-new york.html'),
    ('geneva-ny-ny-lessons-near-me.html', 'Geneva NY', 'NY', 'new-york-mahjong.html', 'geneva-ny-ny-mahjong.html', 'mahjong-lessons-near-me-new york.html'),
    ('auburn-ny-ny-lessons-near-me.html', 'Auburn NY', 'NY', 'new-york-mahjong.html', 'auburn-ny-ny-mahjong.html', 'mahjong-lessons-near-me-new york.html'),
    ('oswego-ny-lessons-near-me.html', 'Oswego NY', 'NY', 'new-york-mahjong.html', 'oswego-ny-mahjong.html', 'mahjong-lessons-near-me-new york.html'),
    ('plattsburgh-ny-lessons-near-me.html', 'Plattsburgh NY', 'NY', 'new-york-mahjong.html', 'plattsburgh-ny-mahjong.html', 'mahjong-lessons-near-me-new york.html'),
    ('glens-falls-ny-lessons-near-me.html', 'Glens Falls', 'NY', 'new-york-mahjong.html', 'glens-falls-ny-mahjong.html', 'mahjong-lessons-near-me-new york.html'),
    ('cooperstown-ny-lessons-near-me.html', 'Cooperstown NY', 'NY', 'new-york-mahjong.html', 'cooperstown-ny-mahjong.html', 'mahjong-lessons-near-me-new york.html'),
    ('oneonta-ny-lessons-near-me.html', 'Oneonta NY', 'NY', 'new-york-mahjong.html', 'oneonta-ny-mahjong.html', 'mahjong-lessons-near-me-new york.html'),
    ('cortland-ny-lessons-near-me.html', 'Cortland NY', 'NY', 'new-york-mahjong.html', 'cortland-ny-mahjong.html', 'mahjong-lessons-near-me-new york.html'),
    ('corning-ny-lessons-near-me.html', 'Corning NY', 'NY', 'new-york-mahjong.html', 'corning-ny-mahjong.html', 'mahjong-lessons-near-me-new york.html'),
    ('jacksonville-nc-nc-lessons-near-me.html', 'Jacksonville NC', 'NC', 'north-carolina-mahjong.html', 'jacksonville-nc-nc-mahjong.html', 'mahjong-lessons-near-me-north carolina.html'),
    ('goldsboro-nc-lessons-near-me.html', 'Goldsboro NC', 'NC', 'north-carolina-mahjong.html', 'goldsboro-nc-mahjong.html', 'mahjong-lessons-near-me-north carolina.html'),
    ('rocky-mount-nc-lessons-near-me.html', 'Rocky Mount', 'NC', 'north-carolina-mahjong.html', 'rocky-mount-nc-mahjong.html', 'mahjong-lessons-near-me-north carolina.html'),
    ('wilson-nc-lessons-near-me.html', 'Wilson NC', 'NC', 'north-carolina-mahjong.html', 'wilson-nc-mahjong.html', 'mahjong-lessons-near-me-north carolina.html'),
]
