# auto-generated city tuples — WAVE32_CITIES
WAVE32_CITIES = [
    ('marysville-wa-3-mahjong.html', 'Marysville WA', 'WA', 'washington-state-mahjong.html', 'washington-mahjong-hub.html'),
    ('perris-ca-3-mahjong.html', 'Perris CA', 'CA', 'california-mahjong.html', 'california-mahjong-hub.html'),
    ('cleveland-oh-4-mahjong.html', 'Cleveland OH', 'OH', 'ohio-mahjong.html', 'ohio-mahjong-hub.html'),
    ('worcester-ma-4-mahjong.html', 'Worcester MA', 'MA', 'massachusetts-mahjong.html', 'massachusetts-mahjong-hub.html'),
    ('columbia-sc-4-mahjong.html', 'Columbia SC', 'SC', 'south-carolina-mahjong.html', 'south-carolina-mahjong-hub.html'),
    ('waterbury-ct-4-mahjong.html', 'Waterbury CT', 'CT', 'connecticut-mahjong.html', 'connecticut-mahjong-hub.html'),
    ('eagan-mn-4-mahjong.html', 'Eagan MN', 'MN', 'minnesota-mahjong.html', 'minnesota-mahjong-hub.html'),
    ('southfield-mi-3-mahjong.html', 'Southfield MI', 'MI', 'michigan-mahjong.html', 'michigan-mahjong-hub.html'),
    ('lafayette-la-4-mahjong.html', 'Lafayette LA', 'LA', 'louisiana-mahjong.html', 'louisiana-mahjong-hub.html'),
    ('boise-city-id-3-mahjong.html', 'Boise City ID', 'ID', 'idaho-mahjong.html', 'idaho-mahjong-hub.html'),
    ('elkhart-in-4-mahjong.html', 'Elkhart IN', 'IN', 'indiana-mahjong.html', 'indiana-mahjong-hub.html'),
    ('buena-park-ca-3-mahjong.html', 'Buena Park CA', 'CA', 'california-mahjong.html', 'california-mahjong-hub.html'),
    ('marietta-ga-4-mahjong.html', 'Marietta GA', 'GA', 'georgia-mahjong.html', 'georgia-mahjong-hub.html'),
    ('parker-co-3-mahjong.html', 'Parker CO', 'CO', 'colorado-mahjong.html', 'colorado-mahjong-hub.html'),
    ('west-palm-beach-fl-3-mahjong.html', 'West Palm Beach FL', 'FL', 'florida-mahjong.html', 'florida-mahjong-hub.html'),
    ('salem-ma-4-mahjong.html', 'Salem MA', 'MA', 'massachusetts-mahjong.html', 'massachusetts-mahjong-hub.html'),
    ('aurora-il-4-mahjong.html', 'Aurora IL', 'IL', 'illinois-mahjong.html', 'illinois-mahjong-hub.html'),
    ('leesburg-va-4-mahjong.html', 'Leesburg VA', 'VA', 'virginia-mahjong.html', 'virginia-mahjong-hub.html'),
    ('doral-fl-3-mahjong.html', 'Doral FL', 'FL', 'florida-mahjong.html', 'florida-mahjong-hub.html'),
    ('westminster-ca-3-mahjong.html', 'Westminster CA', 'CA', 'california-mahjong.html', 'california-mahjong-hub.html'),
    ('lubbock-tx-4-mahjong.html', 'Lubbock TX', 'TX', 'texas-mahjong.html', 'texas-mahjong-hub.html'),
    ('overland-park-ks-4-mahjong.html', 'Overland Park KS', 'KS', 'kansas-mahjong.html', 'kansas-mahjong-hub.html'),
    ('jackson-ms-4-mahjong.html', 'Jackson MS', 'MS', 'mississippi-mahjong.html', 'mississippi-mahjong-hub.html'),
    ('gastonia-nc-3-mahjong.html', 'Gastonia NC', 'NC', 'north-carolina-mahjong.html', 'north-carolina-mahjong-hub.html'),
    ('daytona-beach-fl-4-mahjong.html', 'Daytona Beach FL', 'FL', 'florida-mahjong.html', 'florida-mahjong-hub.html'),
    ('kansas-city-mo-3-mahjong.html', 'Kansas City MO', 'MO', 'missouri-mahjong.html', 'missouri-mahjong-hub.html'),
    ('rancho-palos-verdes-ca-3-mahjong.html', 'Rancho Palos Verdes CA', 'CA', 'california-mahjong.html', 'california-mahjong-hub.html'),
    ('burnsville-mn-4-mahjong.html', 'Burnsville MN', 'MN', 'minnesota-mahjong.html', 'minnesota-mahjong-hub.html'),
    ('rowlett-tx-3-mahjong.html', 'Rowlett TX', 'TX', 'texas-mahjong.html', 'texas-mahjong-hub.html'),
    ('roswell-nm-4-mahjong.html', 'Roswell NM', 'NM', 'new-mexico-mahjong.html', 'new-mexico-mahjong-hub.html'),
    ('montgomery-al-4-mahjong.html', 'Montgomery AL', 'AL', 'alabama-mahjong.html', 'alabama-mahjong-hub.html'),
    ('logan-ut-4-mahjong.html', 'Logan UT', 'UT', 'utah-mahjong.html', 'utah-mahjong-hub.html'),
    ('woburn-ma-3-mahjong.html', 'Woburn MA', 'MA', 'massachusetts-mahjong.html', 'massachusetts-mahjong-hub.html'),
    ('allentown-pa-4-mahjong.html', 'Allentown PA', 'PA', 'pennsylvania-mahjong.html', 'pennsylvania-mahjong-hub.html'),
    ('mount-pleasant-sc-4-mahjong.html', 'Mount Pleasant SC', 'SC', 'south-carolina-mahjong.html', 'south-carolina-mahjong-hub.html'),
    ('columbus-ga-4-mahjong.html', 'Columbus GA', 'GA', 'georgia-mahjong.html', 'georgia-mahjong-hub.html'),
    ('buffalo-ny-4-mahjong.html', 'Buffalo NY', 'NY', 'new-york-mahjong.html', 'new-york-mahjong-hub.html'),
    ('new-berlin-wi-3-mahjong.html', 'New Berlin WI', 'WI', 'wisconsin-mahjong.html', 'wisconsin-mahjong-hub.html'),
    ('north-richland-hills-tx-3-mahjong.html', 'North Richland Hills TX', 'TX', 'texas-mahjong.html', 'texas-mahjong-hub.html'),
    ('lima-oh-4-mahjong.html', 'Lima OH', 'OH', 'ohio-mahjong.html', 'ohio-mahjong-hub.html'),
    ('sacramento-ca-3-mahjong.html', 'Sacramento CA', 'CA', 'california-mahjong.html', 'california-mahjong-hub.html'),
    ('fort-smith-ar-4-mahjong.html', 'Fort Smith AR', 'AR', 'arkansas-mahjong.html', 'arkansas-mahjong-hub.html'),
    ('east-providence-ri-4-mahjong.html', 'East Providence RI', 'RI', 'rhode-island-mahjong.html', 'rhode-island-mahjong-hub.html'),
    ('urbandale-ia-4-mahjong.html', 'Urbandale IA', 'IA', 'iowa-mahjong.html', 'iowa-mahjong-hub.html'),
    ('mount-vernon-ny-3-mahjong.html', 'Mount Vernon NY', 'NY', 'new-york-mahjong.html', 'new-york-mahjong-hub.html'),
    ('lakewood-co-4-mahjong.html', 'Lakewood CO', 'CO', 'colorado-mahjong.html', 'colorado-mahjong-hub.html'),
    ('henderson-nv-4-mahjong.html', 'Henderson NV', 'NV', 'nevada-mahjong.html', 'nevada-mahjong-hub.html'),
    ('covina-ca-3-mahjong.html', 'Covina CA', 'CA', 'california-mahjong.html', 'california-mahjong-hub.html'),
    ('stamford-ct-4-mahjong.html', 'Stamford CT', 'CT', 'connecticut-mahjong.html', 'connecticut-mahjong-hub.html'),
    ('bloomington-in-4-mahjong.html', 'Bloomington IN', 'IN', 'indiana-mahjong.html', 'indiana-mahjong-hub.html'),
    ('kingsport-tn-4-mahjong.html', 'Kingsport TN', 'TN', 'tennessee-mahjong.html', 'tennessee-mahjong-hub.html'),
    ('spokane-wa-4-mahjong.html', 'Spokane WA', 'WA', 'washington-state-mahjong.html', 'washington-mahjong-hub.html'),
    ('kennewick-wa-4-mahjong.html', 'Kennewick WA', 'WA', 'washington-state-mahjong.html', 'washington-mahjong-hub.html'),
    ('philadelphia-pa-3-mahjong.html', 'Philadelphia PA', 'PA', 'pennsylvania-mahjong.html', 'pennsylvania-mahjong-hub.html'),
    ('bellingham-wa-4-mahjong.html', 'Bellingham WA', 'WA', 'washington-state-mahjong.html', 'washington-mahjong-hub.html'),
    ('visalia-ca-4-mahjong.html', 'Visalia CA', 'CA', 'california-mahjong.html', 'california-mahjong-hub.html'),
    ('la-crosse-wi-4-mahjong.html', 'La Crosse WI', 'WI', 'wisconsin-mahjong.html', 'wisconsin-mahjong-hub.html'),
    ('council-bluffs-ia-4-mahjong.html', 'Council Bluffs IA', 'IA', 'iowa-mahjong.html', 'iowa-mahjong-hub.html'),
    ('north-lauderdale-fl-3-mahjong.html', 'North Lauderdale FL', 'FL', 'florida-mahjong.html', 'florida-mahjong-hub.html'),
    ('dallas-tx-3-mahjong.html', 'Dallas TX', 'TX', 'texas-mahjong.html', 'texas-mahjong-hub.html'),
    ('antioch-ca-4-mahjong.html', 'Antioch CA', 'CA', 'california-mahjong.html', 'california-mahjong-hub.html'),
    ('sterling-heights-mi-3-mahjong.html', 'Sterling Heights MI', 'MI', 'michigan-mahjong.html', 'michigan-mahjong-hub.html'),
    ('deerfield-beach-fl-4-mahjong.html', 'Deerfield Beach FL', 'FL', 'florida-mahjong.html', 'florida-mahjong-hub.html'),
    ('fishers-in-3-mahjong.html', 'Fishers IN', 'IN', 'indiana-mahjong.html', 'indiana-mahjong-hub.html'),
    ('cheyenne-wy-4-mahjong.html', 'Cheyenne WY', 'WY', 'wyoming-mahjong.html', 'wyoming-mahjong-hub.html'),
    ('murrieta-ca-3-mahjong.html', 'Murrieta CA', 'CA', 'california-mahjong.html', 'california-mahjong-hub.html'),
    ('lenexa-ks-4-mahjong.html', 'Lenexa KS', 'KS', 'kansas-mahjong.html', 'kansas-mahjong-hub.html'),
    ('noblesville-in-4-mahjong.html', 'Noblesville IN', 'IN', 'indiana-mahjong.html', 'indiana-mahjong-hub.html'),
    ('southaven-ms-3-mahjong.html', 'Southaven MS', 'MS', 'mississippi-mahjong.html', 'mississippi-mahjong-hub.html'),
    ('chino-ca-3-mahjong.html', 'Chino CA', 'CA', 'california-mahjong.html', 'california-mahjong-hub.html'),
    ('gaithersburg-md-3-mahjong.html', 'Gaithersburg MD', 'MD', 'maryland-mahjong.html', 'maryland-mahjong-hub.html'),
    ('fountain-valley-ca-3-mahjong.html', 'Fountain Valley CA', 'CA', 'california-mahjong.html', 'california-mahjong-hub.html'),
    ('frederick-md-4-mahjong.html', 'Frederick MD', 'MD', 'maryland-mahjong.html', 'maryland-mahjong-hub.html'),
    ('greenville-nc-4-mahjong.html', 'Greenville NC', 'NC', 'north-carolina-mahjong.html', 'north-carolina-mahjong-hub.html'),
    ('dekalb-il-3-mahjong.html', 'DeKalb IL', 'IL', 'illinois-mahjong.html', 'illinois-mahjong-hub.html'),
    ('west-allis-wi-3-mahjong.html', 'West Allis WI', 'WI', 'wisconsin-mahjong.html', 'wisconsin-mahjong-hub.html'),
    ('thornton-co-3-mahjong.html', 'Thornton CO', 'CO', 'colorado-mahjong.html', 'colorado-mahjong-hub.html'),
    ('west-des-moines-ia-4-mahjong.html', 'West Des Moines IA', 'IA', 'iowa-mahjong.html', 'iowa-mahjong-hub.html'),
    ('fall-river-ma-4-mahjong.html', 'Fall River MA', 'MA', 'massachusetts-mahjong.html', 'massachusetts-mahjong-hub.html'),
    ('tulare-ca-3-mahjong.html', 'Tulare CA', 'CA', 'california-mahjong.html', 'california-mahjong-hub.html'),
    ('chula-vista-ca-3-mahjong.html', 'Chula Vista CA', 'CA', 'california-mahjong.html', 'california-mahjong-hub.html'),
    ('coral-springs-fl-3-mahjong.html', 'Coral Springs FL', 'FL', 'florida-mahjong.html', 'florida-mahjong-hub.html'),
    ('concord-nc-4-mahjong.html', 'Concord NC', 'NC', 'north-carolina-mahjong.html', 'north-carolina-mahjong-hub.html'),
    ('smyrna-ga-3-mahjong.html', 'Smyrna GA', 'GA', 'georgia-mahjong.html', 'georgia-mahjong-hub.html'),
    ('apopka-fl-4-mahjong.html', 'Apopka FL', 'FL', 'florida-mahjong.html', 'florida-mahjong-hub.html'),
    ('grand-forks-nd-4-mahjong.html', 'Grand Forks ND', 'ND', 'north-dakota-mahjong.html', 'north-dakota-mahjong-hub.html'),
    ('lancaster-oh-3-mahjong.html', 'Lancaster OH', 'OH', 'ohio-mahjong.html', 'ohio-mahjong-hub.html'),
    ('naperville-il-4-mahjong.html', 'Naperville IL', 'IL', 'illinois-mahjong.html', 'illinois-mahjong-hub.html'),
    ('hollywood-fl-4-mahjong.html', 'Hollywood FL', 'FL', 'florida-mahjong.html', 'florida-mahjong-hub.html'),
    ('rogers-ar-4-mahjong.html', 'Rogers AR', 'AR', 'arkansas-mahjong.html', 'arkansas-mahjong-hub.html'),
    ('new-orleans-la-3-mahjong.html', 'New Orleans LA', 'LA', 'louisiana-mahjong.html', 'louisiana-mahjong-hub.html'),
    ('lakewood-wa-3-mahjong.html', 'Lakewood WA', 'WA', 'washington-state-mahjong.html', 'washington-mahjong-hub.html'),
    ('oak-lawn-il-3-mahjong.html', 'Oak Lawn IL', 'IL', 'illinois-mahjong.html', 'illinois-mahjong-hub.html'),
    ('caldwell-id-4-mahjong.html', 'Caldwell ID', 'ID', 'idaho-mahjong.html', 'idaho-mahjong-hub.html'),
    ('portland-or-3-mahjong.html', 'Portland OR', 'OR', 'oregon-mahjong.html', 'oregon-mahjong-hub.html'),
    ('concord-ca-4-mahjong.html', 'Concord CA', 'CA', 'california-mahjong.html', 'california-mahjong-hub.html'),
    ('burien-wa-3-mahjong.html', 'Burien WA', 'WA', 'washington-state-mahjong.html', 'washington-mahjong-hub.html'),
    ('st-charles-mo-3-mahjong.html', 'St. Charles MO', 'MO', 'missouri-mahjong.html', 'missouri-mahjong-hub.html'),
    ('waukesha-wi-4-mahjong.html', 'Waukesha WI', 'WI', 'wisconsin-mahjong.html', 'wisconsin-mahjong-hub.html'),
    ('flagstaff-az-4-mahjong.html', 'Flagstaff AZ', 'AZ', 'arizona-mahjong.html', 'arizona-mahjong-hub.html'),
    ('puyallup-wa-3-mahjong.html', 'Puyallup WA', 'WA', 'washington-state-mahjong.html', 'washington-mahjong-hub.html'),
    ('schenectady-ny-4-mahjong.html', 'Schenectady NY', 'NY', 'new-york-mahjong.html', 'new-york-mahjong-hub.html'),
    ('denver-co-3-mahjong.html', 'Denver CO', 'CO', 'colorado-mahjong.html', 'colorado-mahjong-hub.html'),
    ('springfield-il-4-mahjong.html', 'Springfield IL', 'IL', 'illinois-mahjong.html', 'illinois-mahjong-hub.html'),
    ('campbell-ca-3-mahjong.html', 'Campbell CA', 'CA', 'california-mahjong.html', 'california-mahjong-hub.html'),
    ('moreno-valley-ca-3-mahjong.html', 'Moreno Valley CA', 'CA', 'california-mahjong.html', 'california-mahjong-hub.html'),
    ('kettering-oh-3-mahjong.html', 'Kettering OH', 'OH', 'ohio-mahjong.html', 'ohio-mahjong-hub.html'),
    ('lincoln-park-mi-3-mahjong.html', 'Lincoln Park MI', 'MI', 'michigan-mahjong.html', 'michigan-mahjong-hub.html'),
    ('lake-havasu-city-az-4-mahjong.html', 'Lake Havasu City AZ', 'AZ', 'arizona-mahjong.html', 'arizona-mahjong-hub.html'),
    ('north-little-rock-ar-3-mahjong.html', 'North Little Rock AR', 'AR', 'arkansas-mahjong.html', 'arkansas-mahjong-hub.html'),
    ('reno-nv-4-mahjong.html', 'Reno NV', 'NV', 'nevada-mahjong.html', 'nevada-mahjong-hub.html'),
    ('littleton-co-4-mahjong.html', 'Littleton CO', 'CO', 'colorado-mahjong.html', 'colorado-mahjong-hub.html'),
    ('prescott-az-4-mahjong.html', 'Prescott AZ', 'AZ', 'arizona-mahjong.html', 'arizona-mahjong-hub.html'),
    ('dublin-ca-3-mahjong.html', 'Dublin CA', 'CA', 'california-mahjong.html', 'california-mahjong-hub.html'),
    ('texarkana-tx-4-mahjong.html', 'Texarkana TX', 'TX', 'texas-mahjong.html', 'texas-mahjong-hub.html'),
    ('portland-me-4-mahjong.html', 'Portland ME', 'ME', 'maine-mahjong.html', 'maine-mahjong-hub.html'),
    ('brooklyn-park-mn-3-mahjong.html', 'Brooklyn Park MN', 'MN', 'minnesota-mahjong.html', 'minnesota-mahjong-hub.html'),
    ('west-haven-ct-3-mahjong.html', 'West Haven CT', 'CT', 'connecticut-mahjong.html', 'connecticut-mahjong-hub.html'),
    ('el-centro-ca-3-mahjong.html', 'El Centro CA', 'CA', 'california-mahjong.html', 'california-mahjong-hub.html'),
    ('the-colony-tx-4-mahjong.html', 'The Colony TX', 'TX', 'texas-mahjong.html', 'texas-mahjong-hub.html'),
    ('flint-mi-4-mahjong.html', 'Flint MI', 'MI', 'michigan-mahjong.html', 'michigan-mahjong-hub.html'),
    ('pittsburg-ca-3-mahjong.html', 'Pittsburg CA', 'CA', 'california-mahjong.html', 'california-mahjong-hub.html'),
    ('buckeye-az-3-mahjong.html', 'Buckeye AZ', 'AZ', 'arizona-mahjong.html', 'arizona-mahjong-hub.html'),
    ('brea-ca-3-mahjong.html', 'Brea CA', 'CA', 'california-mahjong.html', 'california-mahjong-hub.html'),
    ('indio-ca-3-mahjong.html', 'Indio CA', 'CA', 'california-mahjong.html', 'california-mahjong-hub.html'),
    ('scottsdale-az-3-mahjong.html', 'Scottsdale AZ', 'AZ', 'arizona-mahjong.html', 'arizona-mahjong-hub.html'),
    ('columbus-oh-3-mahjong.html', 'Columbus OH', 'OH', 'ohio-mahjong.html', 'ohio-mahjong-hub.html'),
    ('lancaster-pa-4-mahjong.html', 'Lancaster PA', 'PA', 'pennsylvania-mahjong.html', 'pennsylvania-mahjong-hub.html'),
    ('lincoln-ne-4-mahjong.html', 'Lincoln NE', 'NE', 'nebraska-mahjong.html', 'nebraska-mahjong-hub.html'),
    ('trenton-nj-4-mahjong.html', 'Trenton NJ', 'NJ', 'new-jersey-mahjong.html', 'new-jersey-mahjong-hub.html'),
    ('boston-ma-3-mahjong.html', 'Boston MA', 'MA', 'massachusetts-mahjong.html', 'massachusetts-mahjong-hub.html'),
    ('glendora-ca-3-mahjong.html', 'Glendora CA', 'CA', 'california-mahjong.html', 'california-mahjong-hub.html'),
    ('rochester-mn-4-mahjong.html', 'Rochester MN', 'MN', 'minnesota-mahjong.html', 'minnesota-mahjong-hub.html'),
    ('florissant-mo-4-mahjong.html', 'Florissant MO', 'MO', 'missouri-mahjong.html', 'missouri-mahjong-hub.html'),
    ('annapolis-md-3-mahjong.html', 'Annapolis MD', 'MD', 'maryland-mahjong.html', 'maryland-mahjong-hub.html'),
    ('chapel-hill-nc-4-mahjong.html', 'Chapel Hill NC', 'NC', 'north-carolina-mahjong.html', 'north-carolina-mahjong-hub.html'),
    ('lawrence-in-3-mahjong.html', 'Lawrence IN', 'IN', 'indiana-mahjong.html', 'indiana-mahjong-hub.html'),
    ('calexico-ca-3-mahjong.html', 'Calexico CA', 'CA', 'california-mahjong.html', 'california-mahjong-hub.html'),
    ('calumet-city-il-3-mahjong.html', 'Calumet City IL', 'IL', 'illinois-mahjong.html', 'illinois-mahjong-hub.html'),
    ('missoula-mt-4-mahjong.html', 'Missoula MT', 'MT', 'montana-mahjong.html', 'montana-mahjong-hub.html'),
    ('clovis-ca-3-mahjong.html', 'Clovis CA', 'CA', 'california-mahjong.html', 'california-mahjong-hub.html'),
    ('pearland-tx-4-mahjong.html', 'Pearland TX', 'TX', 'texas-mahjong.html', 'texas-mahjong-hub.html'),
    ('gilbert-az-4-mahjong.html', 'Gilbert AZ', 'AZ', 'arizona-mahjong.html', 'arizona-mahjong-hub.html'),
    ('wausau-wi-4-mahjong.html', 'Wausau WI', 'WI', 'wisconsin-mahjong.html', 'wisconsin-mahjong-hub.html'),
    ('raleigh-nc-3-mahjong.html', 'Raleigh NC', 'NC', 'north-carolina-mahjong.html', 'north-carolina-mahjong-hub.html'),
    ('orange-ca-3-mahjong.html', 'Orange CA', 'CA', 'california-mahjong.html', 'california-mahjong-hub.html'),
    ('walnut-creek-ca-4-mahjong.html', 'Walnut Creek CA', 'CA', 'california-mahjong.html', 'california-mahjong-hub.html'),
    ('bremerton-wa-4-mahjong.html', 'Bremerton WA', 'WA', 'washington-state-mahjong.html', 'washington-mahjong-hub.html'),
    ('porterville-ca-3-mahjong.html', 'Porterville CA', 'CA', 'california-mahjong.html', 'california-mahjong-hub.html'),
    ('marana-az-3-mahjong.html', 'Marana AZ', 'AZ', 'arizona-mahjong.html', 'arizona-mahjong-hub.html'),
    ('tallahassee-fl-3-mahjong.html', 'Tallahassee FL', 'FL', 'florida-mahjong.html', 'florida-mahjong-hub.html'),
    ('conroe-tx-4-mahjong.html', 'Conroe TX', 'TX', 'texas-mahjong.html', 'texas-mahjong-hub.html'),
    ('blacksburg-va-3-mahjong.html', 'Blacksburg VA', 'VA', 'virginia-mahjong.html', 'virginia-mahjong-hub.html'),
    ('san-antonio-tx-3-mahjong.html', 'San Antonio TX', 'TX', 'texas-mahjong.html', 'texas-mahjong-hub.html'),
    ('hartford-ct-4-mahjong.html', 'Hartford CT', 'CT', 'connecticut-mahjong.html', 'connecticut-mahjong-hub.html'),
    ('waterloo-ia-4-mahjong.html', 'Waterloo IA', 'IA', 'iowa-mahjong.html', 'iowa-mahjong-hub.html'),
    ('binghamton-ny-4-mahjong.html', 'Binghamton NY', 'NY', 'new-york-mahjong.html', 'new-york-mahjong-hub.html'),
    ('meridian-id-4-mahjong.html', 'Meridian ID', 'ID', 'idaho-mahjong.html', 'idaho-mahjong-hub.html'),
    ('fond-du-lac-wi-4-mahjong.html', 'Fond du Lac WI', 'WI', 'wisconsin-mahjong.html', 'wisconsin-mahjong-hub.html'),
    ('baytown-tx-4-mahjong.html', 'Baytown TX', 'TX', 'texas-mahjong.html', 'texas-mahjong-hub.html'),
    ('cary-nc-4-mahjong.html', 'Cary NC', 'NC', 'north-carolina-mahjong.html', 'north-carolina-mahjong-hub.html'),
    ('weymouth-town-ma-3-mahjong.html', 'Weymouth Town MA', 'MA', 'massachusetts-mahjong.html', 'massachusetts-mahjong-hub.html'),
    ('tulsa-ok-3-mahjong.html', 'Tulsa OK', 'OK', 'oklahoma-mahjong.html', 'oklahoma-mahjong-hub.html'),
    ('mission-tx-3-mahjong.html', 'Mission TX', 'TX', 'texas-mahjong.html', 'texas-mahjong-hub.html'),
    ('cuyahoga-falls-oh-3-mahjong.html', 'Cuyahoga Falls OH', 'OH', 'ohio-mahjong.html', 'ohio-mahjong-hub.html'),
    ('malden-ma-4-mahjong.html', 'Malden MA', 'MA', 'massachusetts-mahjong.html', 'massachusetts-mahjong-hub.html'),
    ('allen-tx-4-mahjong.html', 'Allen TX', 'TX', 'texas-mahjong.html', 'texas-mahjong-hub.html'),
    ('tucson-az-3-mahjong.html', 'Tucson AZ', 'AZ', 'arizona-mahjong.html', 'arizona-mahjong-hub.html'),
    ('franklin-tn-4-mahjong.html', 'Franklin TN', 'TN', 'tennessee-mahjong.html', 'tennessee-mahjong-hub.html'),
    ('shakopee-mn-3-mahjong.html', 'Shakopee MN', 'MN', 'minnesota-mahjong.html', 'minnesota-mahjong-hub.html'),
    ('jacksonville-fl-3-mahjong.html', 'Jacksonville FL', 'FL', 'florida-mahjong.html', 'florida-mahjong-hub.html'),
    ('atlantic-city-nj-4-mahjong.html', 'Atlantic City NJ', 'NJ', 'new-jersey-mahjong.html', 'new-jersey-mahjong-hub.html'),
    ('erie-pa-4-mahjong.html', 'Erie PA', 'PA', 'pennsylvania-mahjong.html', 'pennsylvania-mahjong-hub.html'),
    ('merced-ca-3-mahjong.html', 'Merced CA', 'CA', 'california-mahjong.html', 'california-mahjong-hub.html'),
    ('abilene-tx-4-mahjong.html', 'Abilene TX', 'TX', 'texas-mahjong.html', 'texas-mahjong-hub.html'),
    ('yorba-linda-ca-3-mahjong.html', 'Yorba Linda CA', 'CA', 'california-mahjong.html', 'california-mahjong-hub.html'),
    ('greenville-sc-4-mahjong.html', 'Greenville SC', 'SC', 'south-carolina-mahjong.html', 'south-carolina-mahjong-hub.html'),
    ('huntersville-nc-4-mahjong.html', 'Huntersville NC', 'NC', 'north-carolina-mahjong.html', 'north-carolina-mahjong-hub.html'),
    ('st-clair-shores-mi-3-mahjong.html', 'St. Clair Shores MI', 'MI', 'michigan-mahjong.html', 'michigan-mahjong-hub.html'),
    ('harrisburg-pa-4-mahjong.html', 'Harrisburg PA', 'PA', 'pennsylvania-mahjong.html', 'pennsylvania-mahjong-hub.html'),
    ('san-buenaventura-ventura-ca-3-mahjong.html', 'San Buenaventura (Ventura) CA', 'CA', 'california-mahjong.html', 'california-mahjong-hub.html'),
    ('fremont-ca-3-mahjong.html', 'Fremont CA', 'CA', 'california-mahjong.html', 'california-mahjong-hub.html'),
    ('pueblo-co-4-mahjong.html', 'Pueblo CO', 'CO', 'colorado-mahjong.html', 'colorado-mahjong-hub.html'),
    ('chelsea-ma-3-mahjong.html', 'Chelsea MA', 'MA', 'massachusetts-mahjong.html', 'massachusetts-mahjong-hub.html'),
    ('belleville-il-3-mahjong.html', 'Belleville IL', 'IL', 'illinois-mahjong.html', 'illinois-mahjong-hub.html'),
    ('minneapolis-mn-3-mahjong.html', 'Minneapolis MN', 'MN', 'minnesota-mahjong.html', 'minnesota-mahjong-hub.html'),
    ('bartlett-tn-3-mahjong.html', 'Bartlett TN', 'TN', 'tennessee-mahjong.html', 'tennessee-mahjong-hub.html'),
    ('wichita-falls-tx-3-mahjong.html', 'Wichita Falls TX', 'TX', 'texas-mahjong.html', 'texas-mahjong-hub.html'),
    ('missouri-city-tx-3-mahjong.html', 'Missouri City TX', 'TX', 'texas-mahjong.html', 'texas-mahjong-hub.html'),
    ('st-louis-mo-3-mahjong.html', 'St. Louis MO', 'MO', 'missouri-mahjong.html', 'missouri-mahjong-hub.html'),
    ('pharr-tx-3-mahjong.html', 'Pharr TX', 'TX', 'texas-mahjong.html', 'texas-mahjong-hub.html'),
    ('albuquerque-nm-3-mahjong.html', 'Albuquerque NM', 'NM', 'new-mexico-mahjong.html', 'new-mexico-mahjong-hub.html'),
    ('athens-clarke-county-ga-3-mahjong.html', 'Athens-Clarke County GA', 'GA', 'georgia-mahjong.html', 'georgia-mahjong-hub.html'),
    ('south-jordan-ut-4-mahjong.html', 'South Jordan UT', 'UT', 'utah-mahjong.html', 'utah-mahjong-hub.html'),
    ('north-las-vegas-nv-4-mahjong.html', 'North Las Vegas NV', 'NV', 'nevada-mahjong.html', 'nevada-mahjong-hub.html'),
    ('pomona-ca-3-mahjong.html', 'Pomona CA', 'CA', 'california-mahjong.html', 'california-mahjong-hub.html'),
    ('eastvale-ca-3-mahjong.html', 'Eastvale CA', 'CA', 'california-mahjong.html', 'california-mahjong-hub.html'),
    ('grove-city-oh-3-mahjong.html', 'Grove City OH', 'OH', 'ohio-mahjong.html', 'ohio-mahjong-hub.html'),
    ('lawrence-ks-4-mahjong.html', 'Lawrence KS', 'KS', 'kansas-mahjong.html', 'kansas-mahjong-hub.html'),
    ('midland-tx-4-mahjong.html', 'Midland TX', 'TX', 'texas-mahjong.html', 'texas-mahjong-hub.html'),
    ('oklahoma-city-ok-3-mahjong.html', 'Oklahoma City OK', 'OK', 'oklahoma-mahjong.html', 'oklahoma-mahjong-hub.html'),
    ('oro-valley-az-4-mahjong.html', 'Oro Valley AZ', 'AZ', 'arizona-mahjong.html', 'arizona-mahjong-hub.html'),
    ('mesa-az-4-mahjong.html', 'Mesa AZ', 'AZ', 'arizona-mahjong.html', 'arizona-mahjong-hub.html'),
    ('norwalk-ct-4-mahjong.html', 'Norwalk CT', 'CT', 'connecticut-mahjong.html', 'connecticut-mahjong-hub.html'),
    ('kentwood-mi-4-mahjong.html', 'Kentwood MI', 'MI', 'michigan-mahjong.html', 'michigan-mahjong-hub.html'),
    ('brookfield-wi-4-mahjong.html', 'Brookfield WI', 'WI', 'wisconsin-mahjong.html', 'wisconsin-mahjong-hub.html'),
    ('rockwall-tx-4-mahjong.html', 'Rockwall TX', 'TX', 'texas-mahjong.html', 'texas-mahjong-hub.html'),
    ('mishawaka-in-4-mahjong.html', 'Mishawaka IN', 'IN', 'indiana-mahjong.html', 'indiana-mahjong-hub.html'),
    ('tustin-ca-3-mahjong.html', 'Tustin CA', 'CA', 'california-mahjong.html', 'california-mahjong-hub.html'),
    ('st-cloud-mn-4-mahjong.html', 'St. Cloud MN', 'MN', 'minnesota-mahjong.html', 'minnesota-mahjong-hub.html'),
    ('passaic-nj-3-mahjong.html', 'Passaic NJ', 'NJ', 'new-jersey-mahjong.html', 'new-jersey-mahjong-hub.html'),
    ('escondido-ca-3-mahjong.html', 'Escondido CA', 'CA', 'california-mahjong.html', 'california-mahjong-hub.html'),
    ('san-bruno-ca-3-mahjong.html', 'San Bruno CA', 'CA', 'california-mahjong.html', 'california-mahjong-hub.html'),
    ('berkeley-ca-3-mahjong.html', 'Berkeley CA', 'CA', 'california-mahjong.html', 'california-mahjong-hub.html'),
    ('san-clemente-ca-3-mahjong.html', 'San Clemente CA', 'CA', 'california-mahjong.html', 'california-mahjong-hub.html'),
    ('lawton-ok-4-mahjong.html', 'Lawton OK', 'OK', 'oklahoma-mahjong.html', 'oklahoma-mahjong-hub.html'),
    ('eau-claire-wi-4-mahjong.html', 'Eau Claire WI', 'WI', 'wisconsin-mahjong.html', 'wisconsin-mahjong-hub.html'),
    ('maricopa-az-4-mahjong.html', 'Maricopa AZ', 'AZ', 'arizona-mahjong.html', 'arizona-mahjong-hub.html'),
    ('desoto-tx-3-mahjong.html', 'DeSoto TX', 'TX', 'texas-mahjong.html', 'texas-mahjong-hub.html'),
    ('fort-wayne-in-4-mahjong.html', 'Fort Wayne IN', 'IN', 'indiana-mahjong.html', 'indiana-mahjong-hub.html'),
    ('shoreline-wa-3-mahjong.html', 'Shoreline WA', 'WA', 'washington-state-mahjong.html', 'washington-mahjong-hub.html'),
    ('medford-ma-4-mahjong.html', 'Medford MA', 'MA', 'massachusetts-mahjong.html', 'massachusetts-mahjong-hub.html'),
    ('la-habra-ca-3-mahjong.html', 'La Habra CA', 'CA', 'california-mahjong.html', 'california-mahjong-hub.html'),
    ('albany-ny-4-mahjong.html', 'Albany NY', 'NY', 'new-york-mahjong.html', 'new-york-mahjong-hub.html'),
    ('daly-city-ca-3-mahjong.html', 'Daly City CA', 'CA', 'california-mahjong.html', 'california-mahjong-hub.html'),
    ('taylor-mi-3-mahjong.html', 'Taylor MI', 'MI', 'michigan-mahjong.html', 'michigan-mahjong-hub.html'),
    ('lynchburg-va-4-mahjong.html', 'Lynchburg VA', 'VA', 'virginia-mahjong.html', 'virginia-mahjong-hub.html'),
    ('bowie-md-3-mahjong.html', 'Bowie MD', 'MD', 'maryland-mahjong.html', 'maryland-mahjong-hub.html'),
    ('danbury-ct-4-mahjong.html', 'Danbury CT', 'CT', 'connecticut-mahjong.html', 'connecticut-mahjong-hub.html'),
    ('charlottesville-va-3-mahjong.html', 'Charlottesville VA', 'VA', 'virginia-mahjong.html', 'virginia-mahjong-hub.html'),
    ('coral-gables-fl-3-mahjong.html', 'Coral Gables FL', 'FL', 'florida-mahjong.html', 'florida-mahjong-hub.html'),
    ('coeur-dalene-id-4-mahjong.html', "Coeur d'Alene ID", 'ID', 'idaho-mahjong.html', 'idaho-mahjong-hub.html'),
    ('el-monte-ca-3-mahjong.html', 'El Monte CA', 'CA', 'california-mahjong.html', 'california-mahjong-hub.html'),
    ('crystal-lake-il-3-mahjong.html', 'Crystal Lake IL', 'IL', 'illinois-mahjong.html', 'illinois-mahjong-hub.html'),
    ('danville-ca-3-mahjong.html', 'Danville CA', 'CA', 'california-mahjong.html', 'california-mahjong-hub.html'),
    ('goodyear-az-3-mahjong.html', 'Goodyear AZ', 'AZ', 'arizona-mahjong.html', 'arizona-mahjong-hub.html'),
    ('paterson-nj-3-mahjong.html', 'Paterson NJ', 'NJ', 'new-jersey-mahjong.html', 'new-jersey-mahjong-hub.html'),
    ('salem-or-4-mahjong.html', 'Salem OR', 'OR', 'oregon-mahjong.html', 'oregon-mahjong-hub.html'),
    ('kissimmee-fl-4-mahjong.html', 'Kissimmee FL', 'FL', 'florida-mahjong.html', 'florida-mahjong-hub.html'),
    ('saginaw-mi-4-mahjong.html', 'Saginaw MI', 'MI', 'michigan-mahjong.html', 'michigan-mahjong-hub.html'),
    ('brownsville-tx-4-mahjong.html', 'Brownsville TX', 'TX', 'texas-mahjong.html', 'texas-mahjong-hub.html'),
    ('flower-mound-tx-4-mahjong.html', 'Flower Mound TX', 'TX', 'texas-mahjong.html', 'texas-mahjong-hub.html'),
    ('grapevine-tx-4-mahjong.html', 'Grapevine TX', 'TX', 'texas-mahjong.html', 'texas-mahjong-hub.html'),
    ('edina-mn-4-mahjong.html', 'Edina MN', 'MN', 'minnesota-mahjong.html', 'minnesota-mahjong-hub.html'),
    ('detroit-mi-3-mahjong.html', 'Detroit MI', 'MI', 'michigan-mahjong.html', 'michigan-mahjong-hub.html'),
    ('fairfield-oh-3-mahjong.html', 'Fairfield OH', 'OH', 'ohio-mahjong.html', 'ohio-mahjong-hub.html'),
    ('mansfield-tx-4-mahjong.html', 'Mansfield TX', 'TX', 'texas-mahjong.html', 'texas-mahjong-hub.html'),
    ('rochester-ny-4-mahjong.html', 'Rochester NY', 'NY', 'new-york-mahjong.html', 'new-york-mahjong-hub.html'),
    ('birmingham-al-3-mahjong.html', 'Birmingham AL', 'AL', 'alabama-mahjong.html', 'alabama-mahjong-hub.html'),
    ('austin-tx-3-mahjong.html', 'Austin TX', 'TX', 'texas-mahjong.html', 'texas-mahjong-hub.html'),
    ('santa-barbara-ca-4-mahjong.html', 'Santa Barbara CA', 'CA', 'california-mahjong.html', 'california-mahjong-hub.html'),
    ('addison-il-3-mahjong.html', 'Addison IL', 'IL', 'illinois-mahjong.html', 'illinois-mahjong-hub.html'),
    ('rio-rancho-nm-4-mahjong.html', 'Rio Rancho NM', 'NM', 'new-mexico-mahjong.html', 'new-mexico-mahjong-hub.html'),
    ('normal-il-4-mahjong.html', 'Normal IL', 'IL', 'illinois-mahjong.html', 'illinois-mahjong-hub.html'),
    ('romeoville-il-3-mahjong.html', 'Romeoville IL', 'IL', 'illinois-mahjong.html', 'illinois-mahjong-hub.html'),
    ('coon-rapids-mn-3-mahjong.html', 'Coon Rapids MN', 'MN', 'minnesota-mahjong.html', 'minnesota-mahjong-hub.html'),
    ('san-mateo-ca-4-mahjong.html', 'San Mateo CA', 'CA', 'california-mahjong.html', 'california-mahjong-hub.html'),
    ('orlando-fl-3-mahjong.html', 'Orlando FL', 'FL', 'florida-mahjong.html', 'florida-mahjong-hub.html'),
    ('casper-wy-4-mahjong.html', 'Casper WY', 'WY', 'wyoming-mahjong.html', 'wyoming-mahjong-hub.html'),
    ('bedford-tx-3-mahjong.html', 'Bedford TX', 'TX', 'texas-mahjong.html', 'texas-mahjong-hub.html'),
    ('wilmington-nc-4-mahjong.html', 'Wilmington NC', 'NC', 'north-carolina-mahjong.html', 'north-carolina-mahjong-hub.html'),
    ('pinellas-park-fl-3-mahjong.html', 'Pinellas Park FL', 'FL', 'florida-mahjong.html', 'florida-mahjong-hub.html'),
    ('north-miami-beach-fl-3-mahjong.html', 'North Miami Beach FL', 'FL', 'florida-mahjong.html', 'florida-mahjong-hub.html'),
    ('kansas-city-ks-3-mahjong.html', 'Kansas City KS', 'KS', 'kansas-mahjong.html', 'kansas-mahjong-hub.html'),
    ('fitchburg-ma-3-mahjong.html', 'Fitchburg MA', 'MA', 'massachusetts-mahjong.html', 'massachusetts-mahjong-hub.html'),
    ('wheeling-il-3-mahjong.html', 'Wheeling IL', 'IL', 'illinois-mahjong.html', 'illinois-mahjong-hub.html'),
    ('newton-ma-4-mahjong.html', 'Newton MA', 'MA', 'massachusetts-mahjong.html', 'massachusetts-mahjong-hub.html'),
    ('north-miami-fl-3-mahjong.html', 'North Miami FL', 'FL', 'florida-mahjong.html', 'florida-mahjong-hub.html'),
    ('norwich-ct-4-mahjong.html', 'Norwich CT', 'CT', 'connecticut-mahjong.html', 'connecticut-mahjong-hub.html'),
    ('newark-nj-3-mahjong.html', 'Newark NJ', 'NJ', 'new-jersey-mahjong.html', 'new-jersey-mahjong-hub.html'),
    ('alexandria-la-4-mahjong.html', 'Alexandria LA', 'LA', 'louisiana-mahjong.html', 'louisiana-mahjong-hub.html'),
    ('blaine-mn-3-mahjong.html', 'Blaine MN', 'MN', 'minnesota-mahjong.html', 'minnesota-mahjong-hub.html'),
    ('harlingen-tx-3-mahjong.html', 'Harlingen TX', 'TX', 'texas-mahjong.html', 'texas-mahjong-hub.html'),
    ('lompoc-ca-3-mahjong.html', 'Lompoc CA', 'CA', 'california-mahjong.html', 'california-mahjong-hub.html'),
    ('denton-tx-4-mahjong.html', 'Denton TX', 'TX', 'texas-mahjong.html', 'texas-mahjong-hub.html'),
    ('galveston-tx-3-mahjong.html', 'Galveston TX', 'TX', 'texas-mahjong.html', 'texas-mahjong-hub.html'),
    ('greenwood-in-4-mahjong.html', 'Greenwood IN', 'IN', 'indiana-mahjong.html', 'indiana-mahjong-hub.html'),
    ('salinas-ca-4-mahjong.html', 'Salinas CA', 'CA', 'california-mahjong.html', 'california-mahjong-hub.html'),
    ('miami-gardens-fl-3-mahjong.html', 'Miami Gardens FL', 'FL', 'florida-mahjong.html', 'florida-mahjong-hub.html'),
    ('huntington-wv-4-mahjong.html', 'Huntington WV', 'WV', 'west-virginia-mahjong.html', 'west-virginia-mahjong-hub.html'),
    ('laredo-tx-4-mahjong.html', 'Laredo TX', 'TX', 'texas-mahjong.html', 'texas-mahjong-hub.html'),
    ('melbourne-fl-4-mahjong.html', 'Melbourne FL', 'FL', 'florida-mahjong.html', 'florida-mahjong-hub.html'),
    ('haltom-city-tx-3-mahjong.html', 'Haltom City TX', 'TX', 'texas-mahjong.html', 'texas-mahjong-hub.html'),
    ('palm-bay-fl-3-mahjong.html', 'Palm Bay FL', 'FL', 'florida-mahjong.html', 'florida-mahjong-hub.html'),
    ('wilson-nc-4-mahjong.html', 'Wilson NC', 'NC', 'north-carolina-mahjong.html', 'north-carolina-mahjong-hub.html'),
    ('bountiful-ut-4-mahjong.html', 'Bountiful UT', 'UT', 'utah-mahjong.html', 'utah-mahjong-hub.html'),
    ('ceres-ca-3-mahjong.html', 'Ceres CA', 'CA', 'california-mahjong.html', 'california-mahjong-hub.html'),
    ('parma-oh-3-mahjong.html', 'Parma OH', 'OH', 'ohio-mahjong.html', 'ohio-mahjong-hub.html'),
    ('rapid-city-sd-4-mahjong.html', 'Rapid City SD', 'SD', 'south-dakota-mahjong.html', 'south-dakota-mahjong-hub.html'),
    ('bell-gardens-ca-3-mahjong.html', 'Bell Gardens CA', 'CA', 'california-mahjong.html', 'california-mahjong-hub.html'),
    ('commerce-city-co-3-mahjong.html', 'Commerce City CO', 'CO', 'colorado-mahjong.html', 'colorado-mahjong-hub.html'),
    ('springfield-ma-4-mahjong.html', 'Springfield MA', 'MA', 'massachusetts-mahjong.html', 'massachusetts-mahjong-hub.html'),
    ('fort-collins-co-4-mahjong.html', 'Fort Collins CO', 'CO', 'colorado-mahjong.html', 'colorado-mahjong-hub.html'),
    ('san-leandro-ca-3-mahjong.html', 'San Leandro CA', 'CA', 'california-mahjong.html', 'california-mahjong-hub.html'),
    ('vista-ca-3-mahjong.html', 'Vista CA', 'CA', 'california-mahjong.html', 'california-mahjong-hub.html'),
    ('yonkers-ny-4-mahjong.html', 'Yonkers NY', 'NY', 'new-york-mahjong.html', 'new-york-mahjong-hub.html'),
    ('cincinnati-oh-3-mahjong.html', 'Cincinnati OH', 'OH', 'ohio-mahjong.html', 'ohio-mahjong-hub.html'),
    ('hagerstown-md-4-mahjong.html', 'Hagerstown MD', 'MD', 'maryland-mahjong.html', 'maryland-mahjong-hub.html'),
    ('sanford-fl-4-mahjong.html', 'Sanford FL', 'FL', 'florida-mahjong.html', 'florida-mahjong-hub.html'),
    ('union-city-nj-3-mahjong.html', 'Union City NJ', 'NJ', 'new-jersey-mahjong.html', 'new-jersey-mahjong-hub.html'),
    ('toledo-oh-4-mahjong.html', 'Toledo OH', 'OH', 'ohio-mahjong.html', 'ohio-mahjong-hub.html'),
    ('sierra-vista-az-4-mahjong.html', 'Sierra Vista AZ', 'AZ', 'arizona-mahjong.html', 'arizona-mahjong-hub.html'),
    ('newport-news-va-4-mahjong.html', 'Newport News VA', 'VA', 'virginia-mahjong.html', 'virginia-mahjong-hub.html'),
    ('hammond-in-4-mahjong.html', 'Hammond IN', 'IN', 'indiana-mahjong.html', 'indiana-mahjong-hub.html'),
    ('buffalo-grove-il-3-mahjong.html', 'Buffalo Grove IL', 'IL', 'illinois-mahjong.html', 'illinois-mahjong-hub.html'),
    ('sugar-land-tx-4-mahjong.html', 'Sugar Land TX', 'TX', 'texas-mahjong.html', 'texas-mahjong-hub.html'),
    ('huntsville-al-3-mahjong.html', 'Huntsville AL', 'AL', 'alabama-mahjong.html', 'alabama-mahjong-hub.html'),
    ('lodi-ca-3-mahjong.html', 'Lodi CA', 'CA', 'california-mahjong.html', 'california-mahjong-hub.html'),
    ('edmonds-wa-3-mahjong.html', 'Edmonds WA', 'WA', 'washington-state-mahjong.html', 'washington-mahjong-hub.html'),
    ('duncanville-tx-3-mahjong.html', 'Duncanville TX', 'TX', 'texas-mahjong.html', 'texas-mahjong-hub.html'),
    ('rocky-mount-nc-4-mahjong.html', 'Rocky Mount NC', 'NC', 'north-carolina-mahjong.html', 'north-carolina-mahjong-hub.html'),
    ('pontiac-mi-3-mahjong.html', 'Pontiac MI', 'MI', 'michigan-mahjong.html', 'michigan-mahjong-hub.html'),
    ('national-city-ca-3-mahjong.html', 'National City CA', 'CA', 'california-mahjong.html', 'california-mahjong-hub.html'),
    ('hayward-ca-3-mahjong.html', 'Hayward CA', 'CA', 'california-mahjong.html', 'california-mahjong-hub.html'),
    ('niagara-falls-ny-3-mahjong.html', 'Niagara Falls NY', 'NY', 'new-york-mahjong.html', 'new-york-mahjong-hub.html'),
    ('sparks-nv-4-mahjong.html', 'Sparks NV', 'NV', 'nevada-mahjong.html', 'nevada-mahjong-hub.html'),
    ('hanford-ca-3-mahjong.html', 'Hanford CA', 'CA', 'california-mahjong.html', 'california-mahjong-hub.html'),
    ('cypress-ca-3-mahjong.html', 'Cypress CA', 'CA', 'california-mahjong.html', 'california-mahjong-hub.html'),
    ('youngstown-oh-4-mahjong.html', 'Youngstown OH', 'OH', 'ohio-mahjong.html', 'ohio-mahjong-hub.html'),
    ('madison-al-3-mahjong.html', 'Madison AL', 'AL', 'alabama-mahjong.html', 'alabama-mahjong-hub.html'),
    ('redlands-ca-3-mahjong.html', 'Redlands CA', 'CA', 'california-mahjong.html', 'california-mahjong-hub.html'),
    ('cape-girardeau-mo-4-mahjong.html', 'Cape Girardeau MO', 'MO', 'missouri-mahjong.html', 'missouri-mahjong-hub.html'),
    ('nampa-id-4-mahjong.html', 'Nampa ID', 'ID', 'idaho-mahjong.html', 'idaho-mahjong-hub.html'),
    ('wheaton-il-3-mahjong.html', 'Wheaton IL', 'IL', 'illinois-mahjong.html', 'illinois-mahjong-hub.html'),
    ('lancaster-tx-3-mahjong.html', 'Lancaster TX', 'TX', 'texas-mahjong.html', 'texas-mahjong-hub.html'),
    ('rialto-ca-3-mahjong.html', 'Rialto CA', 'CA', 'california-mahjong.html', 'california-mahjong-hub.html'),
    ('fargo-nd-4-mahjong.html', 'Fargo ND', 'ND', 'north-dakota-mahjong.html', 'north-dakota-mahjong-hub.html'),
    ('peoria-il-4-mahjong.html', 'Peoria IL', 'IL', 'illinois-mahjong.html', 'illinois-mahjong-hub.html'),
    ('omaha-ne-4-mahjong.html', 'Omaha NE', 'NE', 'nebraska-mahjong.html', 'nebraska-mahjong-hub.html'),
    ('rancho-santa-margarita-ca-3-mahjong.html', 'Rancho Santa Margarita CA', 'CA', 'california-mahjong.html', 'california-mahjong-hub.html'),
    ('manhattan-ks-4-mahjong.html', 'Manhattan KS', 'KS', 'kansas-mahjong.html', 'kansas-mahjong-hub.html'),
    ('palm-springs-ca-3-mahjong.html', 'Palm Springs CA', 'CA', 'california-mahjong.html', 'california-mahjong-hub.html'),
    ('san-diego-ca-3-mahjong.html', 'San Diego CA', 'CA', 'california-mahjong.html', 'california-mahjong-hub.html'),
    ('santa-rosa-ca-4-mahjong.html', 'Santa Rosa CA', 'CA', 'california-mahjong.html', 'california-mahjong-hub.html'),
    ('lowell-ma-4-mahjong.html', 'Lowell MA', 'MA', 'massachusetts-mahjong.html', 'massachusetts-mahjong-hub.html'),
    ('broken-arrow-ok-4-mahjong.html', 'Broken Arrow OK', 'OK', 'oklahoma-mahjong.html', 'oklahoma-mahjong-hub.html'),
    ('kent-wa-3-mahjong.html', 'Kent WA', 'WA', 'washington-state-mahjong.html', 'washington-mahjong-hub.html'),
    ('nashville-tn-3-mahjong.html', 'Nashville TN', 'TN', 'tennessee-mahjong.html', 'tennessee-mahjong-hub.html'),
    ('hackensack-nj-4-mahjong.html', 'Hackensack NJ', 'NJ', 'new-jersey-mahjong.html', 'new-jersey-mahjong-hub.html'),
    ('broomfield-co-4-mahjong.html', 'Broomfield CO', 'CO', 'colorado-mahjong.html', 'colorado-mahjong-hub.html'),
    ('durham-nc-4-mahjong.html', 'Durham NC', 'NC', 'north-carolina-mahjong.html', 'north-carolina-mahjong-hub.html'),
    ('wichita-ks-4-mahjong.html', 'Wichita KS', 'KS', 'kansas-mahjong.html', 'kansas-mahjong-hub.html'),
    ('cathedral-city-ca-3-mahjong.html', 'Cathedral City CA', 'CA', 'california-mahjong.html', 'california-mahjong-hub.html'),
    ('lakeville-mn-4-mahjong.html', 'Lakeville MN', 'MN', 'minnesota-mahjong.html', 'minnesota-mahjong-hub.html'),
    ('elmhurst-il-3-mahjong.html', 'Elmhurst IL', 'IL', 'illinois-mahjong.html', 'illinois-mahjong-hub.html'),
    ('weslaco-tx-3-mahjong.html', 'Weslaco TX', 'TX', 'texas-mahjong.html', 'texas-mahjong-hub.html'),
    ('greenfield-wi-3-mahjong.html', 'Greenfield WI', 'WI', 'wisconsin-mahjong.html', 'wisconsin-mahjong-hub.html'),
    ('sunnyvale-ca-3-mahjong.html', 'Sunnyvale CA', 'CA', 'california-mahjong.html', 'california-mahjong-hub.html'),
    ('santa-cruz-ca-4-mahjong.html', 'Santa Cruz CA', 'CA', 'california-mahjong.html', 'california-mahjong-hub.html'),
    ('kenosha-wi-4-mahjong.html', 'Kenosha WI', 'WI', 'wisconsin-mahjong.html', 'wisconsin-mahjong-hub.html'),
    ('state-college-pa-4-mahjong.html', 'State College PA', 'PA', 'pennsylvania-mahjong.html', 'pennsylvania-mahjong-hub.html'),
    ('mansfield-oh-4-mahjong.html', 'Mansfield OH', 'OH', 'ohio-mahjong.html', 'ohio-mahjong-hub.html'),
    ('quincy-il-4-mahjong.html', 'Quincy IL', 'IL', 'illinois-mahjong.html', 'illinois-mahjong-hub.html'),
    ('pompano-beach-fl-3-mahjong.html', 'Pompano Beach FL', 'FL', 'florida-mahjong.html', 'florida-mahjong-hub.html'),
    ('san-angelo-tx-3-mahjong.html', 'San Angelo TX', 'TX', 'texas-mahjong.html', 'texas-mahjong-hub.html'),
    ('bloomington-il-4-mahjong.html', 'Bloomington IL', 'IL', 'illinois-mahjong.html', 'illinois-mahjong-hub.html'),
    ('tracy-ca-3-mahjong.html', 'Tracy CA', 'CA', 'california-mahjong.html', 'california-mahjong-hub.html'),
    ('spartanburg-sc-4-mahjong.html', 'Spartanburg SC', 'SC', 'south-carolina-mahjong.html', 'south-carolina-mahjong-hub.html'),
    ('nashua-nh-4-mahjong.html', 'Nashua NH', 'NH', 'new-hampshire-mahjong.html', 'new-hampshire-mahjong-hub.html'),
    ('macon-ga-4-mahjong.html', 'Macon GA', 'GA', 'georgia-mahjong.html', 'georgia-mahjong-hub.html'),
    ('hempstead-ny-3-mahjong.html', 'Hempstead NY', 'NY', 'new-york-mahjong.html', 'new-york-mahjong-hub.html'),
    ('camden-nj-4-mahjong.html', 'Camden NJ', 'NJ', 'new-jersey-mahjong.html', 'new-jersey-mahjong-hub.html'),
    ('palm-desert-ca-4-mahjong.html', 'Palm Desert CA', 'CA', 'california-mahjong.html', 'california-mahjong-hub.html'),
    ('streamwood-il-3-mahjong.html', 'Streamwood IL', 'IL', 'illinois-mahjong.html', 'illinois-mahjong-hub.html'),
    ('chesapeake-va-4-mahjong.html', 'Chesapeake VA', 'VA', 'virginia-mahjong.html', 'virginia-mahjong-hub.html'),
    ('dublin-oh-3-mahjong.html', 'Dublin OH', 'OH', 'ohio-mahjong.html', 'ohio-mahjong-hub.html'),
    ('camarillo-ca-3-mahjong.html', 'Camarillo CA', 'CA', 'california-mahjong.html', 'california-mahjong-hub.html'),
    ('muskegon-mi-4-mahjong.html', 'Muskegon MI', 'MI', 'michigan-mahjong.html', 'michigan-mahjong-hub.html'),
    ('elizabeth-nj-3-mahjong.html', 'Elizabeth NJ', 'NJ', 'new-jersey-mahjong.html', 'new-jersey-mahjong-hub.html'),
    ('anchorage-ak-4-mahjong.html', 'Anchorage AK', 'AK', 'alaska-mahjong.html', 'alaska-mahjong-hub.html'),
    ('minot-nd-4-mahjong.html', 'Minot ND', 'ND', 'north-dakota-mahjong.html', 'north-dakota-mahjong-hub.html'),
    ('davie-fl-3-mahjong.html', 'Davie FL', 'FL', 'florida-mahjong.html', 'florida-mahjong-hub.html'),
    ('mcallen-tx-4-mahjong.html', 'McAllen TX', 'TX', 'texas-mahjong.html', 'texas-mahjong-hub.html'),
    ('mckinney-tx-4-mahjong.html', 'McKinney TX', 'TX', 'texas-mahjong.html', 'texas-mahjong-hub.html'),
    ('killeen-tx-4-mahjong.html', 'Killeen TX', 'TX', 'texas-mahjong.html', 'texas-mahjong-hub.html'),
    ('findlay-oh-4-mahjong.html', 'Findlay OH', 'OH', 'ohio-mahjong.html', 'ohio-mahjong-hub.html'),
    ('oakland-ca-3-mahjong.html', 'Oakland CA', 'CA', 'california-mahjong.html', 'california-mahjong-hub.html'),
    ('mountain-view-ca-4-mahjong.html', 'Mountain View CA', 'CA', 'california-mahjong.html', 'california-mahjong-hub.html'),
    ('lake-elsinore-ca-3-mahjong.html', 'Lake Elsinore CA', 'CA', 'california-mahjong.html', 'california-mahjong-hub.html'),
    ('amarillo-tx-4-mahjong.html', 'Amarillo TX', 'TX', 'texas-mahjong.html', 'texas-mahjong-hub.html'),
    ('provo-ut-4-mahjong.html', 'Provo UT', 'UT', 'utah-mahjong.html', 'utah-mahjong-hub.html'),
    ('atlanta-ga-3-mahjong.html', 'Atlanta GA', 'GA', 'georgia-mahjong.html', 'georgia-mahjong-hub.html'),
    ('monterey-park-ca-3-mahjong.html', 'Monterey Park CA', 'CA', 'california-mahjong.html', 'california-mahjong-hub.html'),
    ('strongsville-oh-3-mahjong.html', 'Strongsville OH', 'OH', 'ohio-mahjong.html', 'ohio-mahjong-hub.html'),
    ('madera-ca-3-mahjong.html', 'Madera CA', 'CA', 'california-mahjong.html', 'california-mahjong-hub.html'),
    ('decatur-il-4-mahjong.html', 'Decatur IL', 'IL', 'illinois-mahjong.html', 'illinois-mahjong-hub.html'),
    ('woonsocket-ri-4-mahjong.html', 'Woonsocket RI', 'RI', 'rhode-island-mahjong.html', 'rhode-island-mahjong-hub.html'),
    ('mobile-al-4-mahjong.html', 'Mobile AL', 'AL', 'alabama-mahjong.html', 'alabama-mahjong-hub.html'),
    ('vallejo-ca-4-mahjong.html', 'Vallejo CA', 'CA', 'california-mahjong.html', 'california-mahjong-hub.html'),
    ('arcadia-ca-3-mahjong.html', 'Arcadia CA', 'CA', 'california-mahjong.html', 'california-mahjong-hub.html'),
    ('collierville-tn-4-mahjong.html', 'Collierville TN', 'TN', 'tennessee-mahjong.html', 'tennessee-mahjong-hub.html'),
    ('jefferson-city-mo-4-mahjong.html', 'Jefferson City MO', 'MO', 'missouri-mahjong.html', 'missouri-mahjong-hub.html'),
    ('longview-tx-4-mahjong.html', 'Longview TX', 'TX', 'texas-mahjong.html', 'texas-mahjong-hub.html'),
    ('chandler-az-4-mahjong.html', 'Chandler AZ', 'AZ', 'arizona-mahjong.html', 'arizona-mahjong-hub.html'),
    ('arvada-co-3-mahjong.html', 'Arvada CO', 'CO', 'colorado-mahjong.html', 'colorado-mahjong-hub.html'),
    ('alhambra-ca-3-mahjong.html', 'Alhambra CA', 'CA', 'california-mahjong.html', 'california-mahjong-hub.html'),
    ('kokomo-in-4-mahjong.html', 'Kokomo IN', 'IN', 'indiana-mahjong.html', 'indiana-mahjong-hub.html'),
    ('oakland-park-fl-3-mahjong.html', 'Oakland Park FL', 'FL', 'florida-mahjong.html', 'florida-mahjong-hub.html'),
    ('indianapolis-in-3-mahjong.html', 'Indianapolis IN', 'IN', 'indiana-mahjong.html', 'indiana-mahjong-hub.html'),
    ('boynton-beach-fl-3-mahjong.html', 'Boynton Beach FL', 'FL', 'florida-mahjong.html', 'florida-mahjong-hub.html'),
    ('apache-junction-az-4-mahjong.html', 'Apache Junction AZ', 'AZ', 'arizona-mahjong.html', 'arizona-mahjong-hub.html'),
    ('mount-prospect-il-3-mahjong.html', 'Mount Prospect IL', 'IL', 'illinois-mahjong.html', 'illinois-mahjong-hub.html'),
    ('cranston-ri-4-mahjong.html', 'Cranston RI', 'RI', 'rhode-island-mahjong.html', 'rhode-island-mahjong-hub.html'),
    ('lafayette-in-4-mahjong.html', 'Lafayette IN', 'IN', 'indiana-mahjong.html', 'indiana-mahjong-hub.html'),
    ('olathe-ks-4-mahjong.html', 'Olathe KS', 'KS', 'kansas-mahjong.html', 'kansas-mahjong-hub.html'),
    ('johns-creek-ga-3-mahjong.html', 'Johns Creek GA', 'GA', 'georgia-mahjong.html', 'georgia-mahjong-hub.html'),
    ('greensboro-nc-4-mahjong.html', 'Greensboro NC', 'NC', 'north-carolina-mahjong.html', 'north-carolina-mahjong-hub.html'),
    ('kalamazoo-mi-4-mahjong.html', 'Kalamazoo MI', 'MI', 'michigan-mahjong.html', 'michigan-mahjong-hub.html'),
    ('tigard-or-4-mahjong.html', 'Tigard OR', 'OR', 'oregon-mahjong.html', 'oregon-mahjong-hub.html'),
    ('jacksonville-nc-4-mahjong.html', 'Jacksonville NC', 'NC', 'north-carolina-mahjong.html', 'north-carolina-mahjong-hub.html'),
    ('citrus-heights-ca-ca-mahjong.html', 'Citrus Heights CA', 'CA', 'california-mahjong.html', 'california-mahjong-hub.html'),
    ('tuscaloosa-al-2-mahjong.html', 'Tuscaloosa AL', 'AL', 'alabama-mahjong.html', 'alabama-mahjong-hub.html'),
    ('ankeny-ia-2-mahjong.html', 'Ankeny IA', 'IA', 'iowa-mahjong.html', 'iowa-mahjong-hub.html'),
    ('hawthorne-ca-ca-mahjong.html', 'Hawthorne CA', 'CA', 'california-mahjong.html', 'california-mahjong-hub.html'),
    ('hoover-al-2-mahjong.html', 'Hoover AL', 'AL', 'alabama-mahjong.html', 'alabama-mahjong-hub.html'),
    ('delray-beach-fl-2-mahjong.html', 'Delray Beach FL', 'FL', 'florida-mahjong.html', 'florida-mahjong-hub.html'),
    ('wellington-fl-fl-mahjong.html', 'Wellington FL', 'FL', 'florida-mahjong.html', 'florida-mahjong-hub.html'),
    ('bullhead-city-az-2-mahjong.html', 'Bullhead City AZ', 'AZ', 'arizona-mahjong.html', 'arizona-mahjong-hub.html'),
    ('weston-fl-fl-mahjong.html', 'Weston FL', 'FL', 'florida-mahjong.html', 'florida-mahjong-hub.html'),
    ('troy-mi-2-mahjong.html', 'Troy MI', 'MI', 'michigan-mahjong.html', 'michigan-mahjong-hub.html'),
    ('new-rochelle-ny-2-mahjong.html', 'New Rochelle NY', 'NY', 'new-york-mahjong.html', 'new-york-mahjong-hub.html'),
    ('stockton-ca-2-mahjong.html', 'Stockton CA', 'CA', 'california-mahjong.html', 'california-mahjong-hub.html'),
    ('royal-oak-mi-mi-mahjong.html', 'Royal Oak MI', 'MI', 'michigan-mahjong.html', 'michigan-mahjong-hub.html'),
    ('titusville-fl-fl-mahjong.html', 'Titusville FL', 'FL', 'florida-mahjong.html', 'florida-mahjong-hub.html'),
    ('laguna-niguel-ca-ca-mahjong.html', 'Laguna Niguel CA', 'CA', 'california-mahjong.html', 'california-mahjong-hub.html'),
    ('spokane-valley-wa-wa-mahjong.html', 'Spokane Valley WA', 'WA', 'washington-state-mahjong.html', 'washington-mahjong-hub.html'),
    ('costa-mesa-ca-ca-mahjong.html', 'Costa Mesa CA', 'CA', 'california-mahjong.html', 'california-mahjong-hub.html'),
    ('grand-prairie-tx-2-mahjong.html', 'Grand Prairie TX', 'TX', 'texas-mahjong.html', 'texas-mahjong-hub.html'),
    ('portsmouth-va-2-mahjong.html', 'Portsmouth VA', 'VA', 'virginia-mahjong.html', 'virginia-mahjong-hub.html'),
    ('lacey-wa-2-mahjong.html', 'Lacey WA', 'WA', 'washington-state-mahjong.html', 'washington-mahjong-hub.html'),
    ('apex-nc-2-mahjong.html', 'Apex NC', 'NC', 'north-carolina-mahjong.html', 'north-carolina-mahjong-hub.html'),
    ('sioux-city-ia-2-mahjong.html', 'Sioux City IA', 'IA', 'iowa-mahjong.html', 'iowa-mahjong-hub.html'),
    ('encinitas-ca-ca-mahjong.html', 'Encinitas CA', 'CA', 'california-mahjong.html', 'california-mahjong-hub.html'),
    ('spanish-fork-ut-2-mahjong.html', 'Spanish Fork UT', 'UT', 'utah-mahjong.html', 'utah-mahjong-hub.html'),
    ('huntington-park-ca-ca-mahjong.html', 'Huntington Park CA', 'CA', 'california-mahjong.html', 'california-mahjong-hub.html'),
    ('eden-prairie-mn-mn-mahjong.html', 'Eden Prairie MN', 'MN', 'minnesota-mahjong.html', 'minnesota-mahjong-hub.html'),
    ('peoria-az-az-mahjong.html', 'Peoria AZ', 'AZ', 'arizona-mahjong.html', 'arizona-mahjong-hub.html'),
    ('tempe-az-2-mahjong.html', 'Tempe AZ', 'AZ', 'arizona-mahjong.html', 'arizona-mahjong-hub.html'),
    ('wilmington-de-2-mahjong.html', 'Wilmington DE', 'DE', 'delaware-mahjong.html', 'delaware-mahjong-hub.html'),
    ('taylorsville-ut-ut-mahjong.html', 'Taylorsville UT', 'UT', 'utah-mahjong.html', 'utah-mahjong-hub.html'),
    ('westland-mi-mi-mahjong.html', 'Westland MI', 'MI', 'michigan-mahjong.html', 'michigan-mahjong-hub.html'),
    ('mesquite-tx-2-mahjong.html', 'Mesquite TX', 'TX', 'texas-mahjong.html', 'texas-mahjong-hub.html'),
    ('burlington-nc-nc-mahjong.html', 'Burlington NC', 'NC', 'north-carolina-mahjong.html', 'north-carolina-mahjong-hub.html'),
    ('garland-tx-2-mahjong.html', 'Garland TX', 'TX', 'texas-mahjong.html', 'texas-mahjong-hub.html'),
    ('richmond-ca-ca-mahjong.html', 'Richmond CA', 'CA', 'california-mahjong.html', 'california-mahjong-hub.html'),
    ('bismarck-nd-2-mahjong.html', 'Bismarck ND', 'ND', 'north-dakota-mahjong.html', 'north-dakota-mahjong-hub.html'),
    ('carson-city-nv-2-mahjong.html', 'Carson City NV', 'NV', 'nevada-mahjong.html', 'nevada-mahjong-hub.html'),
    ('muskogee-ok-2-mahjong.html', 'Muskogee OK', 'OK', 'oklahoma-mahjong.html', 'oklahoma-mahjong-hub.html'),
    ('augusta-richmond-county-ga-ga-mahjong.html', 'Augusta-Richmond County GA', 'GA', 'georgia-mahjong.html', 'georgia-mahjong-hub.html'),
    ('fayetteville-nc-2-mahjong.html', 'Fayetteville NC', 'NC', 'north-carolina-mahjong.html', 'north-carolina-mahjong-hub.html'),
    ('albany-ga-ga-mahjong.html', 'Albany GA', 'GA', 'georgia-mahjong.html', 'georgia-mahjong-hub.html'),
    ('sayreville-nj-nj-mahjong.html', 'Sayreville NJ', 'NJ', 'new-jersey-mahjong.html', 'new-jersey-mahjong-hub.html'),
    ('newark-ca-ca-mahjong.html', 'Newark CA', 'CA', 'california-mahjong.html', 'california-mahjong-hub.html'),
    ('diamond-bar-ca-ca-mahjong.html', 'Diamond Bar CA', 'CA', 'california-mahjong.html', 'california-mahjong-hub.html'),
    ('decatur-al-2-mahjong.html', 'Decatur AL', 'AL', 'alabama-mahjong.html', 'alabama-mahjong-hub.html'),
    ('chattanooga-tn-tn-mahjong.html', 'Chattanooga TN', 'TN', 'tennessee-mahjong.html', 'tennessee-mahjong-hub.html'),
    ('jeffersonville-in-2-mahjong.html', 'Jeffersonville IN', 'IN', 'indiana-mahjong.html', 'indiana-mahjong-hub.html'),
    ('bartlett-il-il-mahjong.html', 'Bartlett IL', 'IL', 'illinois-mahjong.html', 'illinois-mahjong-hub.html'),
    ('baldwin-park-ca-ca-mahjong.html', 'Baldwin Park CA', 'CA', 'california-mahjong.html', 'california-mahjong-hub.html'),
    ('miami-beach-fl-fl-mahjong.html', 'Miami Beach FL', 'FL', 'florida-mahjong.html', 'florida-mahjong-hub.html'),
    ('jackson-tn-2-mahjong.html', 'Jackson TN', 'TN', 'tennessee-mahjong.html', 'tennessee-mahjong-hub.html'),
    ('port-arthur-tx-tx-mahjong.html', 'Port Arthur TX', 'TX', 'texas-mahjong.html', 'texas-mahjong-hub.html'),
    ('san-luis-obispo-ca-2-mahjong.html', 'San Luis Obispo CA', 'CA', 'california-mahjong.html', 'california-mahjong-hub.html'),
    ('burleson-tx-tx-mahjong.html', 'Burleson TX', 'TX', 'texas-mahjong.html', 'texas-mahjong-hub.html'),
    ('newport-beach-ca-ca-mahjong.html', 'Newport Beach CA', 'CA', 'california-mahjong.html', 'california-mahjong-hub.html'),
    ('riverton-ut-ut-mahjong.html', 'Riverton UT', 'UT', 'utah-mahjong.html', 'utah-mahjong-hub.html'),
    ('yakima-wa-2-mahjong.html', 'Yakima WA', 'WA', 'washington-state-mahjong.html', 'washington-mahjong-hub.html'),
    ('dayton-oh-2-mahjong.html', 'Dayton OH', 'OH', 'ohio-mahjong.html', 'ohio-mahjong-hub.html'),
    ('gulfport-ms-2-mahjong.html', 'Gulfport MS', 'MS', 'mississippi-mahjong.html', 'mississippi-mahjong-hub.html'),
    ('long-beach-ca-ca-mahjong.html', 'Long Beach CA', 'CA', 'california-mahjong.html', 'california-mahjong-hub.html'),
    ('chico-ca-2-mahjong.html', 'Chico CA', 'CA', 'california-mahjong.html', 'california-mahjong-hub.html'),
    ('hattiesburg-ms-2-mahjong.html', 'Hattiesburg MS', 'MS', 'mississippi-mahjong.html', 'mississippi-mahjong-hub.html'),
    ('eugene-or-2-mahjong.html', 'Eugene OR', 'OR', 'oregon-mahjong.html', 'oregon-mahjong-hub.html'),
    ('colton-ca-ca-mahjong.html', 'Colton CA', 'CA', 'california-mahjong.html', 'california-mahjong-hub.html'),
    ('montebello-ca-ca-mahjong.html', 'Montebello CA', 'CA', 'california-mahjong.html', 'california-mahjong-hub.html'),
    ('pleasanton-ca-ca-mahjong.html', 'Pleasanton CA', 'CA', 'california-mahjong.html', 'california-mahjong-hub.html'),
    ('everett-wa-wa-mahjong.html', 'Everett WA', 'WA', 'washington-state-mahjong.html', 'washington-mahjong-hub.html'),
    ('hutchinson-ks-2-mahjong.html', 'Hutchinson KS', 'KS', 'kansas-mahjong.html', 'kansas-mahjong-hub.html'),
    ('fairfield-ca-2-mahjong.html', 'Fairfield CA', 'CA', 'california-mahjong.html', 'california-mahjong-hub.html'),
    ('avondale-az-az-mahjong.html', 'Avondale AZ', 'AZ', 'arizona-mahjong.html', 'arizona-mahjong-hub.html'),
    ('euclid-oh-oh-mahjong.html', 'Euclid OH', 'OH', 'ohio-mahjong.html', 'ohio-mahjong-hub.html'),
    ('battle-creek-mi-2-mahjong.html', 'Battle Creek MI', 'MI', 'michigan-mahjong.html', 'michigan-mahjong-hub.html'),
    ('bloomington-mn-2-mahjong.html', 'Bloomington MN', 'MN', 'minnesota-mahjong.html', 'minnesota-mahjong-hub.html'),
    ('rock-island-il-il-mahjong.html', 'Rock Island IL', 'IL', 'illinois-mahjong.html', 'illinois-mahjong-hub.html'),
    ('beaverton-or-2-mahjong.html', 'Beaverton OR', 'OR', 'oregon-mahjong.html', 'oregon-mahjong-hub.html'),
    ('kenner-la-2-mahjong.html', 'Kenner LA', 'LA', 'louisiana-mahjong.html', 'louisiana-mahjong-hub.html'),
    ('clovis-nm-2-mahjong.html', 'Clovis NM', 'NM', 'new-mexico-mahjong.html', 'new-mexico-mahjong-hub.html'),
    ('troy-ny-2-mahjong.html', 'Troy NY', 'NY', 'new-york-mahjong.html', 'new-york-mahjong-hub.html'),
    ('milpitas-ca-ca-mahjong.html', 'Milpitas CA', 'CA', 'california-mahjong.html', 'california-mahjong-hub.html'),
    ('des-plaines-il-il-mahjong.html', 'Des Plaines IL', 'IL', 'illinois-mahjong.html', 'illinois-mahjong-hub.html'),
    ('placentia-ca-ca-mahjong.html', 'Placentia CA', 'CA', 'california-mahjong.html', 'california-mahjong-hub.html'),
    ('taunton-ma-2-mahjong.html', 'Taunton MA', 'MA', 'massachusetts-mahjong.html', 'massachusetts-mahjong-hub.html'),
    ('montclair-ca-ca-mahjong.html', 'Montclair CA', 'CA', 'california-mahjong.html', 'california-mahjong-hub.html'),
    ('johnson-city-tn-2-mahjong.html', 'Johnson City TN', 'TN', 'tennessee-mahjong.html', 'tennessee-mahjong-hub.html'),
    ('savannah-ga-ga-mahjong.html', 'Savannah GA', 'GA', 'georgia-mahjong.html', 'georgia-mahjong-hub.html'),
    ('warren-oh-2-mahjong.html', 'Warren OH', 'OH', 'ohio-mahjong.html', 'ohio-mahjong-hub.html'),
    ('vancouver-wa-2-mahjong.html', 'Vancouver WA', 'WA', 'washington-state-mahjong.html', 'washington-mahjong-hub.html'),
    ('sunrise-fl-fl-mahjong.html', 'Sunrise FL', 'FL', 'florida-mahjong.html', 'florida-mahjong-hub.html'),
    ('muncie-in-2-mahjong.html', 'Muncie IN', 'IN', 'indiana-mahjong.html', 'indiana-mahjong-hub.html'),
    ('lehi-ut-2-mahjong.html', 'Lehi UT', 'UT', 'utah-mahjong.html', 'utah-mahjong-hub.html'),
]
