name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Minify production assets
        run: |
          npm install -g terser clean-css-cli
          terser script.js -c passes=2 -m -o script.js
          terser shop.js -c passes=2 -m -o shop.js
          terser analytics.js -c passes=2 -m -o analytics.js
          cleancss -o critical.css critical.css
          cleancss -o fonts/fonts.css fonts/fonts.css
          cleancss -o styles.css styles.css
      - name: Setup Pages
        uses: actions/configure-pages@v4
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
